"""Public API for the 1D & 2D Ising Monte Carlo Lab."""

from .core import (
    Dimension,
    IsingParams,
    Method,
    all_plus_energy,
    energy,
    estimate_equilibration_sweep,
    exact_1d,
    exact_2d_onsager,
    exact_observables,
    finite_size_scan,
    initial_state,
    magnetization,
    magnetization_estimators,
    method_comparison,
    n_sites,
    notebook_temperature_grid,
    onsager_tc,
    simulate,
    sweep,
    thermodynamic_scan,
)

__all__ = [
    "Dimension",
    "IsingParams",
    "Method",
    "all_plus_energy",
    "energy",
    "estimate_equilibration_sweep",
    "exact_1d",
    "exact_2d_onsager",
    "exact_observables",
    "finite_size_scan",
    "initial_state",
    "magnetization",
    "magnetization_estimators",
    "method_comparison",
    "n_sites",
    "notebook_temperature_grid",
    "onsager_tc",
    "simulate",
    "sweep",
    "thermodynamic_scan",
]
