import type { QuestionnaireItem } from "@/lib/types";

function frq(id:string, conceptIntro:string, prompt:string, answerKey:string, rationale:string, scoringGuide:string[], hints:string[], examSection:string, conceptId?:string): QuestionnaireItem {
  return { id, format:"frq_half", conceptId, conceptIntro, authenticity:"exam_authentic", responseMode:"extended_response", difficultyTier:3, prompt, answerKey, rationale, scoringGuide, hints, examSection };
}

export const recoveredApItemsBatch4C: Record<string, QuestionnaireItem> = {
  "phys1-en-c1": frq(
    "phys1-en-c1",
    "Section II · Physics 1 energy, friction, and spring modeling.",
    "A 0.40 kg block compresses a horizontal spring (k=200 N/m) by 0.10 m. The block is released and moves across a 0.60 m rough patch before reaching the spring's natural-length position. The coefficient of kinetic friction is 0.20 and g=9.8 m/s². (a) Calculate the initial spring energy. (b) Calculate the thermal energy generated by friction. (c) Determine the block's speed when the spring reaches natural length. (d) Find the minimum initial compression required for the block to just reach natural length with zero speed under the same conditions, and explain why this threshold is physically meaningful.",
    "Initial spring energy is 0.5(200)(0.10²)=1.00 J. Friction removes μkmgd=0.20(0.40)(9.8)(0.60)=0.4704 J. Final kinetic energy is 0.5296 J, so v=sqrt(2K/m)=1.63 m/s. For just reaching natural length, 0.5kx²=0.4704, giving x=0.0686 m. Below this compression the spring does not supply enough energy to overcome friction across the patch.",
    "The rewrite requires energy accounting with a nonconservative force and a threshold case.",
    ["1 point: 1.00 J spring energy.","1 point: 0.4704 J thermal loss.","1 point: v≈1.63 m/s.","1 point: threshold compression≈0.0686 m with interpretation."],
    ["Use W_nc=ΔK+ΔU.","At the threshold the final kinetic energy is zero."],
    "Section II · Mathematical Routines","energy-work"
  ),
  "phys1-en-c2": frq(
    "phys1-en-c2",
    "Section II · Physics 1 translation between force and energy representations.",
    "Two frictionless ramps connect the same starting height h to the same floor. Ramp A is steep and short; Ramp B is shallow and long. Identical blocks are released from rest. (a) Compare final speeds and justify using energy. (b) Compare average acceleration magnitudes and explain why equal final speed does not imply equal acceleration history. (c) If the same coefficient of kinetic friction is added to both ramps, explain why final speeds generally need not remain equal. (d) State one condition under which an energy method is more efficient than solving the full time-dependent Newton's-law motion.",
    "With no friction both satisfy mgh=0.5mv², so they have equal final speed sqrt(2gh). The steeper ramp has larger tangential acceleration g sinθ, even though it acts over a shorter path. With friction, dissipated work μkmg cosθ times path length can differ between ramps, so final energies can differ. Energy methods are efficient when only initial/final states matter and nonconservative work can be computed directly.",
    "The item distinguishes state-based energy reasoning from path-dependent dynamics and friction.",
    ["1 point: equal frictionless final speeds.","1 point: correct acceleration comparison.","1 point: explains path-dependent friction loss.","1 point: valid condition favoring energy method."],
    ["Equal energy change does not mean equal acceleration at each point.","Frictional work depends on path details."],
    "Section II · Qualitative/Quantitative Translation","energy-work"
  ),
  "phys1-mom-c1": frq(
    "phys1-mom-c1",
    "Section II · Physics 1 two-dimensional momentum and model consistency.",
    "A 3.0 kg cart moves east at 2.0 m/s and collides with a 1.0 kg cart initially at rest. After the interaction, the 1.0 kg cart moves north at 3.0 m/s. External horizontal impulse is negligible. (a) Determine both components of the 3.0 kg cart's final velocity. (b) Determine its final speed and direction. (c) Calculate initial and final total kinetic energy. (d) Explain what the kinetic-energy result implies about the physical nature of the interaction.",
    "Initial momentum=(6,0) kg·m/s. The 1-kg cart ends with momentum=(0,3), so the 3-kg cart has momentum=(6,-3) and velocity=(2,-1) m/s. Its speed is sqrt(5)=2.24 m/s at 26.6° south of east. Initial K=6 J; final K=7.5+4.5=12 J. Because kinetic energy increases while momentum is conserved, the interaction must release internal stored energy or include an active mechanism; it is not an ordinary passive elastic/inelastic collision.",
    "This uses the original data to expose and reason through a hidden physical consistency issue.",
    ["1 point: velocity components (2,-1) m/s.","1 point: speed and direction.","1 point: Ki=6 J and Kf=12 J.","1 point: correct interpretation of increased kinetic energy."],
    ["Conserve x and y momentum separately.","Always check whether the kinetic-energy result matches the assumed interaction."],
    "Section II · Mathematical Routines","momentum"
  ),
  "phys1-mom-c2": frq(
    "phys1-mom-c2",
    "Section II · Physics 1 impulse, force-time graphs, and injury reduction.",
    "A 70 kg passenger moving at 15 m/s is brought to rest. With a rigid restraint the stopping time is 0.040 s; with an airbag it is 0.16 s. (a) Calculate average net force magnitude in each case. (b) Compare the impulses. (c) Describe two force-time graphs with equal area but different peak force. (d) Explain why the longer stopping time can reduce injury risk and identify one limitation of using average force alone to assess injury.",
    "The momentum change magnitude is 1050 kg·m/s. Average forces are 26,250 N and 6,562.5 N respectively. The impulses are equal because both bring the same mass from the same initial speed to rest. Equal-area force-time curves can have different width and peak height. Injury also depends on peak force, pressure distribution, body region, and acceleration history, so average force alone is incomplete.",
    "The problem connects quantitative impulse with force-time representation and a limitation of the model.",
    ["1 point: both average-force calculations.","1 point: equal impulse explanation.","1 point: valid equal-area/different-peak graph description.","1 point: injury explanation plus model limitation."],
    ["Impulse is the area under F-t.","Same momentum change does not require the same peak force."],
    "Section II · Qualitative/Quantitative Translation","momentum"
  ),
  "phys1-shm-c1": frq(
    "phys1-shm-c1",
    "Section II · Physics 1 SHM inference, uncertainty, and scaling.",
    "A 0.250 kg mass oscillates on an ideal spring with measured period 0.800 s. (a) Calculate the spring constant. (b) If period uncertainty is ±0.010 s and mass uncertainty is negligible, estimate the fractional uncertainty in k. (c) Predict the period if the mass is doubled. (d) Explain why doubling amplitude does not change period in the ideal Hooke-law model but may do so for a real spring at large amplitude.",
    "k=4π²m/T²=15.42 N/m. Since k∝T^-2, fractional uncertainty≈2(0.010/0.800)=2.5%, so Δk≈0.39 N/m. Doubling mass multiplies period by sqrt2, giving 1.13 s. Ideal linear SHM is amplitude-independent; real springs can become nonlinear at large deformation.",
    "The task combines parameter extraction, uncertainty, scaling, and model limits.",
    ["1 point: k≈15.4 N/m.","1 point: ~2.5% uncertainty.","1 point: T_new≈1.13 s.","1 point: correct ideal-versus-real amplitude explanation."],
    ["k varies as 1/T².","For fixed k, T varies as sqrt(m)."],
    "Section II · Mathematical Routines","shm"
  ),
  "phys1-shm-c2": frq(
    "phys1-shm-c2",
    "Section II · Physics 1 SHM energy and phase reasoning.",
    "A mass-spring oscillator has amplitude A and total mechanical energy E. (a) State kinetic and spring-potential energies at x=A, x=0, and x=A/2. Express the x=A/2 values as fractions of E. (b) Determine speed at x=A/2 as a fraction of maximum speed. (c) Explain why acceleration magnitude is maximum where speed is zero. (d) If weak damping is introduced, describe how turning points and total mechanical energy change over many cycles.",
    "At x=A: U=E,K=0. At x=0: U=0,K=E. At x=A/2, U=E/4 and K=3E/4. Therefore v/vmax=sqrt(3/4)=sqrt3/2. Since a=-ω²x, acceleration magnitude is greatest at |x|=A even though the mass instantaneously stops there. With damping, total energy and successive amplitudes decrease.",
    "This integrates energy, speed, acceleration, and damping rather than isolated recall.",
    ["1 point: correct energy states.","1 point: v/vmax=sqrt3/2.","1 point: correct acceleration explanation.","1 point: correct damping trend."],
    ["Spring potential energy scales as x².","Acceleration depends on displacement, not velocity."],
    "Section II · Mathematical Routines","shm"
  ),
  "calc-int-c1": frq(
    "calc-int-c1",
    "Section II · Calculus area, parameter dependence, and average value.",
    "For 0<a<1, consider y=x and y=x² on [0,a]. (a) Write and evaluate the area A(a) between the curves. (b) Find a in (0,1) for which A(a)=1/12. (c) Find the average vertical separation between the curves on [0,1]. (d) Explain why absolute value is unnecessary on [0,1] but may be required if the interval crosses a point where the curves exchange order.",
    "A(a)=∫0^a(x-x²)dx=a²/2-a³/3. Setting A=1/12 gives a=1/2 in (0,1). The average separation on [0,1] is ∫0^1(x-x²)dx=1/6. Since x≥x² on [0,1], the integrand is nonnegative; if the ordering changes, signed area can cancel and a piecewise/absolute-value setup is needed for geometric area.",
    "The rewrite deepens a one-step area calculation into parameter solving and signed-area reasoning.",
    ["1 point: correct A(a).","1 point: a=1/2.","1 point: average separation=1/6.","1 point: correct absolute-value explanation."],
    ["Determine which curve is on top.","Average value is integral divided by interval length."],
    "Section II · Free Response (no calculator)","integrals-basics"
  )
};
