import type { EnglishPracticeQuestion } from "./english-content";

/** Batch 3 — auto-generated by scripts/generate-english-batch3.ts */
export const batch3ToeflQuestions: EnglishPracticeQuestion[] = [
  {
    "id": "toefl-batch3-1",
    "skill": "Listening inference",
    "prompt": "[Batch 3 · Listening inference] A university article about lab safety reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-2",
    "skill": "Listening purpose",
    "prompt": "[Batch 3 · Listening purpose] A university article about library hours reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-3",
    "skill": "Writing coherence",
    "prompt": "[Batch 3 · Writing coherence] A university article about study groups reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-4",
    "skill": "Speaking clarity",
    "prompt": "[Batch 3 · Speaking clarity] A university article about research ethics reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-5",
    "skill": "Reading detail",
    "prompt": "[Batch 3 · Reading detail] A university article about campus dining reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-6",
    "skill": "Grammar in context",
    "prompt": "[Batch 3 · Grammar in context] A university article about lab safety reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-7",
    "skill": "Academic Discussion",
    "prompt": "[Batch 3 · Academic Discussion] A university article about library hours reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-8",
    "skill": "Academic Reading",
    "prompt": "[Batch 3 · Academic Reading] A university article about study groups reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-9",
    "skill": "Listening inference",
    "prompt": "[Batch 3 · Listening inference] A university article about research ethics reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-10",
    "skill": "Listening purpose",
    "prompt": "[Batch 3 · Listening purpose] A university article about campus dining reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-11",
    "skill": "Writing coherence",
    "prompt": "[Batch 3 · Writing coherence] A university article about lab safety reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-12",
    "skill": "Speaking clarity",
    "prompt": "[Batch 3 · Speaking clarity] A university article about library hours reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-13",
    "skill": "Reading detail",
    "prompt": "[Batch 3 · Reading detail] A university article about study groups reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-14",
    "skill": "Grammar in context",
    "prompt": "[Batch 3 · Grammar in context] A university article about research ethics reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-15",
    "skill": "Academic Discussion",
    "prompt": "[Batch 3 · Academic Discussion] A university article about campus dining reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-16",
    "skill": "Academic Reading",
    "prompt": "[Batch 3 · Academic Reading] A university article about lab safety reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-17",
    "skill": "Listening inference",
    "prompt": "[Batch 3 · Listening inference] A university article about library hours reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-18",
    "skill": "Listening purpose",
    "prompt": "[Batch 3 · Listening purpose] A university article about study groups reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-19",
    "skill": "Writing coherence",
    "prompt": "[Batch 3 · Writing coherence] A university article about research ethics reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-20",
    "skill": "Speaking clarity",
    "prompt": "[Batch 3 · Speaking clarity] A university article about campus dining reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-21",
    "skill": "Reading detail",
    "prompt": "[Batch 3 · Reading detail] A university article about lab safety reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-22",
    "skill": "Grammar in context",
    "prompt": "[Batch 3 · Grammar in context] A university article about library hours reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-23",
    "skill": "Academic Discussion",
    "prompt": "[Batch 3 · Academic Discussion] A university article about study groups reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-24",
    "skill": "Academic Reading",
    "prompt": "[Batch 3 · Academic Reading] A university article about research ethics reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-25",
    "skill": "Listening inference",
    "prompt": "[Batch 3 · Listening inference] A university article about campus dining reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-26",
    "skill": "Listening purpose",
    "prompt": "[Batch 3 · Listening purpose] A university article about lab safety reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-27",
    "skill": "Writing coherence",
    "prompt": "[Batch 3 · Writing coherence] A university article about library hours reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-28",
    "skill": "Speaking clarity",
    "prompt": "[Batch 3 · Speaking clarity] A university article about study groups reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-29",
    "skill": "Reading detail",
    "prompt": "[Batch 3 · Reading detail] A university article about research ethics reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-30",
    "skill": "Grammar in context",
    "prompt": "[Batch 3 · Grammar in context] A university article about campus dining reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  },
  {
    "id": "toefl-batch3-31",
    "skill": "Academic Discussion",
    "prompt": "[Batch 3 · Academic Discussion] A university article about lab safety reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?",
    "choices": [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study."
    ],
    "answer": 1,
    "explanation": "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported."
  }
];

export const batch3SatQuestions: EnglishPracticeQuestion[] = [
  {
    "id": "sat-batch3-1",
    "skill": "Transitions",
    "prompt": "[Batch 3 · Transitions] Which sentence best strengthens a paragraph about sustainable transit in city 1?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  },
  {
    "id": "sat-batch3-2",
    "skill": "Information and Ideas",
    "prompt": "[Batch 3 · Information and Ideas] Which sentence best strengthens a paragraph about sustainable transit in city 2?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  },
  {
    "id": "sat-batch3-3",
    "skill": "Expression of Ideas",
    "prompt": "[Batch 3 · Expression of Ideas] Which sentence best strengthens a paragraph about sustainable transit in city 3?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  },
  {
    "id": "sat-batch3-4",
    "skill": "Central Ideas",
    "prompt": "[Batch 3 · Central Ideas] Which sentence best strengthens a paragraph about sustainable transit in city 4?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  },
  {
    "id": "sat-batch3-5",
    "skill": "Algebra",
    "prompt": "[Batch 3 · Algebra] If 7x − 5 = 49, what is x?",
    "choices": [
      "7",
      "8",
      "6",
      "9"
    ],
    "answer": 0,
    "explanation": "Solve: 7x − 5 = 49 ⇒ x = 7."
  },
  {
    "id": "sat-batch3-6",
    "skill": "Data interpretation",
    "prompt": "[Batch 3 · Data interpretation] Which sentence best strengthens a paragraph about sustainable transit in city 6?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  },
  {
    "id": "sat-batch3-7",
    "skill": "Rhetoric",
    "prompt": "[Batch 3 · Rhetoric] Which sentence best strengthens a paragraph about sustainable transit in city 7?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  },
  {
    "id": "sat-batch3-8",
    "skill": "Linear equations",
    "prompt": "[Batch 3 · Linear equations] If 10x − 8 = 100, what is x?",
    "choices": [
      "10",
      "11",
      "9",
      "12"
    ],
    "answer": 0,
    "explanation": "Solve: 10x − 8 = 100 ⇒ x = 10."
  },
  {
    "id": "sat-batch3-9",
    "skill": "Words in context",
    "prompt": "[Batch 3 · Words in context] Which sentence best strengthens a paragraph about sustainable transit in city 9?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  },
  {
    "id": "sat-batch3-10",
    "skill": "Standard English Conventions",
    "prompt": "[Batch 3 · Standard English Conventions] Which sentence best strengthens a paragraph about sustainable transit in city 10?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  },
  {
    "id": "sat-batch3-11",
    "skill": "Transitions",
    "prompt": "[Batch 3 · Transitions] Which sentence best strengthens a paragraph about sustainable transit in city 11?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  },
  {
    "id": "sat-batch3-12",
    "skill": "Information and Ideas",
    "prompt": "[Batch 3 · Information and Ideas] Which sentence best strengthens a paragraph about sustainable transit in city 12?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  },
  {
    "id": "sat-batch3-13",
    "skill": "Expression of Ideas",
    "prompt": "[Batch 3 · Expression of Ideas] Which sentence best strengthens a paragraph about sustainable transit in city 13?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  },
  {
    "id": "sat-batch3-14",
    "skill": "Central Ideas",
    "prompt": "[Batch 3 · Central Ideas] Which sentence best strengthens a paragraph about sustainable transit in city 14?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  },
  {
    "id": "sat-batch3-15",
    "skill": "Algebra",
    "prompt": "[Batch 3 · Algebra] If 17x − 15 = 289, what is x?",
    "choices": [
      "17",
      "18",
      "16",
      "19"
    ],
    "answer": 0,
    "explanation": "Solve: 17x − 15 = 289 ⇒ x = 17."
  },
  {
    "id": "sat-batch3-16",
    "skill": "Data interpretation",
    "prompt": "[Batch 3 · Data interpretation] Which sentence best strengthens a paragraph about sustainable transit in city 16?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  },
  {
    "id": "sat-batch3-17",
    "skill": "Rhetoric",
    "prompt": "[Batch 3 · Rhetoric] Which sentence best strengthens a paragraph about sustainable transit in city 17?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  },
  {
    "id": "sat-batch3-18",
    "skill": "Linear equations",
    "prompt": "[Batch 3 · Linear equations] If 20x − 18 = 400, what is x?",
    "choices": [
      "20",
      "21",
      "19",
      "22"
    ],
    "answer": 0,
    "explanation": "Solve: 20x − 18 = 400 ⇒ x = 20."
  },
  {
    "id": "sat-batch3-19",
    "skill": "Words in context",
    "prompt": "[Batch 3 · Words in context] Which sentence best strengthens a paragraph about sustainable transit in city 19?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  },
  {
    "id": "sat-batch3-20",
    "skill": "Standard English Conventions",
    "prompt": "[Batch 3 · Standard English Conventions] Which sentence best strengthens a paragraph about sustainable transit in city 20?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  },
  {
    "id": "sat-batch3-21",
    "skill": "Transitions",
    "prompt": "[Batch 3 · Transitions] Which sentence best strengthens a paragraph about sustainable transit in city 21?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  },
  {
    "id": "sat-batch3-22",
    "skill": "Information and Ideas",
    "prompt": "[Batch 3 · Information and Ideas] Which sentence best strengthens a paragraph about sustainable transit in city 22?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  },
  {
    "id": "sat-batch3-23",
    "skill": "Expression of Ideas",
    "prompt": "[Batch 3 · Expression of Ideas] Which sentence best strengthens a paragraph about sustainable transit in city 23?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  },
  {
    "id": "sat-batch3-24",
    "skill": "Central Ideas",
    "prompt": "[Batch 3 · Central Ideas] Which sentence best strengthens a paragraph about sustainable transit in city 24?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  },
  {
    "id": "sat-batch3-25",
    "skill": "Algebra",
    "prompt": "[Batch 3 · Algebra] If 27x − 25 = 729, what is x?",
    "choices": [
      "27",
      "28",
      "26",
      "29"
    ],
    "answer": 0,
    "explanation": "Solve: 27x − 25 = 729 ⇒ x = 27."
  },
  {
    "id": "sat-batch3-26",
    "skill": "Data interpretation",
    "prompt": "[Batch 3 · Data interpretation] Which sentence best strengthens a paragraph about sustainable transit in city 26?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  },
  {
    "id": "sat-batch3-27",
    "skill": "Rhetoric",
    "prompt": "[Batch 3 · Rhetoric] Which sentence best strengthens a paragraph about sustainable transit in city 27?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  },
  {
    "id": "sat-batch3-28",
    "skill": "Linear equations",
    "prompt": "[Batch 3 · Linear equations] If 30x − 28 = 900, what is x?",
    "choices": [
      "30",
      "31",
      "29",
      "32"
    ],
    "answer": 0,
    "explanation": "Solve: 30x − 28 = 900 ⇒ x = 30."
  },
  {
    "id": "sat-batch3-29",
    "skill": "Words in context",
    "prompt": "[Batch 3 · Words in context] Which sentence best strengthens a paragraph about sustainable transit in city 29?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  },
  {
    "id": "sat-batch3-30",
    "skill": "Standard English Conventions",
    "prompt": "[Batch 3 · Standard English Conventions] Which sentence best strengthens a paragraph about sustainable transit in city 30?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  },
  {
    "id": "sat-batch3-31",
    "skill": "Transitions",
    "prompt": "[Batch 3 · Transitions] Which sentence best strengthens a paragraph about sustainable transit in city 31?",
    "choices": [
      "Buses exist in many places.",
      "After a pilot added bus lanes, commute times fell 12% on the route studied.",
      "Transportation is important.",
      "Some people dislike traffic."
    ],
    "answer": 1,
    "explanation": "A specific, relevant statistic directly supports the paragraph's claim."
  }
];
