import type { EnglishPracticeQuestion } from "./english-content";

/** Curated extended bank — replaces batch3 templates. Generated by scripts/generate-curated-extended.ts */
export const curatedExtendedToeflQuestions: EnglishPracticeQuestion[] = [
  {
    "id": "toefl-curated-ext-1",
    "skill": "Listening inference",
    "prompt": "A study of renewable energy found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  },
  {
    "id": "toefl-curated-ext-2",
    "skill": "Listening purpose",
    "prompt": "A study of public health found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  },
  {
    "id": "toefl-curated-ext-3",
    "skill": "Writing coherence",
    "prompt": "A study of urban farming found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  },
  {
    "id": "toefl-curated-ext-4",
    "skill": "Speaking clarity",
    "prompt": "A study of digital archives found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  },
  {
    "id": "toefl-curated-ext-5",
    "skill": "Reading detail",
    "prompt": "A study of language acquisition found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  },
  {
    "id": "toefl-curated-ext-6",
    "skill": "Grammar in context",
    "prompt": "The team ___ its microplastics report after revising the methodology.",
    "choices": [
      "publish",
      "publishes",
      "reviewed",
      "publishing"
    ],
    "answer": 2,
    "explanation": "Past tense \"reviewed\" fits a completed reporting action."
  },
  {
    "id": "toefl-curated-ext-7",
    "skill": "Academic Discussion",
    "prompt": "A study of sleep research found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  },
  {
    "id": "toefl-curated-ext-8",
    "skill": "Complete the Words",
    "prompt": "Researchers could not yet con___dence the volunteer programs data without a larger sample.",
    "choices": [
      "evi",
      "tra",
      "tre",
      "tro"
    ],
    "answer": 0,
    "explanation": "The complete word is evidence. Context supports a research finding that needs more data."
  },
  {
    "id": "toefl-curated-ext-9",
    "skill": "Academic Reading",
    "prompt": "A study of museum attendance found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  },
  {
    "id": "toefl-curated-ext-10",
    "skill": "Listening inference",
    "prompt": "A study of campus housing found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  },
  {
    "id": "toefl-curated-ext-11",
    "skill": "Listening purpose",
    "prompt": "A study of renewable energy found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  },
  {
    "id": "toefl-curated-ext-12",
    "skill": "Writing coherence",
    "prompt": "A study of public health found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  },
  {
    "id": "toefl-curated-ext-13",
    "skill": "Speaking clarity",
    "prompt": "A study of urban farming found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  },
  {
    "id": "toefl-curated-ext-14",
    "skill": "Reading detail",
    "prompt": "A study of digital archives found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  },
  {
    "id": "toefl-curated-ext-15",
    "skill": "Grammar in context",
    "prompt": "The team ___ its language acquisition report after revising the methodology.",
    "choices": [
      "publish",
      "publishes",
      "presented",
      "publishing"
    ],
    "answer": 2,
    "explanation": "Past tense \"presented\" fits a completed reporting action."
  },
  {
    "id": "toefl-curated-ext-16",
    "skill": "Academic Discussion",
    "prompt": "A study of microplastics found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  },
  {
    "id": "toefl-curated-ext-17",
    "skill": "Complete the Words",
    "prompt": "Researchers could not yet con___ucture the sleep research data without a larger sample.",
    "choices": [
      "str",
      "tra",
      "tre",
      "tro"
    ],
    "answer": 0,
    "explanation": "The complete word is structure. Context supports a research finding that needs more data."
  },
  {
    "id": "toefl-curated-ext-18",
    "skill": "Academic Reading",
    "prompt": "A study of volunteer programs found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  },
  {
    "id": "toefl-curated-ext-19",
    "skill": "Listening inference",
    "prompt": "A study of museum attendance found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  },
  {
    "id": "toefl-curated-ext-20",
    "skill": "Listening purpose",
    "prompt": "A study of campus housing found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  },
  {
    "id": "toefl-curated-ext-21",
    "skill": "Writing coherence",
    "prompt": "A study of renewable energy found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  },
  {
    "id": "toefl-curated-ext-22",
    "skill": "Speaking clarity",
    "prompt": "A study of public health found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  },
  {
    "id": "toefl-curated-ext-23",
    "skill": "Reading detail",
    "prompt": "A study of urban farming found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  },
  {
    "id": "toefl-curated-ext-24",
    "skill": "Grammar in context",
    "prompt": "The team ___ its digital archives report after revising the methodology.",
    "choices": [
      "publish",
      "publishes",
      "published",
      "publishing"
    ],
    "answer": 2,
    "explanation": "Past tense \"published\" fits a completed reporting action."
  },
  {
    "id": "toefl-curated-ext-25",
    "skill": "Academic Discussion",
    "prompt": "A study of language acquisition found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  },
  {
    "id": "toefl-curated-ext-26",
    "skill": "Complete the Words",
    "prompt": "Researchers could not yet con___lysis the microplastics data without a larger sample.",
    "choices": [
      "ana",
      "tra",
      "tre",
      "tro"
    ],
    "answer": 0,
    "explanation": "The complete word is analysis. Context supports a research finding that needs more data."
  },
  {
    "id": "toefl-curated-ext-27",
    "skill": "Academic Reading",
    "prompt": "A study of sleep research found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  },
  {
    "id": "toefl-curated-ext-28",
    "skill": "Listening inference",
    "prompt": "A study of volunteer programs found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  },
  {
    "id": "toefl-curated-ext-29",
    "skill": "Listening purpose",
    "prompt": "A study of museum attendance found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  },
  {
    "id": "toefl-curated-ext-30",
    "skill": "Writing coherence",
    "prompt": "A study of campus housing found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  },
  {
    "id": "toefl-curated-ext-31",
    "skill": "Speaking clarity",
    "prompt": "A study of renewable energy found benefits in one area but no change in another. Which conclusion is best supported?",
    "choices": [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day."
    ],
    "answer": 1,
    "explanation": "When results are mixed, a balanced conclusion that matches both findings is best supported."
  }
];

export const curatedExtendedSatQuestions: EnglishPracticeQuestion[] = [
  {
    "id": "sat-curated-ext-1",
    "skill": "Transitions",
    "prompt": "Which sentence best supports a paragraph about library programs?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on library programs reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  },
  {
    "id": "sat-curated-ext-2",
    "skill": "Information and Ideas",
    "prompt": "Which sentence best supports a paragraph about transit policy?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on transit policy reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  },
  {
    "id": "sat-curated-ext-3",
    "skill": "Expression of Ideas",
    "prompt": "Which sentence best supports a paragraph about student journalism?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on student journalism reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  },
  {
    "id": "sat-curated-ext-4",
    "skill": "Central Ideas",
    "prompt": "Which sentence best supports a paragraph about water conservation?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on water conservation reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  },
  {
    "id": "sat-curated-ext-5",
    "skill": "Algebra",
    "prompt": "If 8x + 7 = 11, what is x?",
    "choices": [
      "6",
      "8",
      "9",
      "10"
    ],
    "answer": 0,
    "explanation": "Subtract 7 and divide by 8: x = 6."
  },
  {
    "id": "sat-curated-ext-6",
    "skill": "Data interpretation",
    "prompt": "Which sentence best supports a paragraph about science fairs?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on science fairs reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  },
  {
    "id": "sat-curated-ext-7",
    "skill": "Rhetoric",
    "prompt": "Which sentence best supports a paragraph about music education?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on music education reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  },
  {
    "id": "sat-curated-ext-8",
    "skill": "Linear equations",
    "prompt": "Which equation represents a line with slope 2 and y-intercept 5?",
    "choices": [
      "y = 2x + 5",
      "y = 5x + 2",
      "y = -2x + 5",
      "y = 2x - 5"
    ],
    "answer": 0,
    "explanation": "Slope-intercept form is y = mx + b."
  },
  {
    "id": "sat-curated-ext-9",
    "skill": "Words in context",
    "prompt": "Which sentence best supports a paragraph about small business grants?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on small business grants reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  },
  {
    "id": "sat-curated-ext-10",
    "skill": "Standard English Conventions",
    "prompt": "Which sentence best supports a paragraph about community gardens?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on community gardens reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  },
  {
    "id": "sat-curated-ext-11",
    "skill": "Transitions",
    "prompt": "Which sentence best supports a paragraph about library programs?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on library programs reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  },
  {
    "id": "sat-curated-ext-12",
    "skill": "Information and Ideas",
    "prompt": "Which sentence best supports a paragraph about transit policy?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on transit policy reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  },
  {
    "id": "sat-curated-ext-13",
    "skill": "Expression of Ideas",
    "prompt": "Which sentence best supports a paragraph about student journalism?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on student journalism reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  },
  {
    "id": "sat-curated-ext-14",
    "skill": "Central Ideas",
    "prompt": "Which sentence best supports a paragraph about water conservation?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on water conservation reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  },
  {
    "id": "sat-curated-ext-15",
    "skill": "Algebra",
    "prompt": "If 18x + 7 = 31, what is x?",
    "choices": [
      "16",
      "18",
      "19",
      "20"
    ],
    "answer": 0,
    "explanation": "Subtract 7 and divide by 18: x = 16."
  },
  {
    "id": "sat-curated-ext-16",
    "skill": "Data interpretation",
    "prompt": "Which sentence best supports a paragraph about science fairs?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on science fairs reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  },
  {
    "id": "sat-curated-ext-17",
    "skill": "Rhetoric",
    "prompt": "Which sentence best supports a paragraph about music education?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on music education reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  },
  {
    "id": "sat-curated-ext-18",
    "skill": "Linear equations",
    "prompt": "Which equation represents a line with slope 2 and y-intercept 5?",
    "choices": [
      "y = 2x + 5",
      "y = 5x + 2",
      "y = -2x + 5",
      "y = 2x - 5"
    ],
    "answer": 0,
    "explanation": "Slope-intercept form is y = mx + b."
  },
  {
    "id": "sat-curated-ext-19",
    "skill": "Words in context",
    "prompt": "Which sentence best supports a paragraph about small business grants?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on small business grants reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  },
  {
    "id": "sat-curated-ext-20",
    "skill": "Standard English Conventions",
    "prompt": "Which sentence best supports a paragraph about community gardens?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on community gardens reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  },
  {
    "id": "sat-curated-ext-21",
    "skill": "Transitions",
    "prompt": "Which sentence best supports a paragraph about library programs?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on library programs reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  },
  {
    "id": "sat-curated-ext-22",
    "skill": "Information and Ideas",
    "prompt": "Which sentence best supports a paragraph about transit policy?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on transit policy reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  },
  {
    "id": "sat-curated-ext-23",
    "skill": "Expression of Ideas",
    "prompt": "Which sentence best supports a paragraph about student journalism?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on student journalism reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  },
  {
    "id": "sat-curated-ext-24",
    "skill": "Central Ideas",
    "prompt": "Which sentence best supports a paragraph about water conservation?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on water conservation reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  },
  {
    "id": "sat-curated-ext-25",
    "skill": "Algebra",
    "prompt": "If 28x + 7 = 51, what is x?",
    "choices": [
      "26",
      "28",
      "29",
      "30"
    ],
    "answer": 0,
    "explanation": "Subtract 7 and divide by 28: x = 26."
  },
  {
    "id": "sat-curated-ext-26",
    "skill": "Data interpretation",
    "prompt": "Which sentence best supports a paragraph about science fairs?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on science fairs reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  },
  {
    "id": "sat-curated-ext-27",
    "skill": "Rhetoric",
    "prompt": "Which sentence best supports a paragraph about music education?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on music education reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  },
  {
    "id": "sat-curated-ext-28",
    "skill": "Linear equations",
    "prompt": "Which equation represents a line with slope 2 and y-intercept 5?",
    "choices": [
      "y = 2x + 5",
      "y = 5x + 2",
      "y = -2x + 5",
      "y = 2x - 5"
    ],
    "answer": 0,
    "explanation": "Slope-intercept form is y = mx + b."
  },
  {
    "id": "sat-curated-ext-29",
    "skill": "Words in context",
    "prompt": "Which sentence best supports a paragraph about small business grants?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on small business grants reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  },
  {
    "id": "sat-curated-ext-30",
    "skill": "Standard English Conventions",
    "prompt": "Which sentence best supports a paragraph about community gardens?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on community gardens reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  },
  {
    "id": "sat-curated-ext-31",
    "skill": "Transitions",
    "prompt": "Which sentence best supports a paragraph about library programs?",
    "choices": [
      "Many things exist in the world.",
      "A pilot program on library programs reported measurable gains for participants in the study described.",
      "People sometimes disagree.",
      "History is long."
    ],
    "answer": 1,
    "explanation": "A specific, relevant result directly supports the paragraph's claim."
  }
];
