"""Original Digital SAT Math practice corpus — Batch 2 (Packs 11–22 per domain).

Deeper topics beyond Batch 1: absolute value, multi-rate motion, mixtures,
quadratic systems, exponential growth/decay, residuals, circle equations,
right-triangle trig applications, volume/surface area, and related skills.
Aligned to College Board Digital SAT Math domains. Original AI practice —
not College Board exam items.
"""

from __future__ import annotations


SAT_MATH_BATCH2: list[dict[str, str]] = [
    {
        "title": 'SAT Math · Algebra Pack 11: Absolute Value Equations Deep Dive',
        "content": '# SAT Math · Algebra Pack 11: Absolute Value Equations Deep Dive\n**Domain:** Algebra\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nSolve $|2x-5|=9$.\n\n**A)** $x=7$ or $x=-2$\n**B)** $x=7$ only\n**C)** $x=2$ or $x=-7$\n**D)** $x=7$ or $x=2$\n\n**Solution:** $2x-5=9$ → $x=7$; $2x-5=-9$ → $x=-2$.\n**Answer:** A\n\n## Problem 2\nWhich values satisfy $|x+3|=|2x-1|$?\n\n**A)** $x=4$ and $x=-\\dfrac{2}{3}$\n**B)** $x=4$ only\n**C)** $x=-1$ and $x=2$\n**D)** $x=1$ and $x=-3$\n\n**Solution:** $x+3=2x-1$ → $x=4$; $x+3=-(2x-1)$ → $x=-\\dfrac{2}{3}$.\n**Answer:** A\n\n## Problem 3\nSolve $|4-x|=0$.\n\n**A)** $x=4$\n**B)** $x=-4$\n**C)** $x=0$\n**D)** No solution\n\n**Solution:** Absolute value is zero only when the inside is zero.\n**Answer:** A\n\n## Problem 4\nIf $|3x+6|=12$ and $x<0$, then $x=$\n\n**A)** $-6$\n**B)** $-2$\n**C)** $2$\n**D)** $-6$ or $2$\n\n**Solution:** $3x+6=-12$ → $x=-6$.\n**Answer:** A\n\n## Problem 5\nThe solution of $|x-2|=|x+5|$ is\n\n**A)** $x=-\\dfrac{3}{2}$\n**B)** $x=\\dfrac{3}{2}$\n**C)** all real $x$\n**D)** no solution\n\n**Solution:** Midpoint between $2$ and $-5$ is $-\\dfrac{3}{2}$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: If $|5x|=20$, enter the positive value of $x$.\n\n*Student-produced response — enter a number.*\n\n**Solution:** $5x=\\pm 20$; positive $x=4$.\n**Answer (SPR):** 4\n\n## Problem 7\nWhich equation has no real solution?\n\n**A)** $|x|+3=1$\n**B)** $|x-1|=0$\n**C)** $|2x|=4$\n**D)** $|x+7|=3$\n\n**Solution:** $|x|=-2$ is impossible.\n**Answer:** A\n\n## Problem 8\nSolve $|x|=2x-6$. The valid solution is\n\n**A)** $x=6$\n**B)** $x=2$\n**C)** $x=6$ and $x=2$\n**D)** no solution\n\n**Solution:** For $x\\ge 0$: $x=6$ checks. The $x<0$ case yields an extraneous root.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Algebra Pack 12: Absolute Value Inequalities',
        "content": '# SAT Math · Algebra Pack 12: Absolute Value Inequalities\n**Domain:** Algebra\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nSolve $|x-4|<3$.\n\n**A)** $1<x<7$\n**B)** $x<1$ or $x>7$\n**C)** $-3<x<3$\n**D)** $x>7$\n\n**Solution:** $-3<x-4<3$ → $1<x<7$.\n**Answer:** A\n\n## Problem 2\nThe solution of $|2x+1|\\ge 5$ is\n\n**A)** $x\\le -3$ or $x\\ge 2$\n**B)** $-3\\le x\\le 2$\n**C)** $x\\ge 2$ only\n**D)** $x\\le -3$ only\n\n**Solution:** $2x+1\\le -5$ or $2x+1\\ge 5$.\n**Answer:** A\n\n## Problem 3\nWhich number is NOT in the solution of $|x|\\le 4$?\n\n**A)** $5$\n**B)** $-4$\n**C)** $0$\n**D)** $4$\n\n**Solution:** $|5|=5>4$.\n**Answer:** A\n\n## Problem 4\nRewrite $|3x-6|<9$ without absolute value.\n\n**A)** $-1<x<5$\n**B)** $-3<x<3$\n**C)** $x<-1$ or $x>5$\n**D)** $0<x<5$\n\n**Solution:** $-9<3x-6<9$ → $-1<x<5$.\n**Answer:** A\n\n## Problem 5\nIf $|T-70|\\le 5$, then\n\n**A)** $65\\le T\\le 75$\n**B)** $70\\le T\\le 75$\n**C)** $T\\ge 75$\n**D)** $65<T<75$\n\n**Solution:** Within $5$ of $70$, inclusive.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: The smallest integer $x>10$ satisfying $|x-10|\\ge 8$ is\n\n*Student-produced response — enter a number.*\n\n**Solution:** $x\\ge 18$.\n**Answer (SPR):** 18\n\n## Problem 7\nOn a number line, $|x+2|>4$ is the exterior of\n\n**A)** the open interval $(-6,2)$\n**B)** $[-6,2]$\n**C)** $(-2,4)$\n**D)** $(-4,4)$\n\n**Solution:** $x<-6$ or $x>2$.\n**Answer:** A\n\n## Problem 8\nSolve $|5-2x|\\le 1$.\n\n**A)** $2\\le x\\le 3$\n**B)** $x\\le 2$ or $x\\ge 3$\n**C)** $-1\\le x\\le 1$\n**D)** $1\\le x\\le 2$\n\n**Solution:** $-1\\le 5-2x\\le 1$ → $2\\le x\\le 3$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Algebra Pack 13: Multi-Rate Motion Models',
        "content": '# SAT Math · Algebra Pack 13: Multi-Rate Motion Models\n**Domain:** Algebra\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nCar A at $40$ mph starts $30$ miles ahead of car B at $60$ mph (same direction). Hours until B catches A:\n\n**A)** $1.5$\n**B)** $2$\n**C)** $0.5$\n**D)** $3$\n\n**Solution:** Closing speed $20$ mph; $30/20=1.5$.\n**Answer:** A\n\n## Problem 2\nA cyclist rides $12$ miles at $8$ mph then $12$ miles at $12$ mph. Average speed:\n\n**A)** $9.6$ mph\n**B)** $10$ mph\n**C)** $11$ mph\n**D)** $8$ mph\n\n**Solution:** $24$ miles in $2.5$ hours → $9.6$ mph.\n**Answer:** A\n\n## Problem 3\nBoats leave opposite directions at $15$ and $25$ mph. Miles apart after $2$ hours:\n\n**A)** $80$\n**B)** $40$\n**C)** $50$\n**D)** $100$\n\n**Solution:** $(15+25)\\cdot 2=80$.\n**Answer:** A\n\n## Problem 4\nBoat speed in still water $10$ mph; current $2$ mph. Downstream rate:\n\n**A)** $12$ mph\n**B)** $8$ mph\n**C)** $10$ mph\n**D)** $20$ mph\n\n**Solution:** $10+2=12$.\n**Answer:** A\n\n## Problem 5\nUpstream at $8$ mph for $3$ hours covers\n\n**A)** $24$ miles\n**B)** $11$ miles\n**C)** $5$ miles\n**D)** $32$ miles\n\n**Solution:** $8\\times 3=24$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Runner goes $5$ km at $10$ km/h and returns $5$ km at $15$ km/h. Total time in minutes:\n\n*Student-produced response — enter a number.*\n\n**Solution:** $\\dfrac{1}{2}+\\dfrac{1}{3}=\\dfrac{5}{6}$ h $=50$ min.\n**Answer (SPR):** 50\n\n## Problem 7\nTrain A leaves noon at $50$ mph; train B leaves 1 pm at $70$ mph same direction. B catches A at\n\n**A)** $3:30$ pm\n**B)** $2:00$ pm\n**C)** $4:00$ pm\n**D)** $2:30$ pm\n\n**Solution:** $50$-mile lead; close at $20$ mph → $2.5$ h after 1 pm.\n**Answer:** A\n\n## Problem 8\nWalking $4$ mph against a $1$ mph wind, effective speed is\n\n**A)** $3$ mph\n**B)** $5$ mph\n**C)** $4$ mph\n**D)** $9$ mph\n\n**Solution:** $4-1=3$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Algebra Pack 14: Mixture and Concentration Models',
        "content": '# SAT Math · Algebra Pack 14: Mixture and Concentration Models\n**Domain:** Algebra\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nMix $4$ L of $10\\%$ saline with $6$ L of $30\\%$ saline. Resulting concentration:\n\n**A)** $22\\%$\n**B)** $20\\%$\n**C)** $25\\%$\n**D)** $40\\%$\n\n**Solution:** Salt $2.2$ L in $10$ L → $22\\%$.\n**Answer:** A\n\n## Problem 2\nLiters of $40\\%$ solution mixed with $5$ L of $10\\%$ to get $20\\%$:\n\n**A)** $2.5$\n**B)** $5$\n**C)** $10$\n**D)** $1$\n\n**Solution:** $0.4x+0.5=0.2(x+5)$ → $x=2.5$.\n**Answer:** A\n\n## Problem 3\nWater added to $8$ L of $25\\%$ acid to reach $10\\%$:\n\n**A)** $12$ L\n**B)** $8$ L\n**C)** $20$ L\n**D)** $5$ L\n\n**Solution:** $\\dfrac{2}{8+w}=0.1$ → $w=12$.\n**Answer:** A\n\n## Problem 4\nMix $3$ lb coffee at $12$/lb with $x$ lb at $8$/lb for average $10$/lb. Then $x=$\n\n**A)** $3$\n**B)** $2$\n**C)** $4$\n**D)** $6$\n\n**Solution:** $36+8x=10(3+x)$ → $x=3$.\n**Answer:** A\n\n## Problem 5\nIn $40$ kg of $30\\%$ copper alloy, copper mass is\n\n**A)** $12$ kg\n**B)** $30$ kg\n**C)** $10$ kg\n**D)** $28$ kg\n\n**Solution:** $0.3\\times 40=12$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Mix $x$ mL of $15\\%$ solution with $20$ mL of $45\\%$ to get $25\\%$. Find $x$.\n\n*Student-produced response — enter a number.*\n\n**Solution:** $0.15x+9=0.25(x+20)$ → $x=40$.\n**Answer (SPR):** 40\n\n## Problem 7\nEvaporate $50$ L of $8\\%$ brine down to $40$ L. New concentration:\n\n**A)** $10\\%$\n**B)** $8\\%$\n**C)** $12\\%$\n**D)** $6\\%$\n\n**Solution:** Salt $4$ L remains; $4/40=0.10$.\n**Answer:** A\n\n## Problem 8\nEquation for adding $x$ kg pure sugar to $10$ kg of $20\\%$ syrup to reach $40\\%$:\n\n**A)** $2+x=0.4(10+x)$\n**B)** $10+x=0.4(10+x)$\n**C)** $0.2+x=0.4$\n**D)** $x=0.4(10+x)$\n\n**Solution:** Sugar $2+x$; total $10+x$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Algebra Pack 15: Linear Systems with Parameters',
        "content": '# SAT Math · Algebra Pack 15: Linear Systems with Parameters\n**Domain:** Algebra\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nFor which $k$ do $x+y=5$ and $2x+2y=k$ have infinitely many solutions?\n\n**A)** $k=10$\n**B)** $k=5$\n**C)** $k=0$\n**D)** $k=2$\n\n**Solution:** Second must be twice the first: $k=10$.\n**Answer:** A\n\n## Problem 2\nThe system $y=3x+1$ and $y=3x+k$ has no solution when\n\n**A)** $k\\ne 1$\n**B)** $k=1$\n**C)** $k=3$ only\n**D)** never\n\n**Solution:** Parallel distinct lines when $k\\ne 1$.\n**Answer:** A\n\n## Problem 3\nIf $ax+2y=8$ and $(1,2)$ is a solution, then $a=$\n\n**A)** $4$\n**B)** $2$\n**C)** $3$\n**D)** $8$\n\n**Solution:** $a+4=8$ → $a=4$.\n**Answer:** A\n\n## Problem 4\nFor $x+y=7$ and $x+ky=10$ with unique solution $x=4$, what is $k$?\n\n**A)** $2$\n**B)** $3$\n**C)** $1$\n**D)** $4$\n\n**Solution:** $y=3$; $4+3k=10$ → $k=2$.\n**Answer:** A\n\n## Problem 5\nThe system $3x-y=4$ and $6x-2y=m$ has no solution when\n\n**A)** $m\\ne 8$\n**B)** $m=8$\n**C)** $m=4$\n**D)** $m=0$\n\n**Solution:** Left sides proportional; inconsistent unless $m=8$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: If $2x+y=11$ and $x-y=1$, enter $x$.\n\n*Student-produced response — enter a number.*\n\n**Solution:** Add: $3x=12$ → $x=4$.\n**Answer (SPR):** 4\n\n## Problem 7\nFor $y=mx+2$ and $y=-x+6$ to intersect at $x=2$, $m$ equals\n\n**A)** $1$\n**B)** $2$\n**C)** $-1$\n**D)** $0$\n\n**Solution:** $2m+2=4$ → $m=1$.\n**Answer:** A\n\n## Problem 8\nHow many solutions does $x-2y=3$ and $2x-4y=6$ have?\n\n**A)** Infinitely many\n**B)** None\n**C)** Exactly one\n**D)** Exactly two\n\n**Solution:** Second is double the first.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Algebra Pack 16: Piecewise Linear Models',
        "content": '# SAT Math · Algebra Pack 16: Piecewise Linear Models\n**Domain:** Algebra\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nLet $f(x)=2x+1$ for $x<3$ and $f(x)=x-2$ for $x\\ge 3$. Then $f(3)=$\n\n**A)** $1$\n**B)** $7$\n**C)** $3$\n**D)** $5$\n\n**Solution:** Use $x\\ge 3$: $3-2=1$.\n**Answer:** A\n\n## Problem 2\nFor the same $f$, $f(1)=$\n\n**A)** $3$\n**B)** $1$\n**C)** $-1$\n**D)** $2$\n\n**Solution:** $2(1)+1=3$.\n**Answer:** A\n\n## Problem 3\nTaxi: $3$ dollars first mile, $2$ dollars each additional mile. Cost for $5$ miles:\n\n**A)** $11$ dollars\n**B)** $10$ dollars\n**C)** $13$ dollars\n**D)** $8$ dollars\n\n**Solution:** $3+2\\cdot 4=11$.\n**Answer:** A\n\n## Problem 4\nParking: $4$ dollars for up to $2$ hours, then $3$ per extra hour. Cost for $5$ hours:\n\n**A)** $13$ dollars\n**B)** $15$ dollars\n**C)** $12$ dollars\n**D)** $19$ dollars\n\n**Solution:** $4+3\\cdot 3=13$.\n**Answer:** A\n\n## Problem 5\nIf $g(x)=|x-4|+1$, then $g(1)=$\n\n**A)** $4$\n**B)** $3$\n**C)** $5$\n**D)** $2$\n\n**Solution:** $|1-4|+1=4$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Let $h(x)=5-x$ for $x\\le 2$ and $h(x)=2x$ for $x>2$. Find $h(2)$.\n\n*Student-produced response — enter a number.*\n\n**Solution:** Use $x\\le 2$: $5-2=3$.\n**Answer (SPR):** 3\n\n## Problem 7\nFor $y=x$ when $x<0$ and $y=2x$ when $x\\ge 0$, at $x=0$\n\n**A)** $y=0$ and the pieces agree\n**B)** $y$ jumps\n**C)** $y=2$\n**D)** $y$ is undefined\n\n**Solution:** Both pieces give $0$.\n**Answer:** A\n\n## Problem 8\nCell plan: $20$ dollars up to $100$ texts, then $0.10$ per extra. Cost for $150$ texts:\n\n**A)** $25$ dollars\n**B)** $35$ dollars\n**C)** $20$ dollars\n**D)** $30$ dollars\n\n**Solution:** $20+0.10\\cdot 50=25$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Algebra Pack 17: Parallel Perpendicular and Intercepts',
        "content": '# SAT Math · Algebra Pack 17: Parallel Perpendicular and Intercepts\n**Domain:** Algebra\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nA line through $(2,-1)$ parallel to $y=\\dfrac{3}{5}x+4$ has equation\n\n**A)** $y+1=\\dfrac{3}{5}(x-2)$\n**B)** $y-1=\\dfrac{3}{5}(x+2)$\n**C)** $y+1=-\\dfrac{5}{3}(x-2)$\n**D)** $y=\\dfrac{5}{3}x$\n\n**Solution:** Same slope; point-slope form.\n**Answer:** A\n\n## Problem 2\nSlope of a line perpendicular to $3x-6y=12$ is\n\n**A)** $-2$\n**B)** $\\dfrac{1}{2}$\n**C)** $2$\n**D)** $-\\dfrac{1}{2}$\n\n**Solution:** $y=\\dfrac{1}{2}x-2$; perpendicular slope $-2$.\n**Answer:** A\n\n## Problem 3\nThe $x$-intercept of $4x-5y=20$ is\n\n**A)** $5$\n**B)** $4$\n**C)** $-4$\n**D)** $20$\n\n**Solution:** $y=0$ → $x=5$.\n**Answer:** A\n\n## Problem 4\nLine through $(0,6)$ and $(8,0)$ has slope\n\n**A)** $-\\dfrac{3}{4}$\n**B)** $-\\dfrac{4}{3}$\n**C)** $\\dfrac{3}{4}$\n**D)** $\\dfrac{4}{3}$\n\n**Solution:** $m=\\dfrac{0-6}{8-0}=-\\dfrac{3}{4}$.\n**Answer:** A\n\n## Problem 5\nWhich line is perpendicular to $y=-\\dfrac{2}{7}x+1$?\n\n**A)** $y=\\dfrac{7}{2}x-3$\n**B)** $y=-\\dfrac{2}{7}x$\n**C)** $y=\\dfrac{2}{7}x$\n**D)** $y=-\\dfrac{7}{2}x$\n\n**Solution:** Negative reciprocal is $\\dfrac{7}{2}$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: The $y$-intercept of $y=-5x+18$ is\n\n*Student-produced response — enter a number.*\n\n**Solution:** Constant term $18$.\n**Answer (SPR):** 18\n\n## Problem 7\nProduct of intercepts of $x+2y=6$ equals\n\n**A)** $18$\n**B)** $6$\n**C)** $12$\n**D)** $3$\n\n**Solution:** Intercepts $6$ and $3$; product $18$.\n**Answer:** A\n\n## Problem 8\nA vertical line through $(4,-2)$ has equation\n\n**A)** $x=4$\n**B)** $y=-2$\n**C)** $y=4$\n**D)** $x=-2$\n\n**Solution:** Vertical: $x=$ constant.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Algebra Pack 18: Interpreting Slopes in Context',
        "content": '# SAT Math · Algebra Pack 18: Interpreting Slopes in Context\n**Domain:** Algebra\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nIn $C=12n+45$ for cost of $n$ tickets, $12$ represents\n\n**A)** cost per additional ticket\n**B)** fixed fee only\n**C)** number of tickets\n**D)** total cost\n\n**Solution:** Slope is marginal cost.\n**Answer:** A\n\n## Problem 2\nIn $h=80-4t$ (meters, minutes), $-4$ means\n\n**A)** height decreases $4$ m each minute\n**B)** height increases $4$ m/min\n**C)** initial height\n**D)** time to ground\n\n**Solution:** Negative slope is decrease rate.\n**Answer:** A\n\n## Problem 3\nPay $P=250+15w$ with overtime hours $w$. Pay with $w=0$ is\n\n**A)** $250$\n**B)** $15$\n**C)** $265$\n**D)** $0$\n\n**Solution:** Intercept.\n**Answer:** A\n\n## Problem 4\nTank starts at $100$ gal and loses $2.5$ gal/min. Minutes until $40$ gal remain:\n\n**A)** $24$\n**B)** $20$\n**C)** $60$\n**D)** $16$\n\n**Solution:** $100-2.5t=40$ → $t=24$.\n**Answer:** A\n\n## Problem 5\nUnits of slope in $d=55t$ ($d$ miles, $t$ hours):\n\n**A)** miles per hour\n**B)** hours\n**C)** miles\n**D)** hours per mile\n\n**Solution:** Rate $=$ distance/time.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: In $y=-3x+21$, when $y=0$, the value of $x$ is\n\n*Student-produced response — enter a number.*\n\n**Solution:** $0=-3x+21$ → $x=7$.\n**Answer (SPR):** 7\n\n## Problem 7\nFrom $y=-\\dfrac{5}{2}x+20$, each unit increase in $x$ changes $y$ by\n\n**A)** $-2.5$\n**B)** $2.5$\n**C)** $20$\n**D)** $-5$\n\n**Solution:** Slope $-\\dfrac{5}{2}$.\n**Answer:** A\n\n## Problem 8\nBattery starts at $100\\%$ and drains $8\\%$ per hour. Percent after $3$ hours:\n\n**A)** $76\\%$\n**B)** $92\\%$\n**C)** $24\\%$\n**D)** $70\\%$\n\n**Solution:** $100-24=76$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Algebra Pack 19: Compound Inequalities and Constraints',
        "content": '# SAT Math · Algebra Pack 19: Compound Inequalities and Constraints\n**Domain:** Algebra\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nSolve $-4\\le 2x+2\\le 10$.\n\n**A)** $-3\\le x\\le 4$\n**B)** $-2\\le x\\le 5$\n**C)** $-4\\le x\\le 10$\n**D)** $0\\le x\\le 4$\n\n**Solution:** $-6\\le 2x\\le 8$ → $-3\\le x\\le 4$.\n**Answer:** A\n\n## Problem 2\nInteger solutions of $1<x\\le 4$ are\n\n**A)** $2,3,4$\n**B)** $1,2,3,4$\n**C)** $2,3$\n**D)** $1,2,3$\n\n**Solution:** Integers strictly above $1$ through $4$.\n**Answer:** A\n\n## Problem 3\nScore $s$ with $70\\le s\\le 100$ is equivalent to\n\n**A)** $|s-85|\\le 15$\n**B)** $|s-70|\\le 100$\n**C)** $s>70$\n**D)** $|s|\\le 100$\n\n**Solution:** Center $85$, radius $15$.\n**Answer:** A\n\n## Problem 4\nSolve $3-x>5$ or $x+1\\ge 8$.\n\n**A)** $x<-2$ or $x\\ge 7$\n**B)** $-2<x<7$\n**C)** $x>-2$\n**D)** $x\\le 7$\n\n**Solution:** $-x>2$ → $x<-2$; or $x\\ge 7$.\n**Answer:** A\n\n## Problem 5\nConstraint $4a+6b\\le 60$ with $b=4$. Max integer $a$ is\n\n**A)** $9$\n**B)** $6$\n**C)** $10$\n**D)** $15$\n\n**Solution:** $4a+24\\le 60$ → $a\\le 9$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: The largest integer $x$ satisfying $5x-3\\le 22$ is\n\n*Student-produced response — enter a number.*\n\n**Solution:** $5x\\le 25$ → $x\\le 5$.\n**Answer (SPR):** 5\n\n## Problem 7\nWhich best describes $x\\le -1$ or $x>3$?\n\n**A)** All reals except $-1<x\\le 3$\n**B)** Interior of $[-1,3]$\n**C)** Only $x>3$\n**D)** All real $x$\n\n**Solution:** Union of left ray and open right ray.\n**Answer:** A\n\n## Problem 8\nSolve $2\\le |x-1|<5$. The solution set is\n\n**A)** $x\\in(-4,-1]\\cup[3,6)$\n**B)** $x\\in(-4,6)$\n**C)** $|x-1|<2$\n**D)** $x\\ge 6$\n\n**Solution:** $|x-1|\\ge 2$ and $|x-1|<5$ give $(-4,-1]\\cup[3,6)$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Algebra Pack 20: Linear Word Problems Advanced',
        "content": '# SAT Math · Algebra Pack 20: Linear Word Problems Advanced\n**Domain:** Algebra\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nAdult tickets $15$, child $9$. Seven tickets cost $87$. Number of adult tickets:\n\n**A)** $4$\n**B)** $3$\n**C)** $5$\n**D)** $2$\n\n**Solution:** $a+c=7$, $15a+9c=87$ → $a=4$.\n**Answer:** A\n\n## Problem 2\nA number increased by $40\\%$ equals $84$. Original number:\n\n**A)** $60$\n**B)** $70$\n**C)** $50$\n**D)** $117.6$\n\n**Solution:** $1.4n=84$ → $n=60$.\n**Answer:** A\n\n## Problem 3\nThree consecutive integers sum to $72$. Middle integer:\n\n**A)** $24$\n**B)** $23$\n**C)** $25$\n**D)** $22$\n\n**Solution:** $3n=72$ → $n=24$.\n**Answer:** A\n\n## Problem 4\nPrinters at $30$ and $20$ pages/min together print $250$ pages in\n\n**A)** $5$ minutes\n**B)** $10$ minutes\n**C)** $8$ minutes\n**D)** $12.5$ minutes\n\n**Solution:** $250/50=5$.\n**Answer:** A\n\n## Problem 5\nInvest $x$ at $4\\%$ and $(8000-x)$ at $6\\%$ for interest $420$. Equation:\n\n**A)** $0.04x+0.06(8000-x)=420$\n**B)** $0.04x+0.06x=420$\n**C)** $4x+6(8000-x)=420$\n**D)** $x+8000=420$\n\n**Solution:** Interest sum equals $420$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Rectangle length is $5$ more than width. Perimeter $42$. Find the width.\n\n*Student-produced response — enter a number.*\n\n**Solution:** $2w+2(w+5)=42$ → $w=8$.\n**Answer (SPR):** 8\n\n## Problem 7\nTwo numbers sum to $50$ and differ by $12$. Larger number:\n\n**A)** $31$\n**B)** $19$\n**C)** $38$\n**D)** $25$\n\n**Solution:** $(50+12)/2=31$.\n**Answer:** A\n\n## Problem 8\nTank $120$ L; fill $8$ L/min and drain $3$ L/min both open. Minutes to fill from empty:\n\n**A)** $24$\n**B)** $15$\n**C)** $40$\n**D)** $20$\n\n**Solution:** Net $5$ L/min; $120/5=24$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Algebra Pack 21: Two-Variable Modeling Practice',
        "content": '# SAT Math · Algebra Pack 21: Two-Variable Modeling Practice\n**Domain:** Algebra\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nPoints $(0,4)$ and $(6,16)$ determine\n\n**A)** $y=2x+4$\n**B)** $y=x+4$\n**C)** $y=\\dfrac{1}{2}x+4$\n**D)** $y=2x-4$\n\n**Solution:** Slope $2$, intercept $4$.\n**Answer:** A\n\n## Problem 2\nIf $3x+4y=24$ and $x=0$, max $y$ is\n\n**A)** $6$\n**B)** $8$\n**C)** $24$\n**D)** $3$\n\n**Solution:** $4y=24$ → $y=6$.\n**Answer:** A\n\n## Problem 3\nSolve for $y$: $5x-2y=11$.\n\n**A)** $y=\\dfrac{5x-11}{2}$\n**B)** $y=\\dfrac{11-5x}{2}$\n**C)** $y=5x-11$\n**D)** $y=2x-\\dfrac{11}{5}$\n\n**Solution:** $-2y=11-5x$ → $y=\\dfrac{5x-11}{2}$.\n**Answer:** A\n\n## Problem 4\nModel with $y=18$ at $x=0$ decreasing by $3$ per unit $x$:\n\n**A)** $y=-3x+18$\n**B)** $y=3x+18$\n**C)** $y=-3x-18$\n**D)** $y=18x-3$\n\n**Solution:** Slope $-3$, intercept $18$.\n**Answer:** A\n\n## Problem 5\nWhich pair satisfies $x+2y=10$ and $3x-y=9$?\n\n**A)** $(4,3)$\n**B)** $(2,4)$\n**C)** $(3,2)$\n**D)** $(5,0)$\n\n**Solution:** $y=3x-9$; $x+2(3x-9)=10$ → $x=4$, $y=3$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: On $4x+y=20$, when $x=3$, what is $y$?\n\n*Student-produced response — enter a number.*\n\n**Solution:** $12+y=20$ → $y=8$.\n**Answer (SPR):** 8\n\n## Problem 7\nThe graph of $2x+5y=0$ must pass through\n\n**A)** $(0,0)$\n**B)** $(2,5)$\n**C)** $(5,-2)$\n**D)** $(1,1)$\n\n**Solution:** No constant term → origin.\n**Answer:** A\n\n## Problem 8\nRevenue $R=9q$, cost $C=3q+120$. Break-even $q$ is\n\n**A)** $20$\n**B)** $15$\n**C)** $40$\n**D)** $12$\n\n**Solution:** $9q=3q+120$ → $q=20$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Algebra Pack 22: Mixed Algebra Challenge',
        "content": '# SAT Math · Algebra Pack 22: Mixed Algebra Challenge\n**Domain:** Algebra\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nSolve $|3x+1|=10$. The positive solution is\n\n**A)** $3$\n**B)** $-\\dfrac{11}{3}$\n**C)** $\\dfrac{11}{3}$\n**D)** $10$\n\n**Solution:** $3x+1=10$ → $x=3$.\n**Answer:** A\n\n## Problem 2\nSystem $2x-y=5$ and $x+y=4$ has $x=$\n\n**A)** $3$\n**B)** $2$\n**C)** $1$\n**D)** $4$\n\n**Solution:** Add: $3x=9$ → $x=3$.\n**Answer:** A\n\n## Problem 3\nInequality $-2(x-4)>6$ simplifies to\n\n**A)** $x<1$\n**B)** $x>1$\n**C)** $x<7$\n**D)** $x>-1$\n\n**Solution:** $-2x+8>6$ → $x<1$.\n**Answer:** A\n\n## Problem 4\nLine through $(-3,5)$ with slope $-2$ has $y$-intercept\n\n**A)** $-1$\n**B)** $5$\n**C)** $11$\n**D)** $1$\n\n**Solution:** $5=-2(-3)+b$ → $b=-1$.\n**Answer:** A\n\n## Problem 5\nMix $2$ hours at $50$ mph and $3$ hours at $70$ mph. Total miles:\n\n**A)** $310$\n**B)** $250$\n**C)** $350$\n**D)** $240$\n\n**Solution:** $100+210=310$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Solve $7x-4=3x+16$. Enter $x$.\n\n*Student-produced response — enter a number.*\n\n**Solution:** $4x=20$ → $x=5$.\n**Answer (SPR):** 5\n\n## Problem 7\nIf $f(x)=mx+b$, $f(0)=9$, and $f(4)=1$, then $m=$\n\n**A)** $-2$\n**B)** $2$\n**C)** $-\\dfrac{1}{2}$\n**D)** $8$\n\n**Solution:** $m=(1-9)/4=-2$.\n**Answer:** A\n\n## Problem 8\n$|x-5|\\ge 2$ excludes which set of $x$?\n\n**A)** $(3,7)$\n**B)** $[3,7]$\n**C)** $(-\\infty,3]$\n**D)** $[7,\\infty)$\n\n**Solution:** Solution $x\\le 3$ or $x\\ge 7$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Advanced Math Pack 11: Quadratic Systems',
        "content": '# SAT Math · Advanced Math Pack 11: Quadratic Systems\n**Domain:** Advanced Math\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nSolve $y=x^2-4$ and $y=3x$. The $x$-values are\n\n**A)** $4$ and $-1$\n**B)** $2$ and $-2$\n**C)** $3$ only\n**D)** $0$ and $3$\n\n**Solution:** $x^2-3x-4=0$ → $(x-4)(x+1)=0$.\n**Answer:** A\n\n## Problem 2\nHow many real intersections do $y=x^2+2$ and $y=x$ have?\n\n**A)** $0$\n**B)** $1$\n**C)** $2$\n**D)** $3$\n\n**Solution:** Discriminant of $x^2-x+2$ is $1-8=-7$.\n**Answer:** A\n\n## Problem 3\nIf $x+y=6$ and $xy=8$, then $x^2+y^2=$\n\n**A)** $20$\n**B)** $36$\n**C)** $28$\n**D)** $16$\n\n**Solution:** $(x+y)^2-2xy=36-16=20$.\n**Answer:** A\n\n## Problem 4\nFor $y=x^2$ and $y=2x+3$, a positive solution for $x$ is\n\n**A)** $3$\n**B)** $1$\n**C)** $2$\n**D)** $-1$\n\n**Solution:** $x^2-2x-3=0$ → $(x-3)(x+1)=0$.\n**Answer:** A\n\n## Problem 5\nThe system $y=5-x^2$ and $y=1$ intersects at $x=$\n\n**A)** $\\pm 2$\n**B)** $\\pm 1$\n**C)** $\\pm 5$\n**D)** $0$ only\n\n**Solution:** $5-x^2=1$ → $x^2=4$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: For $y=x^2$ and $y=5x$, enter the positive solution for $x$.\n\n*Student-produced response — enter a number.*\n\n**Solution:** $x^2=5x$ → $x(x-5)=0$; positive $x=5$.\n**Answer (SPR):** 5\n\n## Problem 7\nIf $y=x^2-6x+10$ and $y=2$, the solutions for $x$ are\n\n**A)** $2$ and $4$\n**B)** $1$ and $5$\n**C)** $3$ only\n**D)** no real solution\n\n**Solution:** $x^2-6x+8=0$ → $(x-2)(x-4)=0$.\n**Answer:** A\n\n## Problem 8\nNumber of real solutions of $x^2+y^2=9$ and $y=x$:\n\n**A)** $2$\n**B)** $1$\n**C)** $0$\n**D)** $4$\n\n**Solution:** $2x^2=9$ → two real $x$ values.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Advanced Math Pack 12: Exponential Growth and Decay',
        "content": '# SAT Math · Advanced Math Pack 12: Exponential Growth and Decay\n**Domain:** Advanced Math\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nA culture starts at $500$ bacteria and doubles every $3$ hours. After $9$ hours:\n\n**A)** $4000$\n**B)** $2000$\n**C)** $4500$\n**D)** $1500$\n\n**Solution:** $3$ doublings: $500\\cdot 2^3=4000$.\n**Answer:** A\n\n## Problem 2\nWhich models $8\\%$ annual growth from principal $P$?\n\n**A)** $P(1.08)^t$\n**B)** $P(0.08)^t$\n**C)** $P+0.08t$\n**D)** $P(1.8)^t$\n\n**Solution:** Multiply by $1.08$ each year.\n**Answer:** A\n\n## Problem 3\nValue $V=1200(0.85)^t$ after $t$ years. Annual decay rate is\n\n**A)** $15\\%$\n**B)** $85\\%$\n**C)** $0.85\\%$\n**D)** $1200\\%$\n\n**Solution:** Base $0.85$ means $15\\%$ loss per year.\n**Answer:** A\n\n## Problem 4\nIf $3\\cdot 2^x=96$, then $x=$\n\n**A)** $5$\n**B)** $4$\n**C)** $6$\n**D)** $32$\n\n**Solution:** $2^x=32$ → $x=5$.\n**Answer:** A\n\n## Problem 5\nAn account of $2000$ grows at $5\\%$ per year compounded annually. After $2$ years:\n\n**A)** $2205$\n**B)** $2100$\n**C)** $2200$\n**D)** $2000\\cdot 1.1$\n\n**Solution:** $2000(1.05)^2=2000\\cdot 1.1025=2205$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Solve $4^x=64$. Enter $x$.\n\n*Student-produced response — enter a number.*\n\n**Solution:** $4^x=(4^{3/2})?$ $64=4^3$ → $x=3$. Or $4^x=(2^2)^x=2^{2x}=2^6$.\n**Answer (SPR):** 3\n\n## Problem 7\nWhich sequence is exponential with common ratio $3$?\n\n**A)** $2,6,18,54$\n**B)** $2,5,8,11$\n**C)** $3,6,12,18$\n**D)** $1,3,6,10$\n\n**Solution:** Each term times $3$.\n**Answer:** A\n\n## Problem 8\nIf half-life is $4$ years and mass starts at $80$ g, mass after $8$ years is\n\n**A)** $20$ g\n**B)** $40$ g\n**C)** $10$ g\n**D)** $60$ g\n\n**Solution:** Two half-lives: $80/4=20$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Advanced Math Pack 13: Completing the Square and Vertex',
        "content": '# SAT Math · Advanced Math Pack 13: Completing the Square and Vertex\n**Domain:** Advanced Math\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nRewrite $x^2+6x+2$ by completing the square.\n\n**A)** $(x+3)^2-7$\n**B)** $(x+3)^2+2$\n**C)** $(x+6)^2-34$\n**D)** $(x+3)^2-9$\n\n**Solution:** $x^2+6x+9-9+2=(x+3)^2-7$.\n**Answer:** A\n\n## Problem 2\nVertex of $y=x^2-8x+3$ is\n\n**A)** $(4,-13)$\n**B)** $(4,3)$\n**C)** $(-4,-13)$\n**D)** $(8,3)$\n\n**Solution:** $x=4$; $y=16-32+3=-13$.\n**Answer:** A\n\n## Problem 3\nMinimum of $f(x)=2(x-5)^2+7$ is\n\n**A)** $7$\n**B)** $5$\n**C)** $2$\n**D)** $0$\n\n**Solution:** Vertex $y$-coordinate since coefficient of square is positive.\n**Answer:** A\n\n## Problem 4\nComplete the square: $x^2-10x=$\n\n**A)** $(x-5)^2-25$\n**B)** $(x-10)^2$\n**C)** $(x-5)^2+25$\n**D)** $(x-5)^2$\n\n**Solution:** Add/subtract $25$.\n**Answer:** A\n\n## Problem 5\nAxis of symmetry of $y=-3x^2+12x-1$ is\n\n**A)** $x=2$\n**B)** $x=4$\n**C)** $x=-2$\n**D)** $x=12$\n\n**Solution:** $x=-b/(2a)=-12/(2(-3))=2$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: For $y=(x-7)^2+4$, the vertex $y$-coordinate is\n\n*Student-produced response — enter a number.*\n\n**Solution:** Vertex form $(h,k)=(7,4)$.\n**Answer (SPR):** 4\n\n## Problem 7\nWhich quadratic opens downward and has vertex $(1,-2)$?\n\n**A)** $y=-(x-1)^2-2$\n**B)** $y=(x-1)^2-2$\n**C)** $y=-(x+1)^2-2$\n**D)** $y=-(x-1)^2+2$\n\n**Solution:** Negative leading coefficient; vertex $(1,-2)$.\n**Answer:** A\n\n## Problem 8\n$x^2+4x+1=0$ after completing the square becomes\n\n**A)** $(x+2)^2=3$\n**B)** $(x+2)^2=1$\n**C)** $(x+4)^2=15$\n**D)** $(x+2)^2=-1$\n\n**Solution:** $(x+2)^2-4+1=0$ → $(x+2)^2=3$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Advanced Math Pack 14: Rational Expressions Deep Dive',
        "content": '# SAT Math · Advanced Math Pack 14: Rational Expressions Deep Dive\n**Domain:** Advanced Math\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nSimplify $\\dfrac{x^2-9}{x^2-x-6}$ for allowed $x$.\n\n**A)** $\\dfrac{x+3}{x+2}$\n**B)** $\\dfrac{x-3}{x-2}$\n**C)** $x+3$\n**D)** $\\dfrac{x-3}{x+2}$\n\n**Solution:** $(x-3)(x+3)/[(x-3)(x+2)]$.\n**Answer:** A\n\n## Problem 2\nFor what $x$ is $\\dfrac{x+1}{x^2-4}$ undefined?\n\n**A)** $x=\\pm 2$\n**B)** $x=-1$\n**C)** $x=0$\n**D)** $x=4$\n\n**Solution:** Denominator zero at $\\pm 2$.\n**Answer:** A\n\n## Problem 3\nSolve $\\dfrac{x}{x+2}=\\dfrac{3}{5}$ (exclude extraneous).\n\n**A)** $x=3$\n**B)** $x=-2$\n**C)** $x=5$\n**D)** $x=\\dfrac{6}{2}$\n\n**Solution:** $5x=3x+6$ → $2x=6$ → $x=3$.\n**Answer:** A\n\n## Problem 4\n$\\dfrac{2}{x}+\\dfrac{3}{x}=$\n\n**A)** $\\dfrac{5}{x}$\n**B)** $\\dfrac{5}{x^2}$\n**C)** $5x$\n**D)** $\\dfrac{6}{x}$\n\n**Solution:** Common denominator $x$.\n**Answer:** A\n\n## Problem 5\nWhich equals $\\dfrac{1}{x-1}-\\dfrac{1}{x+1}$?\n\n**A)** $\\dfrac{2}{x^2-1}$\n**B)** $\\dfrac{0}{x^2-1}$\n**C)** $\\dfrac{2x}{x^2-1}$\n**D)** $\\dfrac{1}{x^2-1}$\n\n**Solution:** $(x+1)-(x-1)$ over $(x-1)(x+1)$ = $2/(x^2-1)$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: If $\\dfrac{18}{x}=6$, enter $x$.\n\n*Student-produced response — enter a number.*\n\n**Solution:** $x=3$.\n**Answer (SPR):** 3\n\n## Problem 7\nSimplify $\\dfrac{6x^3y}{3xy^2}$ for $x,y\\ne 0$.\n\n**A)** $\\dfrac{2x^2}{y}$\n**B)** $2xy$\n**C)** $\\dfrac{2x}{y}$\n**D)** $2x^2y$\n\n**Solution:** $2x^{2}y^{-1}$.\n**Answer:** A\n\n## Problem 8\nSolve $\\dfrac{x+4}{x}=2$.\n\n**A)** $x=4$\n**B)** $x=-4$\n**C)** $x=2$\n**D)** $x=0$\n\n**Solution:** $x+4=2x$ → $x=4$ (and $x\\ne 0$).\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Advanced Math Pack 15: Polynomial Factoring Strategies',
        "content": '# SAT Math · Advanced Math Pack 15: Polynomial Factoring Strategies\n**Domain:** Advanced Math\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nFactor $x^2-5x-14$.\n\n**A)** $(x-7)(x+2)$\n**B)** $(x-7)(x-2)$\n**C)** $(x+7)(x-2)$\n**D)** $(x-14)(x+1)$\n\n**Solution:** Numbers summing to $-5$ multiplying to $-14$.\n**Answer:** A\n\n## Problem 2\nFactor $2x^2+7x+3$.\n\n**A)** $(2x+1)(x+3)$\n**B)** $(2x+3)(x+1)$\n**C)** $(2x-1)(x-3)$\n**D)** $(x+1)(x+3)$\n\n**Solution:** Check: $2x^2+6x+x+3$.\n**Answer:** A\n\n## Problem 3\nFactor completely $x^3-4x$.\n\n**A)** $x(x-2)(x+2)$\n**B)** $x(x^2-4)$ only\n**C)** $(x-2)(x+2)$\n**D)** $x^2(x-4)$\n\n**Solution:** $x(x^2-4)=x(x-2)(x+2)$.\n**Answer:** A\n\n## Problem 4\nWhich is a factor of $x^2+8x+16$?\n\n**A)** $x+4$\n**B)** $x-4$\n**C)** $x+8$\n**D)** $x+2$\n\n**Solution:** $(x+4)^2$.\n**Answer:** A\n\n## Problem 5\nFactor $9x^2-25$.\n\n**A)** $(3x-5)(3x+5)$\n**B)** $(9x-5)(x+5)$\n**C)** $(3x-25)(3x+1)$\n**D)** $(3x-5)^2$\n\n**Solution:** Difference of squares.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: One factor of $x^2-x-12$ is $(x-4)$. The other linear factor is $(x+k)$ with $k=$\n\n*Student-produced response — enter a number.*\n\n**Solution:** $(x-4)(x+3)$; $k=3$.\n**Answer (SPR):** 3\n\n## Problem 7\nWhich factorization of $6x^2+x-2$ is correct?\n\n**A)** $(2x-1)(3x+2)$\n**B)** $(6x-1)(x+2)$\n**C)** $(3x-1)(2x+2)$\n**D)** $(2x+1)(3x-2)$\n\n**Solution:** Expand: $6x^2+4x-3x-2=6x^2+x-2$.\n**Answer:** A\n\n## Problem 8\nFactor $x^3+8$.\n\n**A)** $(x+2)(x^2-2x+4)$\n**B)** $(x+2)^3$\n**C)** $(x-2)(x^2+2x+4)$\n**D)** $(x+8)(x^2-1)$\n\n**Solution:** Sum of cubes $a^3+b^3$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Advanced Math Pack 16: Radical and Rational Exponents',
        "content": '# SAT Math · Advanced Math Pack 16: Radical and Rational Exponents\n**Domain:** Advanced Math\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nSimplify $\\sqrt{72}$.\n\n**A)** $6\\sqrt{2}$\n**B)** $8\\sqrt{3}$\n**C)** $36\\sqrt{2}$\n**D)** $12\\sqrt{6}$\n\n**Solution:** $\\sqrt{36\\cdot 2}=6\\sqrt{2}$.\n**Answer:** A\n\n## Problem 2\n$x^{2/3}\\cdot x^{1/3}=$\n\n**A)** $x$\n**B)** $x^{1/3}$\n**C)** $x^{2/9}$\n**D)** $x^{3}$\n\n**Solution:** Add exponents: $1$.\n**Answer:** A\n\n## Problem 3\nSolve $\\sqrt{3x+4}=5$.\n\n**A)** $x=7$\n**B)** $x=3$\n**C)** $x=21$\n**D)** $x=1$\n\n**Solution:** $3x+4=25$ → $x=7$.\n**Answer:** A\n\n## Problem 4\nRewrite $\\sqrt[3]{x^6}$ for $x\\ge 0$ as\n\n**A)** $x^2$\n**B)** $x^3$\n**C)** $x^{1/2}$\n**D)** $x^6$\n\n**Solution:** $(x^6)^{1/3}=x^2$.\n**Answer:** A\n\n## Problem 5\nWhich equals $8^{2/3}$?\n\n**A)** $4$\n**B)** $16$\n**C)** $2$\n**D)** $64$\n\n**Solution:** $(8^{1/3})^2=2^2=4$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: If $\\sqrt{x-1}=6$, enter $x$.\n\n*Student-produced response — enter a number.*\n\n**Solution:** $x-1=36$ → $x=37$.\n**Answer (SPR):** 37\n\n## Problem 7\nSimplify $\\dfrac{\\sqrt{50}}{\\sqrt{2}}$.\n\n**A)** $5$\n**B)** $10$\n**C)** $25$\n**D)** $5\\sqrt{2}$\n\n**Solution:** $\\sqrt{25}=5$.\n**Answer:** A\n\n## Problem 8\nSolve $\\sqrt{2x+1}=x-1$ and discard extraneous roots. Valid solution:\n\n**A)** $x=4$\n**B)** $x=0$\n**C)** $x=1$\n**D)** $x=-1$\n\n**Solution:** $2x+1=(x-1)^2$ → $x^2-4x=0$ → $x(x-4)=0$; only $x=4$ checks ($x=0$ fails domain/check).\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Advanced Math Pack 17: Function Composition and Inverses',
        "content": '# SAT Math · Advanced Math Pack 17: Function Composition and Inverses\n**Domain:** Advanced Math\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nIf $f(x)=2x+3$ and $g(x)=x^2$, then $(f\\circ g)(2)=$\n\n**A)** $11$\n**B)** $10$\n**C)** $7$\n**D)** $16$\n\n**Solution:** $g(2)=4$; $f(4)=11$.\n**Answer:** A\n\n## Problem 2\nIf $f(x)=3x-1$, an inverse function is\n\n**A)** $f^{-1}(x)=\\dfrac{x+1}{3}$\n**B)** $f^{-1}(x)=3x+1$\n**C)** $f^{-1}(x)=\\dfrac{x-1}{3}$\n**D)** $f^{-1}(x)=1-3x$\n\n**Solution:** Swap: $x=3y-1$ → $y=(x+1)/3$.\n**Answer:** A\n\n## Problem 3\n$(g\\circ f)(x)$ for $f(x)=x+4$, $g(x)=5x$ equals\n\n**A)** $5x+20$\n**B)** $5x+4$\n**C)** $x+20$\n**D)** $5(x+4)+4$\n\n**Solution:** $g(f(x))=5(x+4)$.\n**Answer:** A\n\n## Problem 4\nIf $h(x)=x^3$, then $h^{-1}(8)=$\n\n**A)** $2$\n**B)** $4$\n**C)** $24$\n**D)** $512$\n\n**Solution:** Cube root of $8$ is $2$.\n**Answer:** A\n\n## Problem 5\nDomain of $(f\\circ g)$ if $g(x)=\\sqrt{x}$ and $f(x)=1/(x-3)$ requires\n\n**A)** $x\\ge 0$ and $\\sqrt{x}\\ne 3$\n**B)** $x>3$\n**C)** all real $x$\n**D)** $x\\ne 0$ only\n\n**Solution:** $g$ needs $x\\ge 0$; $f(g(x))$ needs $\\sqrt{x}\\ne 3$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: If $f(x)=x/2+5$, find $f^{-1}(9)$.\n\n*Student-produced response — enter a number.*\n\n**Solution:** $9=x/2+5$ → $x/2=4$ → $x=8$.\n**Answer (SPR):** 8\n\n## Problem 7\nWhich pair are inverses?\n\n**A)** $y=2x$ and $y=\\dfrac{x}{2}$\n**B)** $y=x+3$ and $y=x+3$\n**C)** $y=x^2$ and $y=x^3$\n**D)** $y=2x$ and $y=2/x$\n\n**Solution:** Composition yields identity.\n**Answer:** A\n\n## Problem 8\nIf $f(x)=4-x$, then $f(f(x))=$\n\n**A)** $x$\n**B)** $4-x$\n**C)** $8-x$\n**D)** $-x$\n\n**Solution:** $f(f(x))=4-(4-x)=x$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Advanced Math Pack 18: Absolute Value Meets Quadratics',
        "content": '# SAT Math · Advanced Math Pack 18: Absolute Value Meets Quadratics\n**Domain:** Advanced Math\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nSolve $|x^2-5|=4$. The possible values of $x^2$ are\n\n**A)** $9$ and $1$\n**B)** $4$ and $-4$\n**C)** $5$ only\n**D)** $9$ only\n\n**Solution:** $x^2-5=\\pm 4$ → $x^2=9$ or $1$.\n**Answer:** A\n\n## Problem 2\nHow many real solutions does $|x^2-1|=0$ have?\n\n**A)** $2$\n**B)** $1$\n**C)** $0$\n**D)** $4$\n\n**Solution:** $x^2=1$ → $x=\\pm 1$.\n**Answer:** A\n\n## Problem 3\nThe graph of $y=|x^2-4|$ meets the $x$-axis at\n\n**A)** $x=\\pm 2$\n**B)** $x=0$ only\n**C)** $x=4$\n**D)** never\n\n**Solution:** Zeros when $x^2-4=0$.\n**Answer:** A\n\n## Problem 4\nWhich $x$ satisfies $|2x-1|=x^2$?\n\n**A)** $x=1$\n**B)** $x=3$\n**C)** $x=-2$\n**D)** $x=5$\n\n**Solution:** Check $x=1$: $|1|=1$.\n**Answer:** A\n\n## Problem 5\nMinimum value of $y=|x^2+1|$ is\n\n**A)** $1$\n**B)** $0$\n**C)** $-1$\n**D)** $2$\n\n**Solution:** $x^2+1\\ge 1$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: If $|x^2-5|=4$ and $x>0$, enter the larger possible $x$.\n\n*Student-produced response — enter a number.*\n\n**Solution:** $x^2=9$ or $1$; larger positive $x=3$.\n**Answer (SPR):** 3\n\n## Problem 7\nWhich equation has solutions $x=0$ and $x=2$?\n\n**A)** $|x(x-2)|=0$\n**B)** $|x|+|x-2|=0$\n**C)** $x^2=2$\n**D)** $|x-1|=2$\n\n**Solution:** Product zero at those roots.\n**Answer:** A\n\n## Problem 8\nFor $y=|(x-1)(x-5)|$, the expression inside changes sign at\n\n**A)** $x=1$ and $x=5$\n**B)** $x=3$ only\n**C)** $x=0$\n**D)** $x=6$\n\n**Solution:** Roots of the quadratic factor.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Advanced Math Pack 19: Exponential Equations Beyond Bases',
        "content": '# SAT Math · Advanced Math Pack 19: Exponential Equations Beyond Bases\n**Domain:** Advanced Math\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nSolve $9^x=27$.\n\n**A)** $x=\\dfrac{3}{2}$\n**B)** $x=3$\n**C)** $x=\\dfrac{1}{2}$\n**D)** $x=2$\n\n**Solution:** $(3^2)^x=3^{2x}=3^3$ → $2x=3$.\n**Answer:** A\n\n## Problem 2\nIf $5^{x+1}=125$, then $x=$\n\n**A)** $2$\n**B)** $3$\n**C)** $4$\n**D)** $1$\n\n**Solution:** $5^{x+1}=5^3$ → $x=2$.\n**Answer:** A\n\n## Problem 3\nSolve $(\\dfrac{1}{2})^x=8$.\n\n**A)** $x=-3$\n**B)** $x=3$\n**C)** $x=-2$\n**D)** $x=4$\n\n**Solution:** $2^{-x}=2^3$ → $x=-3$.\n**Answer:** A\n\n## Problem 4\nWhich is equivalent to $4^{x+2}$?\n\n**A)** $16\\cdot 4^x$\n**B)** $4^x+2$\n**C)** $8\\cdot 4^x$\n**D)** $4^x\\cdot 2$\n\n**Solution:** $4^{x+2}=4^x\\cdot 4^2=16\\cdot 4^x$.\n**Answer:** A\n\n## Problem 5\nIf $2^{2x}=2^{x+3}$, then $x=$\n\n**A)** $3$\n**B)** $2$\n**C)** $0$\n**D)** $6$\n\n**Solution:** $2x=x+3$ → $x=3$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Solve $3^x=81$. Enter $x$.\n\n*Student-produced response — enter a number.*\n\n**Solution:** $81=3^4$ → $x=4$.\n**Answer (SPR):** 4\n\n## Problem 7\nPopulation $P=400\\cdot 3^{t/2}$. When $t=4$, $P=$\n\n**A)** $3600$\n**B)** $1200$\n**C)** $4800$\n**D)** $1600$\n\n**Solution:** $400\\cdot 3^2=3600$.\n**Answer:** A\n\n## Problem 8\nSolve $e^{2x}=e^{6}$ (same base). Then $x=$\n\n**A)** $3$\n**B)** $6$\n**C)** $2$\n**D)** $12$\n\n**Solution:** Exponents equal: $2x=6$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Advanced Math Pack 20: Nonlinear Inequalities',
        "content": '# SAT Math · Advanced Math Pack 20: Nonlinear Inequalities\n**Domain:** Advanced Math\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nSolve $x^2-9<0$.\n\n**A)** $-3<x<3$\n**B)** $x<-3$ or $x>3$\n**C)** $x\\le -3$\n**D)** $x>3$\n\n**Solution:** Product $(x-3)(x+3)<0$ between the roots.\n**Answer:** A\n\n## Problem 2\nSolution of $(x-1)(x-5)\\ge 0$ is\n\n**A)** $x\\le 1$ or $x\\ge 5$\n**B)** $1\\le x\\le 5$\n**C)** $x\\ge 1$\n**D)** $x\\le 5$\n\n**Solution:** Nonnegative outside the roots (inclusive).\n**Answer:** A\n\n## Problem 3\nWhich value satisfies $x^2>4$?\n\n**A)** $x=3$\n**B)** $x=1$\n**C)** $x=0$\n**D)** $x=-1$\n\n**Solution:** $|x|>2$; among choices only $3$.\n**Answer:** A\n\n## Problem 4\nSolve $\\dfrac{x-2}{x+1}>0$.\n\n**A)** $x<-1$ or $x>2$\n**B)** $-1<x<2$\n**C)** $x>2$ only\n**D)** $x<-1$ only\n\n**Solution:** Critical points $-1,2$; positive outside.\n**Answer:** A\n\n## Problem 5\nThe solution of $(x+2)^2(x-3)\\le 0$ is\n\n**A)** $x\\le 3$\n**B)** $x\\ge 3$\n**C)** $x=-2$ only\n**D)** all real $x$\n\n**Solution:** Square factor always $\\ge 0$; sign follows $(x-3)$ except zeros.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: The largest integer $x$ satisfying $x^2\\le 20$ is\n\n*Student-produced response — enter a number.*\n\n**Solution:** $\\sqrt{20}\\approx 4.47$ → $4$.\n**Answer (SPR):** 4\n\n## Problem 7\nSolve $2^x>8$.\n\n**A)** $x>3$\n**B)** $x<3$\n**C)** $x>8$\n**D)** $x>2$\n\n**Solution:** $2^x>2^3$ → $x>3$.\n**Answer:** A\n\n## Problem 8\nWhich $x$ is NOT a solution of $(x-4)(x+1)\\le 0$?\n\n**A)** $x=5$\n**B)** $x=0$\n**C)** $x=4$\n**D)** $x=-1$\n\n**Solution:** Solution $[-1,4]$; $5$ is outside.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Advanced Math Pack 21: Modeling with Quadratics and Exponentials',
        "content": "# SAT Math · Advanced Math Pack 21: Modeling with Quadratics and Exponentials\n**Domain:** Advanced Math\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nA ball's height $h=-16t^2+48t$ feet. Maximum height occurs at $t=$\n\n**A)** $1.5$ s\n**B)** $3$ s\n**C)** $16$ s\n**D)** $48$ s\n\n**Solution:** Vertex $t=-b/(2a)=48/32=1.5$.\n**Answer:** A\n\n## Problem 2\nMaximum height of that ball is\n\n**A)** $36$ ft\n**B)** $48$ ft\n**C)** $24$ ft\n**D)** $16$ ft\n\n**Solution:** $h(1.5)=-16(2.25)+48(1.5)=36$.\n**Answer:** A\n\n## Problem 3\nRevenue $R=x(50-x)$. Maximum revenue occurs at $x=$\n\n**A)** $25$\n**B)** $50$\n**C)** $0$\n**D)** $10$\n\n**Solution:** Vertex of $-x^2+50x$ at $x=25$.\n**Answer:** A\n\n## Problem 4\nModel $A=500(1.04)^t$ for $t$ years. $A$ after $0$ years is\n\n**A)** $500$\n**B)** $520$\n**C)** $1.04$\n**D)** $0$\n\n**Solution:** Any nonzero base to power $0$ yields factor $1$.\n**Answer:** A\n\n## Problem 5\nWhich better fits long-run growth that doubles each period?\n\n**A)** exponential\n**B)** linear\n**C)** constant\n**D)** quadratic with negative lead\n\n**Solution:** Constant ratio → exponential.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: For $h=-5t^2+20t$, height is $0$ again (after launch) at $t=$\n\n*Student-produced response — enter a number.*\n\n**Solution:** $-5t(t-4)=0$ → $t=4$.\n**Answer (SPR):** 4\n\n## Problem 7\nIf profit $P=-2x^2+40x-50$, profit is zero near the roots of\n\n**A)** $-2x^2+40x-50=0$\n**B)** $40x=50$\n**C)** $x=20$\n**D)** $P=40$\n\n**Solution:** Set $P=0$.\n**Answer:** A\n\n## Problem 8\nA quantity triples every $5$ years from $20$. After $10$ years:\n\n**A)** $180$\n**B)** $60$\n**C)** $200$\n**D)** $120$\n\n**Solution:** $20\\cdot 3^2=180$.\n**Answer:** A\n",
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Advanced Math Pack 22: Mixed Advanced Math Challenge',
        "content": '# SAT Math · Advanced Math Pack 22: Mixed Advanced Math Challenge\n**Domain:** Advanced Math\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nProduct of roots of $2x^2-5x+2=0$ is\n\n**A)** $1$\n**B)** $\\dfrac{5}{2}$\n**C)** $-1$\n**D)** $2$\n\n**Solution:** $c/a=1$.\n**Answer:** A\n\n## Problem 2\nIf $f(x)=3^x$, then $f(2)/f(0)=$\n\n**A)** $9$\n**B)** $3$\n**C)** $1$\n**D)** $6$\n\n**Solution:** $9/1=9$.\n**Answer:** A\n\n## Problem 3\nSimplify $\\dfrac{x^2-16}{x+4}$ for $x\\ne -4$.\n\n**A)** $x-4$\n**B)** $x+4$\n**C)** $x-16$\n**D)** $x^2-4$\n\n**Solution:** $(x-4)(x+4)/(x+4)$.\n**Answer:** A\n\n## Problem 4\nVertex of $y=-(x+3)^2+8$ is\n\n**A)** $(-3,8)$\n**B)** $(3,8)$\n**C)** $(-3,-8)$\n**D)** $(3,-8)$\n\n**Solution:** $(h,k)=(-3,8)$.\n**Answer:** A\n\n## Problem 5\nSolve $|x+2|=2x+5$. The valid solution is\n\n**A)** $x=-\\dfrac{7}{3}$\n**B)** $x=-3$\n**C)** $x=1$\n**D)** $x=0$\n\n**Solution:** Case $-(x+2)=2x+5$ yields $x=-\\dfrac{7}{3}$, which checks; $x=-3$ is extraneous.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Evaluate $(2^3)(5^2)$.\n\n*Student-produced response — enter a number.*\n\n**Solution:** $8\\cdot 25=200$.\n**Answer (SPR):** 200\n\n## Problem 7\nDiscriminant of $x^2-6x+10=0$ is\n\n**A)** $-4$\n**B)** $4$\n**C)** $16$\n**D)** $0$\n\n**Solution:** $36-40=-4$.\n**Answer:** A\n\n## Problem 8\nIf $y=4\\cdot \\left(\\dfrac{1}{2}\\right)^x$, as $x\\to\\infty$, $y$ approaches\n\n**A)** $0$\n**B)** $4$\n**C)** $\\infty$\n**D)** $\\dfrac{1}{2}$\n\n**Solution:** Exponential decay tends to $0$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Problem-Solving and Data Analysis Pack 11: Multi-Step Percentages',
        "content": '# SAT Math · Problem-Solving and Data Analysis Pack 11: Multi-Step Percentages\n**Domain:** Problem-Solving and Data Analysis\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nA jacket costs $80$. After a $25\\%$ discount and then $8\\%$ tax on the sale price, the total is\n\n**A)** $64.80$\n**B)** $70$\n**C)** $86.40$\n**D)** $60$\n\n**Solution:** $80\\times 0.75=60$; then $60\\times 1.08=64.80$.\n**Answer:** A\n\n## Problem 2\nA value rises $20\\%$ then falls $20\\%$. Final relative to original:\n\n**A)** $96\\%$\n**B)** $100\\%$\n**C)** $80\\%$\n**D)** $120\\%$\n\n**Solution:** $1.2\\times 0.8=0.96$.\n**Answer:** A\n\n## Problem 3\nWhat percent of $250$ is $40$?\n\n**A)** $16\\%$\n**B)** $40\\%$\n**C)** $6.25\\%$\n**D)** $25\\%$\n\n**Solution:** $40/250=0.16$.\n**Answer:** A\n\n## Problem 4\nAn item marked up $30\\%$ from $50$ dollars then discounted $10\\%$. Final price:\n\n**A)** $58.50$\n**B)** $65$\n**C)** $45$\n**D)** $60$\n\n**Solution:** $65\\times 0.9=58.5$.\n**Answer:** A\n\n## Problem 5\nPopulation $1200$ grows $5\\%$ then another $5\\%$. New population:\n\n**A)** $1323$\n**B)** $1300$\n**C)** $1260$\n**D)** $1440$\n\n**Solution:** $1200\\times 1.05^2=1323$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Fifteen percent of a number is $54$. The number is\n\n*Student-produced response — enter a number.*\n\n**Solution:** $0.15n=54$ → $n=360$.\n**Answer (SPR):** 360\n\n## Problem 7\nA store takes $15\\%$ off, then an extra $10\\%$ off the reduced price. Equivalent single discount approx:\n\n**A)** $23.5\\%$\n**B)** $25\\%$\n**C)** $15\\%$\n**D)** $10\\%$\n\n**Solution:** $1-0.85\\times 0.9=0.235$.\n**Answer:** A\n\n## Problem 8\nInterest: $600$ at $4\\%$ simple interest for $3$ years earns\n\n**A)** $72$\n**B)** $24$\n**C)** $72\\%$\n**D)** $600$\n\n**Solution:** $600\\times 0.04\\times 3=72$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Problem-Solving and Data Analysis Pack 12: Ratios Rates and Scaling',
        "content": '# SAT Math · Problem-Solving and Data Analysis Pack 12: Ratios Rates and Scaling\n**Domain:** Problem-Solving and Data Analysis\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nRatio of red to blue beads is $5:8$. If $40$ are red, blue count is\n\n**A)** $64$\n**B)** $25$\n**C)** $32$\n**D)** $80$\n\n**Solution:** $\\dfrac{5}{8}=\\dfrac{40}{b}$ → $b=64$.\n**Answer:** A\n\n## Problem 2\nMap scale $1$ cm : $25$ km. A $6.4$ cm segment represents\n\n**A)** $160$ km\n**B)** $25$ km\n**C)** $640$ km\n**D)** $100$ km\n\n**Solution:** $6.4\\times 25=160$.\n**Answer:** A\n\n## Problem 3\nIf $\\dfrac{a}{b}=\\dfrac{3}{7}$ and $a+b=40$, then $a=$\n\n**A)** $12$\n**B)** $28$\n**C)** $15$\n**D)** $21$\n\n**Solution:** $a=\\dfrac{3}{10}\\cdot 40=12$.\n**Answer:** A\n\n## Problem 4\nWork: $6$ machines finish a job in $10$ hours. Hours for $15$ machines (same job, constant rate):\n\n**A)** $4$\n**B)** $6$\n**C)** $25$\n**D)** $9$\n\n**Solution:** Machine-hours $60$; $60/15=4$.\n**Answer:** A\n\n## Problem 5\nA recipe for $8$ servings uses $3$ cups flour. Cups for $20$ servings:\n\n**A)** $7.5$\n**B)** $6$\n**C)** $5$\n**D)** $15$\n\n**Solution:** $\\dfrac{3}{8}\\cdot 20=7.5$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: If $4$ workers need $18$ days, days needed for $12$ workers (same total work):\n\n*Student-produced response — enter a number.*\n\n**Solution:** Worker-days $72$; $72/12=6$.\n**Answer (SPR):** 6\n\n## Problem 7\nSpeed ratio car:bike $=5:2$. If bike speed is $16$ mph, car speed is\n\n**A)** $40$ mph\n**B)** $32$ mph\n**C)** $20$ mph\n**D)** $10$ mph\n\n**Solution:** $\\dfrac{5}{2}\\cdot 16=40$.\n**Answer:** A\n\n## Problem 8\nScale model is $1:75$. Real length $15$ m corresponds to model length\n\n**A)** $0.2$ m\n**B)** $1.125$ m\n**C)** $75$ m\n**D)** $0.02$ m\n\n**Solution:** $15/75=0.2$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Problem-Solving and Data Analysis Pack 13: Unit Rates and Dimensional Analysis',
        "content": '# SAT Math · Problem-Solving and Data Analysis Pack 13: Unit Rates and Dimensional Analysis\n**Domain:** Problem-Solving and Data Analysis\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nA printer makes $96$ pages in $8$ minutes. Pages per minute:\n\n**A)** $12$\n**B)** $8$\n**C)** $96$\n**D)** $16$\n\n**Solution:** $96/8=12$.\n**Answer:** A\n\n## Problem 2\nConvert $72$ km/h to meters per minute.\n\n**A)** $1200$\n**B)** $72000$\n**C)** $1.2$\n**D)** $4320$\n\n**Solution:** $72\\times 1000/60=1200$.\n**Answer:** A\n\n## Problem 3\nUnit price: $9$ dollars for $1.5$ lb. Cost per pound:\n\n**A)** $6$ dollars\n**B)** $7.5$ dollars\n**C)** $13.5$ dollars\n**D)** $4.5$ dollars\n\n**Solution:** $9/1.5=6$.\n**Answer:** A\n\n## Problem 4\nDensity $2.5$ g/cm$^3$. Volume of $40$ g is\n\n**A)** $16$ cm$^3$\n**B)** $100$ cm$^3$\n**C)** $0.0625$ cm$^3$\n**D)** $42.5$ cm$^3$\n\n**Solution:** $V=m/d=40/2.5=16$.\n**Answer:** A\n\n## Problem 5\nFuel economy $28$ mpg. Gallons for $350$ miles:\n\n**A)** $12.5$\n**B)** $10$\n**C)** $28$\n**D)** $14$\n\n**Solution:** $350/28=12.5$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: At $45$ words per minute, minutes to type $540$ words:\n\n*Student-produced response — enter a number.*\n\n**Solution:** $540/45=12$.\n**Answer (SPR):** 12\n\n## Problem 7\nWhich rate is greatest?\n\n**A)** $90$ miles in $1.25$ hours\n**B)** $60$ mph\n**C)** $2$ miles in $3$ minutes\n**D)** $100$ miles in $2$ hours\n\n**Solution:** $90/1.25=72$ mph; $60$ mph; $2$ mi / $3$ min $=40$ mph; $100/2=50$ mph. Greatest is $72$.\n**Answer:** A\n\n## Problem 8\n$3$ inches of rain in $2$ hours averages\n\n**A)** $1.5$ in/h\n**B)** $6$ in/h\n**C)** $3$ in/h\n**D)** $0.67$ in/h\n\n**Solution:** $3/2=1.5$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Problem-Solving and Data Analysis Pack 14: Scatterplots and Residuals',
        "content": '# SAT Math · Problem-Solving and Data Analysis Pack 14: Scatterplots and Residuals\n**Domain:** Problem-Solving and Data Analysis\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nA residual is defined as\n\n**A)** actual $y$ minus predicted $y$\n**B)** predicted minus actual\n**C)** slope of LSRL\n**D)** correlation $r$\n\n**Solution:** Residual $=$ observed $-$ predicted.\n**Answer:** A\n\n## Problem 2\nIf predicted $\\hat{y}=12$ and residual $= -3$, actual $y$ is\n\n**A)** $9$\n**B)** $15$\n**C)** $12$\n**D)** $-3$\n\n**Solution:** $y=\\hat{y}+e=9$.\n**Answer:** A\n\n## Problem 3\nA residual plot with no pattern and random scatter about $0$ suggests\n\n**A)** linear model is reasonable\n**B)** model is exponential\n**C)** correlation is zero\n**D)** outliers only\n\n**Solution:** Random residuals support linearity.\n**Answer:** A\n\n## Problem 4\nLSRL $\\hat{y}=2.5x+10$. Residual at $x=4$ if actual $y=18$ is\n\n**A)** $-2$\n**B)** $2$\n**C)** $20$\n**D)** $8$\n\n**Solution:** $\\hat{y}=20$; residual $18-20=-2$.\n**Answer:** A\n\n## Problem 5\nA positive residual means the point lies\n\n**A)** above the regression line\n**B)** below the line\n**C)** on the line\n**D)** left of the $y$-axis\n\n**Solution:** Actual exceeds prediction.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: For $\\hat{y}=5x-1$ and actual $y=24$ at $x=5$, the residual is\n\n*Student-produced response — enter a number.*\n\n**Solution:** $\\hat{y}=24$; residual $0$.\n**Answer (SPR):** 0\n\n## Problem 7\nIf residuals trend curved (U-shape), one should consider\n\n**A)** a nonlinear model\n**B)** forcing $r=1$\n**C)** deleting all data\n**D)** using only mean\n\n**Solution:** Pattern suggests misspecification.\n**Answer:** A\n\n## Problem 8\nCorrelation $r$ close to $-1$ means\n\n**A)** strong negative linear association\n**B)** no association\n**C)** strong positive association\n**D)** residuals all positive\n\n**Solution:** Near $-1$ is strong negative linear.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Problem-Solving and Data Analysis Pack 15: Two-Way Tables and Relative Frequency',
        "content": '# SAT Math · Problem-Solving and Data Analysis Pack 15: Two-Way Tables and Relative Frequency\n**Domain:** Problem-Solving and Data Analysis\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nTable: Yes/No vs Group A/B. A-Yes $20$, A-No $30$, B-Yes $10$, B-No $40$. $P($Yes$)=$\n\n**A)** $0.3$\n**B)** $0.2$\n**C)** $0.5$\n**D)** $0.6$\n\n**Solution:** Yes total $30$ of $100$.\n**Answer:** A\n\n## Problem 2\nUsing that table, $P($A$|$Yes$)=$\n\n**A)** $\\dfrac{2}{3}$\n**B)** $\\dfrac{1}{2}$\n**C)** $\\dfrac{1}{5}$\n**D)** $\\dfrac{3}{5}$\n\n**Solution:** $20/30=2/3$.\n**Answer:** A\n\n## Problem 3\nRelative frequency of B-No among all is\n\n**A)** $0.4$\n**B)** $0.5$\n**C)** $0.25$\n**D)** $0.8$\n\n**Solution:** $40/100=0.4$.\n**Answer:** A\n\n## Problem 4\nRow totals A and B are\n\n**A)** $50$ and $50$\n**B)** $30$ and $70$\n**C)** $20$ and $40$\n**D)** $60$ and $40$\n\n**Solution:** A: $50$; B: $50$.\n**Answer:** A\n\n## Problem 5\nIf another survey shows Yes rates $40\\%$ in A and $25\\%$ in B with equal group sizes $200$ each, expected Yes count is\n\n**A)** $130$\n**B)** $80$\n**C)** $50$\n**D)** $200$\n\n**Solution:** $0.4\\cdot 200+0.25\\cdot 200=130$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: In a $2\\times 2$ table with entries $12,18,8,22$, the grand total is\n\n*Student-produced response — enter a number.*\n\n**Solution:** $12+18+8+22=60$.\n**Answer (SPR):** 60\n\n## Problem 7\nJoint relative frequency of a cell with count $15$ in a table totaling $60$ is\n\n**A)** $0.25$\n**B)** $15$\n**C)** $0.15$\n**D)** $4$\n\n**Solution:** $15/60=0.25$.\n**Answer:** A\n\n## Problem 8\nMarginal relative frequency for a column totaling $24$ of $80$ is\n\n**A)** $0.3$\n**B)** $24$\n**C)** $0.24$\n**D)** $3.33$\n\n**Solution:** $24/80=0.3$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Problem-Solving and Data Analysis Pack 16: Center Spread and Outliers',
        "content": '# SAT Math · Problem-Solving and Data Analysis Pack 16: Center Spread and Outliers\n**Domain:** Problem-Solving and Data Analysis\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nData: $2,3,3,5,17$. Mean is\n\n**A)** $6$\n**B)** $3$\n**C)** $5$\n**D)** $17$\n\n**Solution:** Sum $30$; mean $6$.\n**Answer:** A\n\n## Problem 2\nFor the same data, median is\n\n**A)** $3$\n**B)** $2$\n**C)** $5$\n**D)** $6$\n\n**Solution:** Middle value $3$.\n**Answer:** A\n\n## Problem 3\nWhich measure is most affected by the outlier $17$?\n\n**A)** mean\n**B)** median\n**C)** mode\n**D)** midrange of middle three only\n\n**Solution:** Mean pulls toward outliers.\n**Answer:** A\n\n## Problem 4\nIQR for $1,2,4,6,7,9,10$ (n=7) uses Q1=$2$, Q3=$9$. IQR=\n\n**A)** $7$\n**B)** $9$\n**C)** $4$\n**D)** $8$\n\n**Solution:** $9-2=7$.\n**Answer:** A\n\n## Problem 5\nA point is often flagged as outlier if it is more than $1.5\\times$IQR beyond quartiles. With Q1=$10$, Q3=$22$, upper fence is\n\n**A)** $40$\n**B)** $34$\n**C)** $22$\n**D)** $18$\n\n**Solution:** IQR=$12$; fence $22+18=40$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: The range of $4,9,11,20$ is\n\n*Student-produced response — enter a number.*\n\n**Solution:** $20-4=16$.\n**Answer (SPR):** 16\n\n## Problem 7\nStandard deviation increases when\n\n**A)** data become more spread out\n**B)** all values equal the mean\n**C)** every observation is replaced by the mean\n**D)** only the median is recomputed\n\n**Solution:** SD measures spread about the mean; greater spread raises SD.\n**Answer:** A\n\n## Problem 8\nFor a symmetric unimodal distribution, mean and median are\n\n**A)** approximately equal\n**B)** always far apart\n**C)** undefined\n**D)** equal to the range\n\n**Solution:** Symmetry centers them together.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Problem-Solving and Data Analysis Pack 17: Probability with Overlap',
        "content": '# SAT Math · Problem-Solving and Data Analysis Pack 17: Probability with Overlap\n**Domain:** Problem-Solving and Data Analysis\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nIf $P(A)=0.4$, $P(B)=0.5$, $P(A\\cap B)=0.2$, then $P(A\\cup B)=$\n\n**A)** $0.7$\n**B)** $0.9$\n**C)** $0.2$\n**D)** $0.1$\n\n**Solution:** $0.4+0.5-0.2=0.7$.\n**Answer:** A\n\n## Problem 2\nEvents with $P(A\\cap B)=P(A)P(B)$ are\n\n**A)** independent\n**B)** mutually exclusive\n**C)** certain\n**D)** impossible\n\n**Solution:** Definition of independence.\n**Answer:** A\n\n## Problem 3\nIf $A$ and $B$ are mutually exclusive and $P(A)=0.3$, $P(B)=0.2$, then $P(A\\cup B)=$\n\n**A)** $0.5$\n**B)** $0.06$\n**C)** $0.1$\n**D)** $1$\n\n**Solution:** Disjoint → add probabilities.\n**Answer:** A\n\n## Problem 4\n$P(A|B)=\\dfrac{P(A\\cap B)}{P(B)}$. If $P(A\\cap B)=0.15$ and $P(B)=0.5$, then $P(A|B)=$\n\n**A)** $0.3$\n**B)** $0.15$\n**C)** $0.65$\n**D)** $0.5$\n\n**Solution:** $0.15/0.5=0.3$.\n**Answer:** A\n\n## Problem 5\nA fair six-sided die: $P($even or $>4)=$\n\n**A)** $\\dfrac{2}{3}$\n**B)** $\\dfrac{1}{2}$\n**C)** $\\dfrac{1}{3}$\n**D)** $1$\n\n**Solution:** Even $\\{2,4,6\\}$, $>4$ $\\{5,6\\}$; union $\\{2,4,5,6\\}$ → $4/6$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: From $5$ red and $3$ blue marbles, $P($red$)$ as a reduced fraction $a/b$ has $a+b=$ (enter that sum)\n\n*Student-produced response — enter a number.*\n\n**Solution:** $5/8$; $5+8=13$.\n**Answer (SPR):** 13\n\n## Problem 7\nComplement rule: $P(A^c)=$\n\n**A)** $1-P(A)$\n**B)** $P(A)$\n**C)** $1+P(A)$\n**D)** $P(A)/2$\n\n**Solution:** Standard identity.\n**Answer:** A\n\n## Problem 8\nTwo independent events each with probability $0.5$. $P($both$)=$\n\n**A)** $0.25$\n**B)** $1$\n**C)** $0.5$\n**D)** $0$\n\n**Solution:** $0.5\\times 0.5=0.25$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Problem-Solving and Data Analysis Pack 18: Sampling Bias and Design',
        "content": '# SAT Math · Problem-Solving and Data Analysis Pack 18: Sampling Bias and Design\n**Domain:** Problem-Solving and Data Analysis\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nCalling only landline phones to estimate smartphone use likely causes\n\n**A)** undercoverage bias\n**B)** perfect randomness\n**C)** zero margin of error\n**D)** guaranteed accuracy\n\n**Solution:** Misses cell-only households.\n**Answer:** A\n\n## Problem 2\nA voluntary online poll mainly suffers from\n\n**A)** voluntary response bias\n**B)** perfect SRS\n**C)** no nonresponse\n**D)** forced randomization\n\n**Solution:** Self-selected respondents differ systematically.\n**Answer:** A\n\n## Problem 3\nA simple random sample means\n\n**A)** every subset of size $n$ is equally likely\n**B)** the researcher picks favorites\n**C)** largest cities only\n**D)** first $n$ volunteers\n\n**Solution:** SRS definition.\n**Answer:** A\n\n## Problem 4\nIncreasing sample size generally\n\n**A)** decreases margin of error\n**B)** increases bias automatically\n**C)** eliminates all bias\n**D)** guarantees causation\n\n**Solution:** Precision improves; bias is separate.\n**Answer:** A\n\n## Problem 5\nObservational study vs experiment: experiments\n\n**A)** impose treatments\n**B)** never use randomization\n**C)** cannot have control groups\n**D)** only survey opinions\n\n**Solution:** Treatment assignment is key.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: A poll of $100$ students finds $64$ favor a schedule change. The sample proportion (percent) is\n\n*Student-produced response — enter a number.*\n\n**Solution:** $64\\%$.\n**Answer (SPR):** 64\n\n## Problem 7\nConvenience sampling near a gym to estimate city exercise rates is problematic because\n\n**A)** the sample is not representative\n**B)** the gym is too random\n**C)** n is always infinite\n**D)** means cannot be computed\n\n**Solution:** Location skews toward exercisers.\n**Answer:** A\n\n## Problem 8\nBlinding in experiments helps reduce\n\n**A)** placebo and expectancy effects\n**B)** sample size\n**C)** randomization need\n**D)** the need for a control\n\n**Solution:** Limits biased responses/measurements.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Problem-Solving and Data Analysis Pack 19: Interpreting Linear Regression Slope',
        "content": "# SAT Math · Problem-Solving and Data Analysis Pack 19: Interpreting Linear Regression Slope\n**Domain:** Problem-Solving and Data Analysis\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nLSRL $\\hat{y}=3.2x+15$ relating hours studied $x$ to score $y$. Slope means\n\n**A)** score rises about $3.2$ per additional study hour\n**B)** score is always $15$\n**C)** hours rise $3.2$ per score point\n**D)** $r=3.2$\n\n**Solution:** Slope is change in predicted $y$ per unit $x$.\n**Answer:** A\n\n## Problem 2\nIntercept $15$ is best interpreted as\n\n**A)** predicted score when study hours are $0$\n**B)** maximum score\n**C)** minimum hours\n**D)** correlation\n\n**Solution:** Value at $x=0$ (context permitting).\n**Answer:** A\n\n## Problem 3\nIf $r=0.85$ for a linear model,\n\n**A)** strong positive linear association\n**B)** strong negative\n**C)** no association\n**D)** perfect fit only\n\n**Solution:** Close to $1$ and positive.\n**Answer:** A\n\n## Problem 4\n$\\hat{y}=-1.5x+40$ for temperature drop context. Each unit increase in $x$ changes predicted $y$ by\n\n**A)** $-1.5$\n**B)** $1.5$\n**C)** $40$\n**D)** $-40$\n\n**Solution:** Slope value.\n**Answer:** A\n\n## Problem 5\nExtrapolation means\n\n**A)** predicting outside the data's $x$-range\n**B)** computing residuals only\n**C)** using median instead of mean\n**D)** sorting the scatterplot\n\n**Solution:** Risky prediction beyond observed domain.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: For $\\hat{y}=4x+7$, predicted $y$ when $x=6$ is\n\n*Student-produced response — enter a number.*\n\n**Solution:** $24+7=31$.\n**Answer (SPR):** 31\n\n## Problem 7\nA slope near $0$ with $r$ near $0$ suggests\n\n**A)** little linear association\n**B)** strong causality\n**C)** perfect line\n**D)** deterministic relation\n\n**Solution:** Flat weak linear signal.\n**Answer:** A\n\n## Problem 8\nChanging units of $x$ from hours to minutes (divide $x$ by $60$) will\n\n**A)** multiply the slope by $60$\n**B)** leave slope unchanged\n**C)** multiply slope by $1/60$\n**D)** set slope to $0$\n\n**Solution:** Per-minute change is $60$ times per-hour change.\n**Answer:** A\n",
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Problem-Solving and Data Analysis Pack 20: Percent Change Chains',
        "content": '# SAT Math · Problem-Solving and Data Analysis Pack 20: Percent Change Chains\n**Domain:** Problem-Solving and Data Analysis\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nStart at $200$. Increase $10\\%$, then decrease $10\\%$. Result:\n\n**A)** $198$\n**B)** $200$\n**C)** $180$\n**D)** $220$\n\n**Solution:** $220\\times 0.9=198$.\n**Answer:** A\n\n## Problem 2\nA price falls from $80$ to $60$. Percent decrease:\n\n**A)** $25\\%$\n**B)** $20\\%$\n**C)** $33\\%$\n**D)** $75\\%$\n\n**Solution:** $20/80=0.25$.\n**Answer:** A\n\n## Problem 3\nSuccessive growth factors $1.05$ and $1.10$ compound to\n\n**A)** $1.155$\n**B)** $1.15$\n**C)** $2.15$\n**D)** $0.15$\n\n**Solution:** $1.05\\times 1.10=1.155$.\n**Answer:** A\n\n## Problem 4\nTo reverse a $20\\%$ increase, multiply by\n\n**A)** $\\dfrac{5}{6}$\n**B)** $0.8$\n**C)** $1.2$\n**D)** $0.2$\n\n**Solution:** Divide by $1.2$ = multiply by $5/6$.\n**Answer:** A\n\n## Problem 5\nSalary $50{,}000$ rises $4\\%$ then $3\\%$. Final salary:\n\n**A)** $53{,}560$\n**B)** $53{,}500$\n**C)** $57{,}000$\n**D)** $52{,}000$\n\n**Solution:** $50000\\times 1.04\\times 1.03=53560$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: A quantity doubles then increases by $50\\%$. Overall growth factor as a decimal times original (enter the factor like 3):\n\n*Student-produced response — enter a number.*\n\n**Solution:** $2\\times 1.5=3$.\n**Answer (SPR):** 3\n\n## Problem 7\nMarkdown from $120$ to $90$ then another $10\\%$ off. Final price:\n\n**A)** $81$\n**B)** $90$\n**C)** $108$\n**D)** $70$\n\n**Solution:** $90\\times 0.9=81$.\n**Answer:** A\n\n## Problem 8\nIf a stock multiplies by $0.7$ then by $1.5$, net factor is\n\n**A)** $1.05$\n**B)** $2.2$\n**C)** $0.7$\n**D)** $0.45$\n\n**Solution:** $0.7\\times 1.5=1.05$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Problem-Solving and Data Analysis Pack 21: Comparing Data Displays',
        "content": '# SAT Math · Problem-Solving and Data Analysis Pack 21: Comparing Data Displays\n**Domain:** Problem-Solving and Data Analysis\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nA histogram with a long right tail is described as\n\n**A)** right-skewed\n**B)** left-skewed\n**C)** symmetric\n**D)** uniform only\n\n**Solution:** Tail to the right → right skew.\n**Answer:** A\n\n## Problem 2\nBoxplots are especially useful for comparing\n\n**A)** spread and center across groups\n**B)** exact correlation $r$\n**C)** individual residual values\n**D)** exponential models only\n\n**Solution:** Side-by-side five-number summaries.\n**Answer:** A\n\n## Problem 3\nIn a pie chart, a $90^\\circ$ sector represents\n\n**A)** $25\\%$ of the whole\n**B)** $90\\%$\n**C)** $50\\%$\n**D)** $10\\%$\n\n**Solution:** $90/360=0.25$.\n**Answer:** A\n\n## Problem 4\nA bar graph differs from a histogram mainly because\n\n**A)** categories need not be numeric bins\n**B)** bars must touch\n**C)** it cannot show counts\n**D)** it requires residuals\n\n**Solution:** Bars for categorical vs continuous bins.\n**Answer:** A\n\n## Problem 5\nIf two boxplots share the same median but one has much larger IQR,\n\n**A)** that group is more spread in the middle $50\\%$\n**B)** means must differ\n**C)** no outliers exist\n**D)** samples are identical\n\n**Solution:** IQR captures central spread.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: A circle graph shows sections $40\\%$, $35\\%$, and the rest. The remaining percent is\n\n*Student-produced response — enter a number.*\n\n**Solution:** $100-75=25$.\n**Answer (SPR):** 25\n\n## Problem 7\nA stem-and-leaf plot preserves\n\n**A)** individual data values\n**B)** only the mean\n**C)** only correlation\n**D)** only residuals\n\n**Solution:** Leaves show actual observations.\n**Answer:** A\n\n## Problem 8\nWhen comparing two distributions of similar shape, a shift right in one boxplot indicates\n\n**A)** generally larger values\n**B)** smaller IQR only\n**C)** left skew only\n**D)** identical means necessarily\n\n**Solution:** Location shift toward larger numbers.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Problem-Solving and Data Analysis Pack 22: Mixed Data Analysis Challenge',
        "content": '# SAT Math · Problem-Solving and Data Analysis Pack 22: Mixed Data Analysis Challenge\n**Domain:** Problem-Solving and Data Analysis\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nRatio $a:b=4:9$ and $b=36$. Then $a=$\n\n**A)** $16$\n**B)** $9$\n**C)** $4$\n**D)** $36$\n\n**Solution:** $\\dfrac{4}{9}=\\dfrac{a}{36}$ → $a=16$.\n**Answer:** A\n\n## Problem 2\n$25\\%$ of a number is $45$. The number is\n\n**A)** $180$\n**B)** $70$\n**C)** $11.25$\n**D)** $135$\n\n**Solution:** $n/4=45$ → $n=180$.\n**Answer:** A\n\n## Problem 3\nResidual $=4$ when $\\hat{y}=11$ means actual $y=$\n\n**A)** $15$\n**B)** $7$\n**C)** $4$\n**D)** $11$\n\n**Solution:** $y=11+4=15$.\n**Answer:** A\n\n## Problem 4\nAverage speed for $120$ miles in $2.5$ hours is\n\n**A)** $48$ mph\n**B)** $50$ mph\n**C)** $30$ mph\n**D)** $60$ mph\n\n**Solution:** $120/2.5=48$.\n**Answer:** A\n\n## Problem 5\n$P(A)=0.6$, $P(B)=0.3$, independent. $P(A\\cap B)=$\n\n**A)** $0.18$\n**B)** $0.9$\n**C)** $0.3$\n**D)** $0.6$\n\n**Solution:** $0.6\\times 0.3=0.18$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Mean of $6,8,10,16$ is\n\n*Student-produced response — enter a number.*\n\n**Solution:** Sum $40$; mean $10$.\n**Answer (SPR):** 10\n\n## Problem 7\nA $15\\%$ tip on a $40$-dollar bill is\n\n**A)** $6$ dollars\n**B)** $15$ dollars\n**C)** $4$ dollars\n**D)** $10$ dollars\n\n**Solution:** $0.15\\times 40=6$.\n**Answer:** A\n\n## Problem 8\nLSRL slope $-2.5$ means predicted $y$\n\n**A)** decreases $2.5$ per unit $x$\n**B)** increases $2.5$ per unit $x$\n**C)** is always $-2.5$\n**D)** equals $r$\n\n**Solution:** Interpretation of negative slope.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Geometry and Trigonometry Pack 11: Circle Equations in the Plane',
        "content": '# SAT Math · Geometry and Trigonometry Pack 11: Circle Equations in the Plane\n**Domain:** Geometry and Trigonometry\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nThe circle $(x-3)^2+(y+2)^2=25$ has center\n\n**A)** $(3,-2)$\n**B)** $(-3,2)$\n**C)** $(3,2)$\n**D)** $(0,0)$\n\n**Solution:** Standard form $(x-h)^2+(y-k)^2=r^2$.\n**Answer:** A\n\n## Problem 2\nRadius of that circle is\n\n**A)** $5$\n**B)** $25$\n**C)** $10$\n**D)** $3$\n\n**Solution:** $r=\\sqrt{25}=5$.\n**Answer:** A\n\n## Problem 3\nEquation of circle center origin radius $4$:\n\n**A)** $x^2+y^2=16$\n**B)** $x^2+y^2=4$\n**C)** $(x-4)^2+y^2=0$\n**D)** $x+y=4$\n\n**Solution:** $r^2=16$.\n**Answer:** A\n\n## Problem 4\nDoes point $(3,4)$ lie on $x^2+y^2=25$?\n\n**A)** Yes\n**B)** No\n**C)** Only if $x=0$\n**D)** Only if $y=0$\n\n**Solution:** $9+16=25$.\n**Answer:** A\n\n## Problem 5\nDiameter endpoints $(2,1)$ and $(6,1)$. Center is\n\n**A)** $(4,1)$\n**B)** $(2,1)$\n**C)** $(4,0)$\n**D)** $(8,2)$\n\n**Solution:** Midpoint $\\left(\\dfrac{2+6}{2},\\dfrac{1+1}{2}\\right)$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: For $(x+5)^2+(y-1)^2=49$, enter the radius.\n\n*Student-produced response — enter a number.*\n\n**Solution:** $r=\\sqrt{49}=7$.\n**Answer (SPR):** 7\n\n## Problem 7\nWhich equation is a circle with radius $3$ centered at $(-2,0)$?\n\n**A)** $(x+2)^2+y^2=9$\n**B)** $(x-2)^2+y^2=9$\n**C)** $(x+2)^2+y^2=3$\n**D)** $x^2+(y+2)^2=9$\n\n**Solution:** $(x-(-2))^2+(y-0)^2=3^2$.\n**Answer:** A\n\n## Problem 8\nThe circle $x^2+y^2-6x+4y=0$ has center\n\n**A)** $(3,-2)$\n**B)** $(-3,2)$\n**C)** $(6,-4)$\n**D)** $(0,0)$\n\n**Solution:** Complete square: $(x-3)^2+(y+2)^2=13$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Geometry and Trigonometry Pack 12: Right Triangle Trig Applications',
        "content": '# SAT Math · Geometry and Trigonometry Pack 12: Right Triangle Trig Applications\n**Domain:** Geometry and Trigonometry\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nIn a right triangle, opposite $30$ and hypotenuse $10$. Adjacent side length (exact):\n\n**A)** $5\\sqrt{3}$\n**B)** $5$\n**C)** $10\\sqrt{3}$\n**D)** $5\\sqrt{2}$\n\n**Solution:** $\\cos 30=\\dfrac{\\sqrt{3}}{2}=\\dfrac{adj}{10}$ → $adj=5\\sqrt{3}$.\n**Answer:** A\n\n## Problem 2\nA ladder leans making $60^\\circ$ with ground; ladder length $12$ ft. Height on wall:\n\n**A)** $6\\sqrt{3}$ ft\n**B)** $6$ ft\n**C)** $12$ ft\n**D)** $4$ ft\n\n**Solution:** $\\sin 60=\\dfrac{h}{12}$ → $h=12\\cdot\\dfrac{\\sqrt{3}}{2}=6\\sqrt{3}$.\n**Answer:** A\n\n## Problem 3\nIf $\\tan\\theta=\\dfrac{3}{4}$ in a right triangle, $\\sin\\theta=$\n\n**A)** $\\dfrac{3}{5}$\n**B)** $\\dfrac{4}{5}$\n**C)** $\\dfrac{3}{4}$\n**D)** $\\dfrac{5}{3}$\n\n**Solution:** Sides $3$-$4$-$5$; opposite/hyp $=3/5$.\n**Answer:** A\n\n## Problem 4\nAngle of elevation $45^\\circ$ to a building $80$ m away. Building height:\n\n**A)** $80$ m\n**B)** $40$ m\n**C)** $80\\sqrt{2}$ m\n**D)** $40\\sqrt{2}$ m\n\n**Solution:** $\\tan 45=1=h/80$ → $h=80$.\n**Answer:** A\n\n## Problem 5\n$\\cos\\theta=\\dfrac{5}{13}$. Then $\\sin\\theta$ (acute $\\theta$) is\n\n**A)** $\\dfrac{12}{13}$\n**B)** $\\dfrac{5}{12}$\n**C)** $\\dfrac{13}{5}$\n**D)** $\\dfrac{12}{5}$\n\n**Solution:** Pythagorean triple $5$-$12$-$13$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Right triangle with legs $6$ and $8$. Hypotenuse length:\n\n*Student-produced response — enter a number.*\n\n**Solution:** $\\sqrt{36+64}=10$.\n**Answer (SPR):** 10\n\n## Problem 7\nFrom a point, angle of depression to a boat is $30^\\circ$. Cliff height $50$ m. Horizontal distance to boat:\n\n**A)** $50\\sqrt{3}$ m\n**B)** $25$ m\n**C)** $50$ m\n**D)** $100$ m\n\n**Solution:** $\\tan 30=\\dfrac{1}{\\sqrt{3}}=\\dfrac{50}{d}$ → $d=50\\sqrt{3}$.\n**Answer:** A\n\n## Problem 8\nIf $\\sin\\theta=\\dfrac{1}{2}$ and $\\theta$ acute, $\\theta=$\n\n**A)** $30^\\circ$\n**B)** $60^\\circ$\n**C)** $45^\\circ$\n**D)** $90^\\circ$\n\n**Solution:** Standard angle.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Geometry and Trigonometry Pack 13: Volume of Solids and Composites',
        "content": '# SAT Math · Geometry and Trigonometry Pack 13: Volume of Solids and Composites\n**Domain:** Geometry and Trigonometry\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nVolume of a rectangular box $4\\times 5\\times 6$ is\n\n**A)** $120$\n**B)** $15$\n**C)** $30$\n**D)** $240$\n\n**Solution:** $4\\cdot 5\\cdot 6=120$.\n**Answer:** A\n\n## Problem 2\nCylinder radius $3$, height $10$. Volume (in terms of $\\pi$):\n\n**A)** $90\\pi$\n**B)** $30\\pi$\n**C)** $60\\pi$\n**D)** $9\\pi$\n\n**Solution:** $\\pi r^2 h=\\pi\\cdot 9\\cdot 10=90\\pi$.\n**Answer:** A\n\n## Problem 3\nSphere radius $3$. Volume formula yields\n\n**A)** $36\\pi$\n**B)** $12\\pi$\n**C)** $9\\pi$\n**D)** $108\\pi$\n\n**Solution:** $\\dfrac{4}{3}\\pi r^3=\\dfrac{4}{3}\\pi\\cdot 27=36\\pi$.\n**Answer:** A\n\n## Problem 4\nCone radius $4$, height $9$. Volume:\n\n**A)** $48\\pi$\n**B)** $144\\pi$\n**C)** $36\\pi$\n**D)** $12\\pi$\n\n**Solution:** $\\dfrac{1}{3}\\pi r^2 h=\\dfrac{1}{3}\\pi\\cdot 16\\cdot 9=48\\pi$.\n**Answer:** A\n\n## Problem 5\nA cube has edge $5$. Surface area is\n\n**A)** $150$\n**B)** $125$\n**C)** $25$\n**D)** $30$\n\n**Solution:** $6\\cdot 25=150$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Prism base area $20$ and height $7$. Volume:\n\n*Student-produced response — enter a number.*\n\n**Solution:** $V=Bh=140$.\n**Answer (SPR):** 140\n\n## Problem 7\nComposite: cube edge $4$ with a square hole of side $2$ drilled through (prism hole). Remaining volume:\n\n**A)** $48$\n**B)** $64$\n**C)** $16$\n**D)** $32$\n\n**Solution:** $64-2\\cdot 2\\cdot 4=64-16=48$.\n**Answer:** A\n\n## Problem 8\nScaled solid with linear scale factor $2$ multiplies volume by\n\n**A)** $8$\n**B)** $2$\n**C)** $4$\n**D)** $6$\n\n**Solution:** Volumes scale by cube of linear factor.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Geometry and Trigonometry Pack 14: Arc Length and Sector Area',
        "content": '# SAT Math · Geometry and Trigonometry Pack 14: Arc Length and Sector Area\n**Domain:** Geometry and Trigonometry\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nCircle radius $6$, central angle $60^\\circ$. Arc length:\n\n**A)** $2\\pi$\n**B)** $6\\pi$\n**C)** $\\pi$\n**D)** $12\\pi$\n\n**Solution:** $\\dfrac{60}{360}\\cdot 2\\pi\\cdot 6=2\\pi$.\n**Answer:** A\n\n## Problem 2\nSame circle/angle, sector area:\n\n**A)** $6\\pi$\n**B)** $2\\pi$\n**C)** $36\\pi$\n**D)** $12\\pi$\n\n**Solution:** $\\dfrac{60}{360}\\pi r^2=\\dfrac{1}{6}\\cdot 36\\pi=6\\pi$.\n**Answer:** A\n\n## Problem 3\nArc length $10\\pi$ on radius $10$. Central angle in degrees:\n\n**A)** $180^\\circ$\n**B)** $90^\\circ$\n**C)** $360^\\circ$\n**D)** $45^\\circ$\n\n**Solution:** $\\dfrac{\\theta}{360}\\cdot 2\\pi\\cdot 10=10\\pi$ → $\\theta=180$.\n**Answer:** A\n\n## Problem 4\nSector with radius $4$ and angle $\\dfrac{\\pi}{3}$ radians. Area:\n\n**A)** $\\dfrac{8\\pi}{3}$\n**B)** $\\dfrac{4\\pi}{3}$\n**C)** $4\\pi$\n**D)** $\\dfrac{16\\pi}{3}$\n\n**Solution:** $\\dfrac{1}{2}r^2\\theta=\\dfrac{1}{2}\\cdot 16\\cdot\\dfrac{\\pi}{3}=\\dfrac{8\\pi}{3}$.\n**Answer:** A\n\n## Problem 5\nFull circumference of radius $7$ is\n\n**A)** $14\\pi$\n**B)** $7\\pi$\n**C)** $49\\pi$\n**D)** $21\\pi$\n\n**Solution:** $2\\pi r$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Radius $9$, central angle $40^\\circ$. Sector area over $\\pi$ equals (enter the coefficient of $\\pi$):\n\n*Student-produced response — enter a number.*\n\n**Solution:** $\\dfrac{40}{360}\\pi\\cdot 81=9\\pi$ → coefficient $9$.\n**Answer (SPR):** 9\n\n## Problem 7\nMinor arc AB is $\\dfrac{1}{5}$ of the circle. Radius $10$. Arc length:\n\n**A)** $4\\pi$\n**B)** $2\\pi$\n**C)** $10\\pi$\n**D)** $20\\pi$\n\n**Solution:** $\\dfrac{1}{5}\\cdot 2\\pi\\cdot 10=4\\pi$.\n**Answer:** A\n\n## Problem 8\nDoubling the radius of a sector (same central angle) multiplies sector area by\n\n**A)** $4$\n**B)** $2$\n**C)** $8$\n**D)** $1$\n\n**Solution:** Area $\\propto r^2$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Geometry and Trigonometry Pack 15: Coordinate Geometry Distances',
        "content": '# SAT Math · Geometry and Trigonometry Pack 15: Coordinate Geometry Distances\n**Domain:** Geometry and Trigonometry\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nDistance between $(1,2)$ and $(4,6)$ is\n\n**A)** $5$\n**B)** $7$\n**C)** $25$\n**D)** $\\sqrt{7}$\n\n**Solution:** $\\sqrt{(3)^2+(4)^2}=5$.\n**Answer:** A\n\n## Problem 2\nMidpoint of $(-2,5)$ and $(6,1)$ is\n\n**A)** $(2,3)$\n**B)** $(4,6)$\n**C)** $(2,4)$\n**D)** $(0,3)$\n\n**Solution:** $\\left(\\dfrac{-2+6}{2},\\dfrac{5+1}{2}\\right)$.\n**Answer:** A\n\n## Problem 3\nPoint equidistant from $(0,0)$ and $(6,0)$ on the $x$-axis is\n\n**A)** $(3,0)$\n**B)** $(0,0)$\n**C)** $(6,0)$\n**D)** $(3,3)$\n\n**Solution:** Perpendicular bisector meets axis at midpoint.\n**Answer:** A\n\n## Problem 4\nPerimeter of triangle with vertices $(0,0)$, $(3,0)$, $(0,4)$ is\n\n**A)** $12$\n**B)** $7$\n**C)** $5$\n**D)** $10$\n\n**Solution:** Sides $3$, $4$, $5$; sum $12$.\n**Answer:** A\n\n## Problem 5\nEquation of vertical line through $(5,-3)$:\n\n**A)** $x=5$\n**B)** $y=-3$\n**C)** $y=5$\n**D)** $x=-3$\n\n**Solution:** Vertical: $x=$ constant.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Distance from $(0,0)$ to $(8,15)$ is\n\n*Student-produced response — enter a number.*\n\n**Solution:** $\\sqrt{64+225}=17$.\n**Answer (SPR):** 17\n\n## Problem 7\nWhich point is $5$ units from $(1,1)$?\n\n**A)** $(1,6)$\n**B)** $(1,4)$\n**C)** $(2,2)$\n**D)** $(0,0)$\n\n**Solution:** Vertical distance $5$.\n**Answer:** A\n\n## Problem 8\nSlope between $(2,7)$ and $(2,-1)$ is\n\n**A)** undefined\n**B)** $0$\n**C)** $4$\n**D)** $-4$\n\n**Solution:** Vertical segment.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Geometry and Trigonometry Pack 16: Similar Triangles Applications',
        "content": "# SAT Math · Geometry and Trigonometry Pack 16: Similar Triangles Applications\n**Domain:** Geometry and Trigonometry\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nTriangles similar with ratio $2:5$. If smaller perimeter $18$, larger perimeter is\n\n**A)** $45$\n**B)** $36$\n**C)** $22.5$\n**D)** $9$\n\n**Solution:** $18\\cdot\\dfrac{5}{2}=45$.\n**Answer:** A\n\n## Problem 2\nSimilar triangles; corresponding sides $6$ and $9$. Scale factor large/small:\n\n**A)** $\\dfrac{3}{2}$\n**B)** $\\dfrac{2}{3}$\n**C)** $3$\n**D)** $15$\n\n**Solution:** $9/6=1.5$.\n**Answer:** A\n\n## Problem 3\nA shadow problem: $6$ ft pole casts $4$ ft shadow; nearby tree casts $20$ ft shadow. Tree height:\n\n**A)** $30$ ft\n**B)** $24$ ft\n**C)** $15$ ft\n**D)** $10$ ft\n\n**Solution:** $\\dfrac{6}{4}=\\dfrac{h}{20}$ → $h=30$.\n**Answer:** A\n\n## Problem 4\nAreas of similar figures scale by square of side ratio. Side ratio $3$ → area ratio\n\n**A)** $9$\n**B)** $3$\n**C)** $6$\n**D)** $27$\n\n**Solution:** $3^2=9$.\n**Answer:** A\n\n## Problem 5\nIn similar right triangles, if hypotenuses are $10$ and $15$, a leg $6$ on the smaller corresponds to\n\n**A)** $9$\n**B)** $4$\n**C)** $12$\n**D)** $7.5$\n\n**Solution:** $6\\cdot\\dfrac{3}{2}=9$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Similar triangles with side ratio $1:4$. Smaller area $5$. Larger area:\n\n*Student-produced response — enter a number.*\n\n**Solution:** $5\\cdot 16=80$.\n**Answer (SPR):** 80\n\n## Problem 7\nAA similarity requires\n\n**A)** two pairs of congruent corresponding angles\n**B)** all three sides proportional only SSS\n**C)** right angles only\n**D)** equal perimeters\n\n**Solution:** Angle-Angle criterion.\n**Answer:** A\n\n## Problem 8\nA midsegment parallel to a triangle's base is half as long as the base. If base $16$, midsegment is\n\n**A)** $8$\n**B)** $16$\n**C)** $32$\n**D)** $4$\n\n**Solution:** Midsegment theorem.\n**Answer:** A\n",
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Geometry and Trigonometry Pack 17: Special Right Triangles and Exact Values',
        "content": '# SAT Math · Geometry and Trigonometry Pack 17: Special Right Triangles and Exact Values\n**Domain:** Geometry and Trigonometry\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nIn a $45$-$45$-$90$ triangle with leg $7$, hypotenuse is\n\n**A)** $7\\sqrt{2}$\n**B)** $7$\n**C)** $14$\n**D)** $14\\sqrt{2}$\n\n**Solution:** Hypotenuse $=$ leg$\\sqrt{2}$.\n**Answer:** A\n\n## Problem 2\nIn a $30$-$60$-$90$ triangle, shorter leg $5$. Longer leg is\n\n**A)** $5\\sqrt{3}$\n**B)** $10$\n**C)** $5\\sqrt{2}$\n**D)** $15$\n\n**Solution:** Longer leg $=$ short$\\sqrt{3}$.\n**Answer:** A\n\n## Problem 3\nSame triangle, hypotenuse is\n\n**A)** $10$\n**B)** $5\\sqrt{3}$\n**C)** $15$\n**D)** $5$\n\n**Solution:** Hypotenuse $=$ $2\\times$ short leg.\n**Answer:** A\n\n## Problem 4\n$\\sin 45^\\circ=$\n\n**A)** $\\dfrac{\\sqrt{2}}{2}$\n**B)** $\\dfrac{1}{2}$\n**C)** $\\dfrac{\\sqrt{3}}{2}$\n**D)** $1$\n\n**Solution:** Standard exact value.\n**Answer:** A\n\n## Problem 5\n$\\cos 60^\\circ=$\n\n**A)** $\\dfrac{1}{2}$\n**B)** $\\dfrac{\\sqrt{3}}{2}$\n**C)** $\\dfrac{\\sqrt{2}}{2}$\n**D)** $0$\n\n**Solution:** Standard exact value.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: A $45$-$45$-$90$ triangle has hypotenuse $10\\sqrt{2}$. Each leg length:\n\n*Student-produced response — enter a number.*\n\n**Solution:** Leg $=$ hyp$/\\sqrt{2}=10$.\n**Answer (SPR):** 10\n\n## Problem 7\nAltitude to the hypotenuse in a right triangle creates\n\n**A)** two smaller right triangles similar to each other and the original\n**B)** equilateral triangles\n**C)** only isosceles non-right\n**D)** congruent circles\n\n**Solution:** Geometric mean / similarity relations.\n**Answer:** A\n\n## Problem 8\nIf $\\tan 30^\\circ=\\dfrac{1}{\\sqrt{3}}$ and opposite side is $4$, adjacent is\n\n**A)** $4\\sqrt{3}$\n**B)** $4$\n**C)** $12$\n**D)** $\\dfrac{4}{3}$\n\n**Solution:** $\\dfrac{opp}{adj}=\\dfrac{1}{\\sqrt{3}}$ → $adj=4\\sqrt{3}$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Geometry and Trigonometry Pack 18: Surface Area Applications',
        "content": '# SAT Math · Geometry and Trigonometry Pack 18: Surface Area Applications\n**Domain:** Geometry and Trigonometry\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nSurface area of a cube with edge $6$ is\n\n**A)** $216$\n**B)** $36$\n**C)** $72$\n**D)** $108$\n\n**Solution:** $6\\cdot 6^2=216$.\n**Answer:** A\n\n## Problem 2\nCylinder radius $2$, height $5$. Lateral surface area:\n\n**A)** $20\\pi$\n**B)** $10\\pi$\n**C)** $4\\pi$\n**D)** $40\\pi$\n\n**Solution:** $2\\pi rh=2\\pi\\cdot 2\\cdot 5=20\\pi$.\n**Answer:** A\n\n## Problem 3\nSphere radius $5$. Surface area:\n\n**A)** $100\\pi$\n**B)** $125\\pi$\n**C)** $20\\pi$\n**D)** $25\\pi$\n\n**Solution:** $4\\pi r^2=100\\pi$.\n**Answer:** A\n\n## Problem 4\nRectangular prism $3\\times 4\\times 5$. Surface area:\n\n**A)** $94$\n**B)** $60$\n**C)** $47$\n**D)** $120$\n\n**Solution:** $2(12+15+20)=94$.\n**Answer:** A\n\n## Problem 5\nCone slant height $10$, radius $6$. Lateral area:\n\n**A)** $60\\pi$\n**B)** $30\\pi$\n**C)** $120\\pi$\n**D)** $16\\pi$\n\n**Solution:** $\\pi r\\ell=\\pi\\cdot 6\\cdot 10=60\\pi$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Cube edge $4$. Surface area:\n\n*Student-produced response — enter a number.*\n\n**Solution:** $6\\cdot 16=96$.\n**Answer (SPR):** 96\n\n## Problem 7\nPainting the outside of a closed cylinder (incl. bases) radius $3$ height $4$ uses area\n\n**A)** $42\\pi$\n**B)** $24\\pi$\n**C)** $36\\pi$\n**D)** $12\\pi$\n\n**Solution:** $2\\pi rh+2\\pi r^2=24\\pi+18\\pi=42\\pi$.\n**Answer:** A\n\n## Problem 8\nIf each edge of a cube doubles, surface area multiplies by\n\n**A)** $4$\n**B)** $2$\n**C)** $8$\n**D)** $6$\n\n**Solution:** Area scales by square of linear factor.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Geometry and Trigonometry Pack 19: Inscribed Angles and Chords',
        "content": '# SAT Math · Geometry and Trigonometry Pack 19: Inscribed Angles and Chords\n**Domain:** Geometry and Trigonometry\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nAn inscribed angle intercepting a $80^\\circ$ arc measures\n\n**A)** $40^\\circ$\n**B)** $80^\\circ$\n**C)** $160^\\circ$\n**D)** $20^\\circ$\n\n**Solution:** Inscribed angle is half the intercepted arc.\n**Answer:** A\n\n## Problem 2\nA central angle intercepting the same arc measures\n\n**A)** $80^\\circ$\n**B)** $40^\\circ$\n**C)** $160^\\circ$\n**D)** $20^\\circ$\n\n**Solution:** Central angle equals the arc.\n**Answer:** A\n\n## Problem 3\nAngle in a semicircle (hypotenuse as diameter) is\n\n**A)** $90^\\circ$\n**B)** $45^\\circ$\n**C)** $60^\\circ$\n**D)** $180^\\circ$\n\n**Solution:** Theorem: angle in a semicircle is right.\n**Answer:** A\n\n## Problem 4\nTwo chords intersect inside a circle. Segments $3$ and $4$ on one chord; other chord parts $2$ and $x$. Then $x=$\n\n**A)** $6$\n**B)** $5$\n**C)** $8$\n**D)** $1.5$\n\n**Solution:** $3\\cdot 4=2x$ → $x=6$.\n**Answer:** A\n\n## Problem 5\nA tangent is perpendicular to the radius at the point of contact. If radius is vertical, tangent is\n\n**A)** horizontal\n**B)** vertical\n**C)** at $45^\\circ$\n**D)** undefined\n\n**Solution:** Perpendicular lines.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Inscribed angle is $25^\\circ$. Measure of intercepted arc in degrees:\n\n*Student-produced response — enter a number.*\n\n**Solution:** Arc $=2\\cdot 25=50$.\n**Answer (SPR):** 50\n\n## Problem 7\nEqual chords in the same circle are\n\n**A)** equidistant from the center\n**B)** always diameters\n**C)** perpendicular\n**D)** never congruent arcs\n\n**Solution:** Equal chords ↔ equal distance from center.\n**Answer:** A\n\n## Problem 8\nA $120^\\circ$ central angle in a circle leaves a major arc of\n\n**A)** $240^\\circ$\n**B)** $120^\\circ$\n**C)** $60^\\circ$\n**D)** $360^\\circ$\n\n**Solution:** $360-120=240$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Geometry and Trigonometry Pack 20: 3D Diagonals and Space Figures',
        "content": '# SAT Math · Geometry and Trigonometry Pack 20: 3D Diagonals and Space Figures\n**Domain:** Geometry and Trigonometry\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nSpace diagonal of a $2\\times 3\\times 6$ rectangular box is\n\n**A)** $7$\n**B)** $\\sqrt{13}$\n**C)** $11$\n**D)** $6$\n\n**Solution:** $\\sqrt{4+9+36}=\\sqrt{49}=7$.\n**Answer:** A\n\n## Problem 2\nFace diagonal on the $3\\times 6$ face is\n\n**A)** $\\sqrt{45}=3\\sqrt{5}$\n**B)** $9$\n**C)** $3$\n**D)** $18$\n\n**Solution:** $\\sqrt{9+36}=\\sqrt{45}$.\n**Answer:** A\n\n## Problem 3\nA cube edge $s$ has space diagonal\n\n**A)** $s\\sqrt{3}$\n**B)** $s\\sqrt{2}$\n**C)** $3s$\n**D)** $s^2$\n\n**Solution:** $\\sqrt{s^2+s^2+s^2}$.\n**Answer:** A\n\n## Problem 4\nPyramid volume with base area $30$ and height $6$ is\n\n**A)** $60$\n**B)** $180$\n**C)** $90$\n**D)** $36$\n\n**Solution:** $V=\\dfrac{1}{3}Bh=60$.\n**Answer:** A\n\n## Problem 5\nA plane cross-section of a sphere through the center is\n\n**A)** a great circle\n**B)** an ellipse only\n**C)** a square\n**D)** a point\n\n**Solution:** Great circle definition.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Cube edge $5$. Space diagonal squared equals\n\n*Student-produced response — enter a number.*\n\n**Solution:** $3\\cdot 25=75$.\n**Answer (SPR):** 75\n\n## Problem 7\nNet of a cube consists of how many square faces?\n\n**A)** $6$\n**B)** $4$\n**C)** $8$\n**D)** $12$\n\n**Solution:** Six faces.\n**Answer:** A\n\n## Problem 8\nCylinder and cone share radius and height. Cone volume is what fraction of cylinder?\n\n**A)** $\\dfrac{1}{3}$\n**B)** $\\dfrac{1}{2}$\n**C)** $\\dfrac{2}{3}$\n**D)** $1$\n\n**Solution:** $\\dfrac{1}{3}\\pi r^2 h$ vs $\\pi r^2 h$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Geometry and Trigonometry Pack 21: Trig Co-functions and Complementary Angles',
        "content": '# SAT Math · Geometry and Trigonometry Pack 21: Trig Co-functions and Complementary Angles\n**Domain:** Geometry and Trigonometry\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\n$\\sin 20^\\circ=\\cos\\,?$\n\n**A)** $70^\\circ$\n**B)** $20^\\circ$\n**C)** $40^\\circ$\n**D)** $160^\\circ$\n\n**Solution:** Co-function: $\\sin\\theta=\\cos(90^\\circ-\\theta)$.\n**Answer:** A\n\n## Problem 2\n$\\cos 55^\\circ=\\sin\\,?$\n\n**A)** $35^\\circ$\n**B)** $55^\\circ$\n**C)** $45^\\circ$\n**D)** $125^\\circ$\n\n**Solution:** $90-55=35$.\n**Answer:** A\n\n## Problem 3\nIf $\\sin\\theta=\\cos\\theta$ and $0^\\circ<\\theta<90^\\circ$, then $\\theta=$\n\n**A)** $45^\\circ$\n**B)** $30^\\circ$\n**C)** $60^\\circ$\n**D)** $90^\\circ$\n\n**Solution:** Equal at $45^\\circ$.\n**Answer:** A\n\n## Problem 4\n$\\tan(90^\\circ-\\theta)=$\n\n**A)** $\\cot\\theta$\n**B)** $\\tan\\theta$\n**C)** $-\\tan\\theta$\n**D)** $\\sin\\theta$\n\n**Solution:** Co-function identity.\n**Answer:** A\n\n## Problem 5\nIn a right triangle, acute angles are complementary, so if one is $28^\\circ$, the other is\n\n**A)** $62^\\circ$\n**B)** $28^\\circ$\n**C)** $72^\\circ$\n**D)** $152^\\circ$\n\n**Solution:** $90-28=62$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: If $\\sin\\theta=0.6$ and $\\theta$ acute, enter $\\cos(90^\\circ-\\theta)$ as a decimal (same value):\n\n*Student-produced response — enter a number.*\n\n**Solution:** Co-function: $\\cos(90-\\theta)=\\sin\\theta=0.6$.\n**Answer (SPR):** 0.6\n\n## Problem 7\nWhich is true?\n\n**A)** $\\sin^2\\theta+\\cos^2\\theta=1$\n**B)** $\\sin\\theta+\\cos\\theta=1$ always\n**C)** $\\tan\\theta=\\sin\\theta$\n**D)** $\\sin\\theta=\\theta$\n\n**Solution:** Pythagorean identity.\n**Answer:** A\n\n## Problem 8\n$\\sec\\theta=$\n\n**A)** $\\dfrac{1}{\\cos\\theta}$\n**B)** $\\dfrac{1}{\\sin\\theta}$\n**C)** $\\cos\\theta$\n**D)** $\\tan\\theta$\n\n**Solution:** Reciprocal definition.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Geometry and Trigonometry Pack 22: Mixed Geometry and Trig Challenge',
        "content": '# SAT Math · Geometry and Trigonometry Pack 22: Mixed Geometry and Trig Challenge\n**Domain:** Geometry and Trigonometry\n\nOriginal AI practice — not College Board exam items.\n\n## Problem 1\nCircle $(x+1)^2+(y-4)^2=36$ has radius\n\n**A)** $6$\n**B)** $36$\n**C)** $18$\n**D)** $4$\n\n**Solution:** $\\sqrt{36}=6$.\n**Answer:** A\n\n## Problem 2\nRight triangle legs $5$ and $12$. $\\sin$ of angle opposite $5$ is\n\n**A)** $\\dfrac{5}{13}$\n**B)** $\\dfrac{12}{13}$\n**C)** $\\dfrac{5}{12}$\n**D)** $\\dfrac{13}{5}$\n\n**Solution:** Hypotenuse $13$.\n**Answer:** A\n\n## Problem 3\nCylinder volume radius $4$ height $3$:\n\n**A)** $48\\pi$\n**B)** $12\\pi$\n**C)** $16\\pi$\n**D)** $36\\pi$\n\n**Solution:** $\\pi\\cdot 16\\cdot 3=48\\pi$.\n**Answer:** A\n\n## Problem 4\nArc length radius $12$ angle $90^\\circ$:\n\n**A)** $6\\pi$\n**B)** $12\\pi$\n**C)** $3\\pi$\n**D)** $24\\pi$\n\n**Solution:** $\\dfrac{1}{4}\\cdot 2\\pi\\cdot 12=6\\pi$.\n**Answer:** A\n\n## Problem 5\nSimilar triangles side ratio $2:3$. Area ratio:\n\n**A)** $4:9$\n**B)** $2:3$\n**C)** $8:27$\n**D)** $1:3$\n\n**Solution:** Square the side ratio.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Distance between $(0,0)$ and $(9,12)$:\n\n*Student-produced response — enter a number.*\n\n**Solution:** $15$.\n**Answer (SPR):** 15\n\n## Problem 7\nInscribed angle $35^\\circ$ intercepts an arc of\n\n**A)** $70^\\circ$\n**B)** $35^\\circ$\n**C)** $145^\\circ$\n**D)** $17.5^\\circ$\n\n**Solution:** Arc is twice the inscribed angle.\n**Answer:** A\n\n## Problem 8\n$\\sin 30^\\circ+\\cos 60^\\circ=$\n\n**A)** $1$\n**B)** $\\dfrac{1}{2}$\n**C)** $\\dfrac{\\sqrt{3}}{2}$\n**D)** $0$\n\n**Solution:** $\\dfrac{1}{2}+\\dfrac{1}{2}=1$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
]
