"""Original Digital SAT Math practice corpus for managed-content injection.

Aligned to College Board Digital SAT Math content domains:
Algebra, Advanced Math, Problem-Solving and Data Analysis,
Geometry and Trigonometry.
All entries use space="sat-mathematics" and category="SAT Mathematics".
Problems are original AI practice — not College Board exam items.
"""

from __future__ import annotations


SAT_MATH_DOCS: list[dict[str, str]] = [
    {
        "title": 'SAT Math · Algebra Pack 01: Linear Equations',
        "content": '# SAT Math · Algebra Pack 01: Linear Equations\n**Domain:** Algebra\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nSolve for $x$: $3x-7=11$.\n\n**A)** $x=4$\n**B)** $x=6$\n**C)** $x=\\dfrac{18}{3}$\n**D)** $x=-6$\n\n**Solution:** Add 7: $3x=18$, so $x=6$.\n**Answer:** B\n\n## Problem 2\nSolve: $5(x-2)=3x+4$.\n\n**A)** $x=7$\n**B)** $x=5$\n**C)** $x=3$\n**D)** $x=-1$\n\n**Solution:** $5x-10=3x+4$ → $2x=14$ → $x=7$.\n**Answer:** A\n\n## Problem 3\nIf $2x+9=3$, what is the value of $4x+1$?\n\n**A)** $-11$\n**B)** $-7$\n**C)** $1$\n**D)** $5$\n\n**Solution:** $2x=-6$ → $x=-3$ → $4x+1=-11$.\n**Answer:** A\n\n## Problem 4\nSolve $\\dfrac{x}{4}+5=8$.\n\n**A)** $x=12$\n**B)** $x=3$\n**C)** $x=32$\n**D)** $x=20$\n\n**Solution:** $\\dfrac{x}{4}=3$ → $x=12$.\n**Answer:** A\n\n## Problem 5\nWhich value of $x$ satisfies $7-2x=x+1$?\n\n**A)** $x=1$\n**B)** $x=2$\n**C)** $x=3$\n**D)** $x=4$\n\n**Solution:** $7-1=3x$ → $6=3x$ → $x=2$.\n**Answer:** B\n\n## Problem 6 (SPR)\nSPR: Solve $6x+5=29$. Enter the value of $x$.\n\n*Student-produced response — enter a number.*\n\n**Solution:** $6x=24$ → $x=4$.\n**Answer (SPR):** 4\n\n## Problem 7\nSolve $\\dfrac{2x-1}{3}=5$.\n\n**A)** $x=7$\n**B)** $x=8$\n**C)** $x=16$\n**D)** $x=\\dfrac{14}{2}$\n\n**Solution:** $2x-1=15$ → $2x=16$ → $x=8$.\n**Answer:** B\n\n## Problem 8\nIf $4(2x-3)=2(x+9)$, then $x=$\n\n**A)** $\\dfrac{15}{3}$\n**B)** $5$\n**C)** $3$\n**D)** $\\dfrac{21}{6}$\n\n**Solution:** $8x-12=2x+18$ → $6x=30$ → $x=5$.\n**Answer:** B\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Algebra Pack 02: Linear Functions',
        "content": '# SAT Math · Algebra Pack 02: Linear Functions\n**Domain:** Algebra\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nA line has slope $m=-2$ and $y$-intercept $5$. Which equation represents the line?\n\n**A)** $y=-2x+5$\n**B)** $y=2x-5$\n**C)** $y=-2x-5$\n**D)** $y=5x-2$\n\n**Solution:** Slope-intercept form is $y=mx+b$.\n**Answer:** A\n\n## Problem 2\nFor $f(x)=3x-4$, what is $f(5)$?\n\n**A)** $11$\n**B)** $15$\n**C)** $19$\n**D)** $7$\n\n**Solution:** $f(5)=15-4=11$.\n**Answer:** A\n\n## Problem 3\nIf $g(x)=mx+2$ and $g(3)=11$, what is $m$?\n\n**A)** $3$\n**B)** $2$\n**C)** $4$\n**D)** $9$\n\n**Solution:** $3m+2=11$ → $3m=9$ → $m=3$.\n**Answer:** A\n\n## Problem 4\nWhich table could represent a linear function with constant rate of change $4$?\n\n**A)** $(0,1),(1,5),(2,9)$\n**B)** $(0,1),(1,4),(2,8)$\n**C)** $(0,0),(1,3),(2,9)$\n**D)** $(1,2),(2,5),(3,7)$\n\n**Solution:** Differences in $y$: $4,4$ — constant slope $4$.\n**Answer:** A\n\n## Problem 5\nThe graph of $y=ax+b$ passes through $(0,-3)$ and $(2,1)$. What is $a$?\n\n**A)** $2$\n**B)** $-2$\n**C)** $1$\n**D)** $4$\n\n**Solution:** $b=-3$; $1=2a-3$ → $2a=4$ → $a=2$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: For $h(x)=-x+9$, find $h(4)$.\n\n*Student-produced response — enter a number.*\n\n**Solution:** $h(4)=-4+9=5$.\n**Answer (SPR):** 5\n\n## Problem 7\nIf $f(x)=2x+k$ and $f(1)=f(3)-4$, what is $k$?\n\n**A)** Any real number\n**B)** $0$\n**C)** $2$\n**D)** No such $k$\n\n**Solution:** $2+k=(6+k)-4$ → $2+k=2+k$, true for all $k$.\n**Answer:** A\n\n## Problem 8\nA linear function $p$ satisfies $p(0)=6$ and $p(2)=0$. Which is $p(x)$?\n\n**A)** $p(x)=-3x+6$\n**B)** $p(x)=3x+6$\n**C)** $p(x)=-3x-6$\n**D)** $p(x)=-6x+3$\n\n**Solution:** Slope $=\\dfrac{0-6}{2-0}=-3$; intercept $6$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Algebra Pack 03: Two-Variable Linear Equations',
        "content": '# SAT Math · Algebra Pack 03: Two-Variable Linear Equations\n**Domain:** Algebra\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nWhich ordered pair is a solution of $2x+y=10$?\n\n**A)** $(3,4)$\n**B)** $(2,5)$\n**C)** $(4,1)$\n**D)** $(5,1)$\n\n**Solution:** $2(3)+4=10$.\n**Answer:** A\n\n## Problem 2\nSolve for $y$ in terms of $x$: $3x-2y=12$.\n\n**A)** $y=\\dfrac{3x-12}{2}$\n**B)** $y=\\dfrac{12-3x}{2}$\n**C)** $y=3x-12$\n**D)** $y=\\dfrac{3}{2}x+6$\n\n**Solution:** $-2y=12-3x$ → $y=\\dfrac{3x-12}{2}$.\n**Answer:** A\n\n## Problem 3\nThe line $x+4y=8$ intersects the $y$-axis at\n\n**A)** $(0,2)$\n**B)** $(0,8)$\n**C)** $(8,0)$\n**D)** $(0,-2)$\n\n**Solution:** Set $x=0$: $4y=8$ → $y=2$.\n**Answer:** A\n\n## Problem 4\nIf $x-y=5$ and $x=8$, then $y=$\n\n**A)** $3$\n**B)** $-3$\n**C)** $13$\n**D)** $5$\n\n**Solution:** $8-y=5$ → $y=3$.\n**Answer:** A\n\n## Problem 5\nWhich equation is equivalent to $y=\\dfrac{1}{2}x-3$?\n\n**A)** $x-2y=6$\n**B)** $x-2y=-6$\n**C)** $2x-y=6$\n**D)** $x+2y=6$\n\n**Solution:** $2y=x-6$ → $x-2y=6$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: On the line $3x+y=15$, when $x=2$, what is $y$?\n\n*Student-produced response — enter a number.*\n\n**Solution:** $6+y=15$ → $y=9$.\n**Answer (SPR):** 9\n\n## Problem 7\nA point $(a,a)$ lies on $2x+3y=20$. Find $a$.\n\n**A)** $4$\n**B)** $5$\n**C)** $2$\n**D)** $8$\n\n**Solution:** $2a+3a=20$ → $5a=20$ → $a=4$.\n**Answer:** A\n\n## Problem 8\nThe $x$-intercept of $5x-2y=10$ is\n\n**A)** $2$\n**B)** $5$\n**C)** $-5$\n**D)** $10$\n\n**Solution:** Set $y=0$: $5x=10$ → $x=2$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Algebra Pack 04: Systems of Linear Equations',
        "content": '# SAT Math · Algebra Pack 04: Systems of Linear Equations\n**Domain:** Algebra\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nSolve the system: $x+y=7$, $x-y=3$. What is $x$?\n\n**A)** $5$\n**B)** $4$\n**C)** $3$\n**D)** $2$\n\n**Solution:** Add: $2x=10$ → $x=5$.\n**Answer:** A\n\n## Problem 2\nFor $2x+y=9$ and $x-y=0$, the solution $(x,y)$ is\n\n**A)** $(3,3)$\n**B)** $(2,5)$\n**C)** $(4,1)$\n**D)** $(3,6)$\n\n**Solution:** From second, $y=x$; $2x+x=9$ → $x=3$.\n**Answer:** A\n\n## Problem 3\nHow many solutions does $y=2x+1$ and $2y=4x+2$ have?\n\n**A)** Infinitely many\n**B)** None\n**C)** Exactly one\n**D)** Exactly two\n\n**Solution:** Second is $y=2x+1$; same line.\n**Answer:** A\n\n## Problem 4\nThe system $y=3x-1$ and $y=-x+7$ intersects when $x=$\n\n**A)** $2$\n**B)** $1$\n**C)** $3$\n**D)** $4$\n\n**Solution:** $3x-1=-x+7$ → $4x=8$ → $x=2$.\n**Answer:** A\n\n## Problem 5\nIf $3x+2y=16$ and $x=2$, then $y=$\n\n**A)** $5$\n**B)** $4$\n**C)** $3$\n**D)** $2$\n\n**Solution:** $6+2y=16$ → $2y=10$ → $y=5$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: For $x+2y=10$ and $3x-2y=6$, find $x$.\n\n*Student-produced response — enter a number.*\n\n**Solution:** Add: $4x=16$ → $x=4$.\n**Answer (SPR):** 4\n\n## Problem 7\nWhich system has no solution?\n\n**A)** $y=2x+1$ and $y=2x-3$\n**B)** $y=x$ and $y=-x$\n**C)** $x+y=1$ and $2x-y=2$\n**D)** $y=3$ and $x=4$\n\n**Solution:** Parallel distinct lines (same slope, different intercept).\n**Answer:** A\n\n## Problem 8\nAdult tickets cost 12 dollars and child tickets cost 8 dollars. Buying 5 tickets costs 48 dollars. If $a$ adult and $c$ child tickets satisfy $a+c=5$ and $12a+8c=48$, then $a=$\n\n**A)** $2$\n**B)** $3$\n**C)** $1$\n**D)** $4$\n\n**Solution:** From first $c=5-a$: $12a+8(5-a)=48$ → $4a=8$ → $a=2$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Algebra Pack 05: Linear Inequalities',
        "content": '# SAT Math · Algebra Pack 05: Linear Inequalities\n**Domain:** Algebra\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nSolve $2x-5>7$.\n\n**A)** $x>6$\n**B)** $x>1$\n**C)** $x<6$\n**D)** $x\\ge 6$\n\n**Solution:** $2x>12$ → $x>6$.\n**Answer:** A\n\n## Problem 2\nWhich value satisfies $-3x\\ge 12$?\n\n**A)** $x=-5$\n**B)** $x=-2$\n**C)** $x=0$\n**D)** $x=4$\n\n**Solution:** Divide by $-3$ (flip): $x\\le -4$. Only $-5$ works.\n**Answer:** A\n\n## Problem 3\nThe solution set of $x+4\\le 2x-1$ is\n\n**A)** $x\\ge 5$\n**B)** $x\\le 5$\n**C)** $x\\ge -5$\n**D)** $x>5$\n\n**Solution:** $4+1\\le 2x-x$ → $5\\le x$.\n**Answer:** A\n\n## Problem 4\nWhich graph description matches $y>x+2$?\n\n**A)** Half-plane above the dashed line $y=x+2$\n**B)** Half-plane below solid $y=x+2$\n**C)** Only the line $y=x+2$\n**D)** Half-plane above solid $y=x+2$\n\n**Solution:** Strict inequality → dashed boundary; $y$ greater → above.\n**Answer:** A\n\n## Problem 5\nIf $5-x<2$, then\n\n**A)** $x>3$\n**B)** $x<3$\n**C)** $x>7$\n**D)** $x<-3$\n\n**Solution:** $-x<-3$ → $x>3$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: The smallest integer $x$ satisfying $3x+1\\ge 16$ is\n\n*Student-produced response — enter a number.*\n\n**Solution:** $3x\\ge 15$ → $x\\ge 5$; smallest integer is $5$.\n**Answer (SPR):** 5\n\n## Problem 7\nA store requires spending at least 40 dollars for free shipping. If each item costs 8 dollars, how many items $n$ guarantee free shipping?\n\n**A)** $n\\ge 5$\n**B)** $n>5$\n**C)** $n\\ge 4$\n**D)** $n\\le 5$\n\n**Solution:** $8n\\ge 40$ → $n\\ge 5$.\n**Answer:** A\n\n## Problem 8\nThe compound inequality $-2<3x+1\\le 10$ is equivalent to\n\n**A)** $-1<x\\le 3$\n**B)** $-1\\le x<3$\n**C)** $-3<x\\le 3$\n**D)** $0<x\\le 3$\n\n**Solution:** $-3<3x\\le 9$ → $-1<x\\le 3$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Algebra Pack 06: Slope and Rate of Change',
        "content": '# SAT Math · Algebra Pack 06: Slope and Rate of Change\n**Domain:** Algebra\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nThe slope between $(1,4)$ and $(5,12)$ is\n\n**A)** $2$\n**B)** $3$\n**C)** $4$\n**D)** $\\dfrac{1}{2}$\n\n**Solution:** $\\dfrac{12-4}{5-1}=2$.\n**Answer:** A\n\n## Problem 2\nA line through $(0,0)$ and $(6,-3)$ has slope\n\n**A)** $-\\dfrac{1}{2}$\n**B)** $-2$\n**C)** $\\dfrac{1}{2}$\n**D)** $2$\n\n**Solution:** $\\dfrac{-3}{6}=-\\dfrac{1}{2}$.\n**Answer:** A\n\n## Problem 3\nWhich line is parallel to $y=-\\dfrac{3}{4}x+1$?\n\n**A)** $y=-\\dfrac{3}{4}x-5$\n**B)** $y=\\dfrac{4}{3}x$\n**C)** $y=\\dfrac{3}{4}x$\n**D)** $y=-\\dfrac{4}{3}x+2$\n\n**Solution:** Parallel lines share slope $-\\dfrac{3}{4}$.\n**Answer:** A\n\n## Problem 4\nA line perpendicular to $y=2x+7$ has slope\n\n**A)** $-\\dfrac{1}{2}$\n**B)** $2$\n**C)** $-2$\n**D)** $\\dfrac{1}{2}$\n\n**Solution:** Negative reciprocal of $2$ is $-\\dfrac{1}{2}$.\n**Answer:** A\n\n## Problem 5\nDistance increases $15$ miles every $3$ hours at constant speed. Rate of change is\n\n**A)** $5$ mph\n**B)** $15$ mph\n**C)** $3$ mph\n**D)** $45$ mph\n\n**Solution:** $\\dfrac{15}{3}=5$ miles per hour.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Slope from $(-2,5)$ to $(4,5)$ equals\n\n*Student-produced response — enter a number.*\n\n**Solution:** Horizontal line: $m=0$.\n**Answer (SPR):** 0\n\n## Problem 7\nIf a line has slope $0$ and passes through $(3,-2)$, its equation is\n\n**A)** $y=-2$\n**B)** $x=3$\n**C)** $y=3$\n**D)** $x=-2$\n\n**Solution:** Horizontal line through $y=-2$.\n**Answer:** A\n\n## Problem 8\nAverage rate of change of $f(x)=4x-1$ on $[1,3]$ is\n\n**A)** $4$\n**B)** $8$\n**C)** $11$\n**D)** $3$\n\n**Solution:** For linear $f$, AROC equals slope $4$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Algebra Pack 07: Linear Word Problems',
        "content": '# SAT Math · Algebra Pack 07: Linear Word Problems\n**Domain:** Algebra\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nA taxi charges 3 dollars plus 2 dollars per mile. Cost $C$ for $m$ miles is\n\n**A)** $C=2m+3$\n**B)** $C=3m+2$\n**C)** $C=2m-3$\n**D)** $C=5m$\n\n**Solution:** Fixed 3 dollars plus 2 dollars per mile.\n**Answer:** A\n\n## Problem 2\nAfter a 12-dollar discount, a jacket costs 38 dollars. Original price was\n\n**A)** 50 dollars\n**B)** 26 dollars\n**C)** 44 dollars\n**D)** 40 dollars\n\n**Solution:** $38+12=50$.\n**Answer:** A\n\n## Problem 3\nSam has $40$ more pages to read than Jordan. Together they have $180$ pages left. How many does Sam have left?\n\n**A)** $110$\n**B)** $70$\n**C)** $90$\n**D)** $140$\n\n**Solution:** $s=j+40$, $s+j=180$ → $2j+40=180$ → $j=70$, $s=110$.\n**Answer:** A\n\n## Problem 4\nA phone plan is 25 dollars per month plus 0.10 dollars per text. Monthly cost for $120$ texts is\n\n**A)** 37 dollars\n**B)** 35 dollars\n**C)** 45 dollars\n**D)** 30 dollars\n\n**Solution:** $25+0.10(120)=37$.\n**Answer:** A\n\n## Problem 5\nMixing $3$ liters of $20\\%$ solution with $x$ liters of $50\\%$ solution yields $30\\%$ overall. Equation:\n\n**A)** $0.2(3)+0.5x=0.3(3+x)$\n**B)** $0.2+0.5x=0.3$\n**C)** $3(20)+x(50)=30$\n**D)** $0.2(3)+0.5x=0.3x$\n\n**Solution:** Solute balance: $0.6+0.5x=0.3(3+x)$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: A number decreased by $9$ equals $4$ times that number decreased by $30$. Find the number.\n\n*Student-produced response — enter a number.*\n\n**Solution:** $n-9=4n-30$ → $21=3n$ → $n=7$.\n**Answer (SPR):** 7\n\n## Problem 7\nTwo cars leave at the same time; one at $50$ mph, the other at $65$ mph in opposite directions. After $t$ hours they are $230$ miles apart. $t=$\n\n**A)** $2$\n**B)** $3$\n**C)** $1.5$\n**D)** $4$\n\n**Solution:** $(50+65)t=230$ → $115t=230$ → $t=2$.\n**Answer:** A\n\n## Problem 8\nA printer makes $12$ pages/min. How many minutes to print $180$ pages after a $5$-minute warm-up?\n\n**A)** $20$\n**B)** $15$\n**C)** $25$\n**D)** $18$\n\n**Solution:** Print time $180/12=15$; total $15+5=20$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Algebra Pack 08: Interpreting Linear Forms',
        "content": '# SAT Math · Algebra Pack 08: Interpreting Linear Forms\n**Domain:** Algebra\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nIn $y=15x+40$, if $y$ is total dollars and $x$ is hours worked, what does $40$ represent?\n\n**A)** Base pay before hours\n**B)** Hourly wage\n**C)** Hours worked\n**D)** Total pay for $1$ hour\n\n**Solution:** $y$-intercept: pay when $x=0$.\n**Answer:** A\n\n## Problem 2\nEquation $d=55t$ models distance $d$ miles after $t$ hours. Units of $55$?\n\n**A)** miles per hour\n**B)** hours\n**C)** miles\n**D)** hours per mile\n\n**Solution:** Slope is rate: distance/time.\n**Answer:** A\n\n## Problem 3\nRewriting $2x+5y=20$ as $y=-\\dfrac{2}{5}x+4$ shows the slope is\n\n**A)** $-\\dfrac{2}{5}$\n**B)** $\\dfrac{2}{5}$\n**C)** $4$\n**D)** $-2$\n\n**Solution:** Coefficient of $x$ in slope-intercept form.\n**Answer:** A\n\n## Problem 4\nIf $C=0.25n+10$ is cost of $n$ guests, cost per additional guest is\n\n**A)** 0.25 dollars\n**B)** 10 dollars\n**C)** 0.10 dollars\n**D)** 25 dollars\n\n**Solution:** Slope is marginal cost per guest.\n**Answer:** A\n\n## Problem 5\nPoint-slope form through $(2,3)$ with slope $4$ is\n\n**A)** $y-3=4(x-2)$\n**B)** $y-2=4(x-3)$\n**C)** $y=4x-2$\n**D)** $y-3=2(x-4)$\n\n**Solution:** $y-y_1=m(x-x_1)$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: In $y=-6x+18$, the $y$-intercept is\n\n*Student-produced response — enter a number.*\n\n**Solution:** Constant term when $x=0$.\n**Answer (SPR):** 18\n\n## Problem 7\nWhich statement must be true for $f(x)=mx+b$ with $m>0$ and $b<0$?\n\n**A)** The line rises left to right and crosses the $y$-axis below the origin\n**B)** The line falls and crosses above the origin\n**C)** The line is horizontal\n**D)** The line passes through the origin\n\n**Solution:** Positive slope; negative intercept.\n**Answer:** A\n\n## Problem 8\nStandard form $Ax+By=C$ with $A=3$, $B=-1$, $C=6$ has $y$-intercept\n\n**A)** $-6$\n**B)** $6$\n**C)** $2$\n**D)** $-2$\n\n**Solution:** $x=0$ → $-y=6$ → $y=-6$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Algebra Pack 09: Graphs and Tables of Linear Models',
        "content": '# SAT Math · Algebra Pack 09: Graphs and Tables of Linear Models\n**Domain:** Algebra\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nA table shows $x$: $0,1,2$ and $y$: $7,4,1$. The linear equation is\n\n**A)** $y=-3x+7$\n**B)** $y=3x+7$\n**C)** $y=-3x-7$\n**D)** $y=-x+7$\n\n**Solution:** Slope $-3$; intercept $7$.\n**Answer:** A\n\n## Problem 2\nOn a graph, a line crosses the $x$-axis at $4$ and $y$-axis at $-2$. Slope is\n\n**A)** $\\dfrac{1}{2}$\n**B)** $-\\dfrac{1}{2}$\n**C)** $2$\n**D)** $-2$\n\n**Solution:** Points $(4,0)$, $(0,-2)$: $m=\\dfrac{0-(-2)}{4-0}=\\dfrac{1}{2}$.\n**Answer:** A\n\n## Problem 3\nWhich $(x,y)$ is NOT on $y=\\dfrac{1}{3}x-1$?\n\n**A)** $(6,0)$\n**B)** $(3,0)$\n**C)** $(0,-1)$\n**D)** $(9,2)$\n\n**Solution:** For $x=6$: $y=2-1=1\\ne 0$. $(3,0)$ works.\n**Answer:** A\n\n## Problem 4\nIf each increase of $2$ in $x$ decreases $y$ by $5$, slope equals\n\n**A)** $-\\dfrac{5}{2}$\n**B)** $-\\dfrac{2}{5}$\n**C)** $\\dfrac{5}{2}$\n**D)** $5$\n\n**Solution:** $m=\\dfrac{\\Delta y}{\\Delta x}=-\\dfrac{5}{2}$.\n**Answer:** A\n\n## Problem 5\nA scatter of perfect linear points includes $(1,8)$ and $(4,2)$. Predicted $y$ at $x=2$ is\n\n**A)** $6$\n**B)** $5$\n**C)** $4$\n**D)** $7$\n\n**Solution:** $m=\\dfrac{2-8}{4-1}=-2$; $y-8=-2(x-1)$ → at $x=2$, $y=6$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: A line through $(0,12)$ and $(3,0)$ has slope whose absolute value is\n\n*Student-produced response — enter a number.*\n\n**Solution:** $|m|=|\\dfrac{0-12}{3-0}|=4$.\n**Answer (SPR):** 4\n\n## Problem 7\nIf $f$ is linear and $f(2)=10$, $f(5)=19$, then $f(8)=$\n\n**A)** $28$\n**B)** $25$\n**C)** $27$\n**D)** $30$\n\n**Solution:** $m=3$; from $5$ to $8$ add $9$ → $19+9=28$.\n**Answer:** A\n\n## Problem 8\nWhich best describes the graph of $x=5$?\n\n**A)** Vertical line\n**B)** Horizontal line\n**C)** Line with slope $5$\n**D)** Line through origin with slope $5$\n\n**Solution:** $x=$ constant is vertical.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Algebra Pack 10: Mixed Algebra Fluency',
        "content": '# SAT Math · Algebra Pack 10: Mixed Algebra Fluency\n**Domain:** Algebra\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nSolve $4(x+1)=2(x+7)$.\n\n**A)** $x=5$\n**B)** $x=3$\n**C)** $x=10$\n**D)** $x=-5$\n\n**Solution:** $4x+4=2x+14$ → $2x=10$ → $x=5$.\n**Answer:** A\n\n## Problem 2\nSystem $y=x+4$ and $2x+y=13$ has solution $y=$\n\n**A)** $7$\n**B)** $5$\n**C)** $9$\n**D)** $3$\n\n**Solution:** $2x+(x+4)=13$ → $3x=9$ → $x=3$, $y=7$.\n**Answer:** A\n\n## Problem 3\nInequality $1-2x\\ge 9$ simplifies to\n\n**A)** $x\\le -4$\n**B)** $x\\ge -4$\n**C)** $x\\le 4$\n**D)** $x\\ge 4$\n\n**Solution:** $-2x\\ge 8$ → $x\\le -4$.\n**Answer:** A\n\n## Problem 4\nLine through $(-1,2)$ parallel to $y=-4x+1$ has equation\n\n**A)** $y=-4x-2$\n**B)** $y=-4x+2$\n**C)** $y=4x+6$\n**D)** $y=-4x$\n\n**Solution:** $y-2=-4(x+1)$ → $y=-4x-2$.\n**Answer:** A\n\n## Problem 5\nIf $3x+y=10$ and $x-y=2$, then $x+y=$\n\n**A)** $6$\n**B)** $4$\n**C)** $8$\n**D)** $2$\n\n**Solution:** Add: $4x=12$ → $x=3$; then $y=1$; so $x+y=4$.\n**Answer:** B\n\n## Problem 6 (SPR)\nSPR: Solve $5x-3=2x+12$. Enter $x$.\n\n*Student-produced response — enter a number.*\n\n**Solution:** $3x=15$ → $x=5$.\n**Answer (SPR):** 5\n\n## Problem 7\nFunction $f(x)=-\\dfrac{1}{2}x+9$. When $f(x)=0$, $x=$\n\n**A)** $18$\n**B)** $9$\n**C)** $-18$\n**D)** $4.5$\n\n**Solution:** $0=-\\dfrac{1}{2}x+9$ → $x=18$.\n**Answer:** A\n\n## Problem 8\nA gym membership is 30 dollars plus 4 dollars per visit. After $v$ visits the cost equals 70 dollars. Find $v$.\n\n**A)** $10$\n**B)** $8$\n**C)** $15$\n**D)** $12$\n\n**Solution:** $30+4v=70$ → $4v=40$ → $v=10$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Advanced Math Pack 01: Quadratic Equations',
        "content": '# SAT Math · Advanced Math Pack 01: Quadratic Equations\n**Domain:** Advanced Math\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nSolve $x^2-5x+6=0$. The solutions are\n\n**A)** $2$ and $3$\n**B)** $1$ and $6$\n**C)** $-2$ and $-3$\n**D)** $0$ and $5$\n\n**Solution:** $(x-2)(x-3)=0$.\n**Answer:** A\n\n## Problem 2\nThe vertex of $y=(x-3)^2+4$ is\n\n**A)** $(3,4)$\n**B)** $(-3,4)$\n**C)** $(3,-4)$\n**D)** $(0,4)$\n\n**Solution:** Vertex form $(h,k)=(3,4)$.\n**Answer:** A\n\n## Problem 3\nIf $x^2=49$, then $x=$\n\n**A)** $7$ or $-7$\n**B)** $7$ only\n**C)** $-7$ only\n**D)** $49$\n\n**Solution:** Square root yields $\\pm 7$.\n**Answer:** A\n\n## Problem 4\nDiscriminant of $x^2-4x+7=0$ is\n\n**A)** $-12$\n**B)** $12$\n**C)** $4$\n**D)** $0$\n\n**Solution:** $b^2-4ac=16-28=-12$.\n**Answer:** A\n\n## Problem 5\nSum of roots of $2x^2-6x+5=0$ is\n\n**A)** $3$\n**B)** $-3$\n**C)** $\\dfrac{5}{2}$\n**D)** $6$\n\n**Solution:** $-b/a=6/2=3$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: One root of $x^2-9x+18=0$ is $3$. The other root is\n\n*Student-produced response — enter a number.*\n\n**Solution:** $(x-3)(x-6)=0$.\n**Answer (SPR):** 6\n\n## Problem 7\nMinimum value of $f(x)=x^2-8x+10$ is\n\n**A)** $-6$\n**B)** $10$\n**C)** $2$\n**D)** $-8$\n\n**Solution:** Vertex $x=4$; $f(4)=16-32+10=-6$.\n**Answer:** A\n\n## Problem 8\nWhich is equivalent to $(x+4)(x-1)$?\n\n**A)** $x^2+3x-4$\n**B)** $x^2+3x+4$\n**C)** $x^2-3x-4$\n**D)** $x^2+5x-4$\n\n**Solution:** $x^2+3x-4$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Advanced Math Pack 02: Exponential Functions',
        "content": '# SAT Math · Advanced Math Pack 02: Exponential Functions\n**Domain:** Advanced Math\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nIf $f(x)=3\\cdot 2^x$, then $f(3)=$\n\n**A)** $24$\n**B)** $18$\n**C)** $12$\n**D)** $48$\n\n**Solution:** $3\\cdot 8=24$.\n**Answer:** A\n\n## Problem 2\nWhich represents exponential growth?\n\n**A)** $y=5(1.08)^x$\n**B)** $y=5(0.92)^x$\n**C)** $y=5-0.08x$\n**D)** $y=\\dfrac{5}{x}$\n\n**Solution:** Base $>1$ → growth.\n**Answer:** A\n\n## Problem 3\nSolve $2^x=32$.\n\n**A)** $5$\n**B)** $4$\n**C)** $16$\n**D)** $6$\n\n**Solution:** $32=2^5$.\n**Answer:** A\n\n## Problem 4\nIf a population doubles every $4$ years starting at $200$, after $12$ years it is\n\n**A)** $1600$\n**B)** $800$\n**C)** $2400$\n**D)** $1200$\n\n**Solution:** $12/4=3$ doublings: $200\\cdot 2^3=1600$.\n**Answer:** A\n\n## Problem 5\n$\\left(\\dfrac{1}{3}\\right)^x=9$ has solution\n\n**A)** $x=-2$\n**B)** $x=2$\n**C)** $x=-1$\n**D)** $x=3$\n\n**Solution:** $3^{-x}=3^2$ → $-x=2$ → $x=-2$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: If $5\\cdot 3^x=135$, then $x=$\n\n*Student-produced response — enter a number.*\n\n**Solution:** $3^x=27$ → $x=3$.\n**Answer (SPR):** 3\n\n## Problem 7\nAn account starts at 800 dollars and grows by $5\\%$ each year. After $1$ year the balance is\n\n**A)** 840 dollars\n**B)** 805 dollars\n**C)** 850 dollars\n**D)** 760 dollars\n\n**Solution:** $800\\cdot 1.05=840$.\n**Answer:** A\n\n## Problem 8\nWhich expression equals $4^{x+1}$?\n\n**A)** $4\\cdot 4^x$\n**B)** $4^x+1$\n**C)** $4x+4$\n**D)** $(4^x)^1$\n\n**Solution:** $4^{x+1}=4^x\\cdot 4^1$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Advanced Math Pack 03: Polynomial Expressions',
        "content": '# SAT Math · Advanced Math Pack 03: Polynomial Expressions\n**Domain:** Advanced Math\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\n$(2x^3)(5x^2)=$\n\n**A)** $10x^5$\n**B)** $7x^5$\n**C)** $10x^6$\n**D)** $10x$\n\n**Solution:** $2\\cdot5=10$; $x^{3+2}=x^5$.\n**Answer:** A\n\n## Problem 2\nDegree of $4x^5-x^2+7$ is\n\n**A)** $5$\n**B)** $4$\n**C)** $2$\n**D)** $7$\n\n**Solution:** Highest power is $5$.\n**Answer:** A\n\n## Problem 3\nFactor $x^2-16$.\n\n**A)** $(x-4)(x+4)$\n**B)** $(x-8)(x+2)$\n**C)** $(x-4)^2$\n**D)** $x(x-16)$\n\n**Solution:** Difference of squares.\n**Answer:** A\n\n## Problem 4\n$(x+3)^2=$\n\n**A)** $x^2+6x+9$\n**B)** $x^2+9$\n**C)** $x^2+3x+9$\n**D)** $x^2+6x+6$\n\n**Solution:** $(a+b)^2=a^2+2ab+b^2$.\n**Answer:** A\n\n## Problem 5\nSimplify $(3x^2-x)-(x^2+4x)$.\n\n**A)** $2x^2-5x$\n**B)** $2x^2+3x$\n**C)** $4x^2-5x$\n**D)** $2x^2-3x$\n\n**Solution:** $3x^2-x-x^2-4x=2x^2-5x$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: If $p(x)=x^3-2x+1$, find $p(2)$.\n\n*Student-produced response — enter a number.*\n\n**Solution:** $8-4+1=5$.\n**Answer (SPR):** 5\n\n## Problem 7\nWhich is a factor of $x^3-8$?\n\n**A)** $x-2$\n**B)** $x+2$\n**C)** $x-8$\n**D)** $x^2-4$\n\n**Solution:** $a^3-b^3=(a-b)(a^2+ab+b^2)$ with $b=2$.\n**Answer:** A\n\n## Problem 8\nLeading coefficient of $-7x^4+2x^3$ is\n\n**A)** $-7$\n**B)** $7$\n**C)** $2$\n**D)** $-4$\n\n**Solution:** Coefficient of highest degree term.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Advanced Math Pack 04: Rational Equations',
        "content": '# SAT Math · Advanced Math Pack 04: Rational Equations\n**Domain:** Advanced Math\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nSolve $\\dfrac{x}{x-2}=3$ (exclude extraneous).\n\n**A)** $x=3$\n**B)** $x=2$\n**C)** $x=6$\n**D)** $x=1$\n\n**Solution:** $x=3(x-2)$ → $x=3x-6$ → $2x=6$ → $x=3$.\n**Answer:** A\n\n## Problem 2\nSimplify $\\dfrac{6x^2}{2x}$ for $x\\ne 0$.\n\n**A)** $3x$\n**B)** $3x^2$\n**C)** $4x$\n**D)** $12x$\n\n**Solution:** $\\dfrac{6}{2}x^{2-1}=3x$.\n**Answer:** A\n\n## Problem 3\nFor what $x$ is $\\dfrac{1}{x-5}$ undefined?\n\n**A)** $5$\n**B)** $0$\n**C)** $-5$\n**D)** $1$\n\n**Solution:** Denominator zero at $x=5$.\n**Answer:** A\n\n## Problem 4\nSolve $\\dfrac{2}{x}=\\dfrac{5}{x+3}$.\n\n**A)** $x=2$\n**B)** $x=-2$\n**C)** $x=3$\n**D)** $x=5$\n\n**Solution:** $2(x+3)=5x$ → $2x+6=5x$ → $6=3x$ → $x=2$.\n**Answer:** A\n\n## Problem 5\n$\\dfrac{x^2-9}{x+3}=$ for $x\\ne -3$\n\n**A)** $x-3$\n**B)** $x+3$\n**C)** $x^2-3$\n**D)** $x-9$\n\n**Solution:** $(x-3)(x+3)/(x+3)=x-3$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: If $\\dfrac{12}{x}=4$, then $x=$\n\n*Student-produced response — enter a number.*\n\n**Solution:** $x=12/4=3$.\n**Answer (SPR):** 3\n\n## Problem 7\nWhich expression equals $\\dfrac{1}{x}+\\dfrac{1}{2}$?\n\n**A)** $\\dfrac{2+x}{2x}$\n**B)** $\\dfrac{1+x}{2x}$\n**C)** $\\dfrac{3}{x}$\n**D)** $\\dfrac{1}{2x}$\n\n**Solution:** Common denominator $2x$: $\\dfrac{2+x}{2x}$.\n**Answer:** A\n\n## Problem 8\nSolve $\\dfrac{x+1}{4}=\\dfrac{x-1}{2}$.\n\n**A)** $x=3$\n**B)** $x=-3$\n**C)** $x=1$\n**D)** $x=5$\n\n**Solution:** $2(x+1)=4(x-1)$ → $2x+2=4x-4$ → $6=2x$ → $x=3$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Advanced Math Pack 05: Radical Equations',
        "content": '# SAT Math · Advanced Math Pack 05: Radical Equations\n**Domain:** Advanced Math\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nSolve $\\sqrt{x}=7$.\n\n**A)** $49$\n**B)** $7$\n**C)** $14$\n**D)** $\\sqrt{7}$\n\n**Solution:** Square both sides: $x=49$.\n**Answer:** A\n\n## Problem 2\n$\\sqrt{36}+\\sqrt{16}=$\n\n**A)** $10$\n**B)** $52$\n**C)** $6$\n**D)** $\\sqrt{52}$\n\n**Solution:** $6+4=10$.\n**Answer:** A\n\n## Problem 3\nSolve $\\sqrt{2x+1}=5$.\n\n**A)** $x=12$\n**B)** $x=24$\n**C)** $x=13$\n**D)** $x=2$\n\n**Solution:** $2x+1=25$ → $2x=24$ → $x=12$.\n**Answer:** A\n\n## Problem 4\nSimplify $\\sqrt{50}$.\n\n**A)** $5\\sqrt{2}$\n**B)** $25\\sqrt{2}$\n**C)** $10\\sqrt{5}$\n**D)** $2\\sqrt{5}$\n\n**Solution:** $\\sqrt{25\\cdot 2}=5\\sqrt{2}$.\n**Answer:** A\n\n## Problem 5\nWhich is equivalent to $x^{1/2}\\cdot x^{3/2}$?\n\n**A)** $x^2$\n**B)** $x$\n**C)** $x^{3/4}$\n**D)** $x^{1/2}$\n\n**Solution:** Add exponents: $1/2+3/2=2$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: If $\\sqrt{x+5}=4$, then $x=$\n\n*Student-produced response — enter a number.*\n\n**Solution:** $x+5=16$ → $x=11$.\n**Answer (SPR):** 11\n\n## Problem 7\nSolve $\\sqrt{x}=-3$.\n\n**A)** No real solution\n**B)** $x=9$\n**C)** $x=-9$\n**D)** $x=3$\n\n**Solution:** Principal square root is nonnegative.\n**Answer:** A\n\n## Problem 8\n$(\\sqrt{x})^2$ for $x\\ge 0$ equals\n\n**A)** $x$\n**B)** $\\sqrt{x}$\n**C)** $x^2$\n**D)** $|x|$ only if negative\n\n**Solution:** By definition for $x\\ge 0$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Advanced Math Pack 06: Nonlinear Systems',
        "content": '# SAT Math · Advanced Math Pack 06: Nonlinear Systems\n**Domain:** Advanced Math\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nSolutions to $y=x^2$ and $y=4$ are $x=$\n\n**A)** $2$ and $-2$\n**B)** $4$ only\n**C)** $0$ and $4$\n**D)** $2$ only\n\n**Solution:** $x^2=4$ → $x=\\pm 2$.\n**Answer:** A\n\n## Problem 2\nIntersection of $y=x^2-1$ and $y=x+1$: solve $x^2-1=x+1$. Then $x=$\n\n**A)** $2$ or $-1$\n**B)** $1$ or $-2$\n**C)** $0$ or $1$\n**D)** $3$ or $-1$\n\n**Solution:** $x^2-x-2=0$ → $(x-2)(x+1)=0$.\n**Answer:** A\n\n## Problem 3\nHow many real solutions does $y=x^2+1$ and $y=-x$ have?\n\n**A)** $0$\n**B)** $1$\n**C)** $2$\n**D)** $3$\n\n**Solution:** $x^2+x+1=0$ has discriminant $1-4=-3$.\n**Answer:** A\n\n## Problem 4\nIf $x+y=5$ and $xy=6$, then $x^2+y^2=$\n\n**A)** $13$\n**B)** $25$\n**C)** $11$\n**D)** $31$\n\n**Solution:** $(x+y)^2-2xy=25-12=13$.\n**Answer:** A\n\n## Problem 5\nSystem $y=2^x$ and $y=8$ meets at $x=$\n\n**A)** $3$\n**B)** $2$\n**C)** $4$\n**D)** $8$\n\n**Solution:** $2^x=8=2^3$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: For $y=x^2$ and $y=9x$, a positive solution for $x$ is\n\n*Student-produced response — enter a number.*\n\n**Solution:** $x^2=9x$ → $x(x-9)=0$; positive is $9$.\n**Answer (SPR):** 9\n\n## Problem 7\nThe circle $x^2+y^2=25$ and line $y=0$ intersect at how many points?\n\n**A)** $2$\n**B)** $1$\n**C)** $0$\n**D)** $4$\n\n**Solution:** $x=\\pm 5$ on the $x$-axis.\n**Answer:** A\n\n## Problem 8\nIf $y=x^2$ and $x+y=12$, then a possible $x$ is\n\n**A)** $3$\n**B)** $4$\n**C)** $6$\n**D)** $2$\n\n**Solution:** $x+x^2=12$ → $x^2+x-12=0$ → $(x+4)(x-3)=0$; $x=3$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Advanced Math Pack 07: Equivalent Expressions',
        "content": '# SAT Math · Advanced Math Pack 07: Equivalent Expressions\n**Domain:** Advanced Math\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nWhich is equivalent to $3(x-4)+2$?\n\n**A)** $3x-10$\n**B)** $3x-12$\n**C)** $3x-2$\n**D)** $3x+2$\n\n**Solution:** $3x-12+2=3x-10$.\n**Answer:** A\n\n## Problem 2\n$(2x-5)(x+3)=$\n\n**A)** $2x^2+x-15$\n**B)** $2x^2+6x-15$\n**C)** $2x^2-x-15$\n**D)** $2x^2+x+15$\n\n**Solution:** $2x^2+6x-5x-15=2x^2+x-15$.\n**Answer:** A\n\n## Problem 3\nFactor $6x+9$.\n\n**A)** $3(2x+3)$\n**B)** $6(x+9)$\n**C)** $3(2x+9)$\n**D)** $2(3x+9)$\n\n**Solution:** GCF $3$.\n**Answer:** A\n\n## Problem 4\n$\\dfrac{4x^3y}{2xy}=$ for $x,y\\ne 0$\n\n**A)** $2x^2$\n**B)** $2xy$\n**C)** $2x^2y$\n**D)** $4x^2$\n\n**Solution:** $\\dfrac{4}{2}x^{3-1}y^{1-1}=2x^2$.\n**Answer:** A\n\n## Problem 5\nWhich equals $(a+b)^2-(a-b)^2$?\n\n**A)** $4ab$\n**B)** $2ab$\n**C)** $a^2+b^2$\n**D)** $0$\n\n**Solution:** $(a^2+2ab+b^2)-(a^2-2ab+b^2)=4ab$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Evaluate $2(5)-3(5)+1$ using $x=5$ in $2x-3x+1$. Result:\n\n*Student-produced response — enter a number.*\n\n**Solution:** $-x+1=-5+1=-4$.\n**Answer (SPR):** -4\n\n## Problem 7\nRewrite $x^2+10x+25$ as\n\n**A)** $(x+5)^2$\n**B)** $(x+10)^2$\n**C)** $(x+5)(x+10)$\n**D)** $(x-5)^2$\n\n**Solution:** Perfect square trinomial.\n**Answer:** A\n\n## Problem 8\n$\\dfrac{x}{5}+\\dfrac{x}{10}=$\n\n**A)** $\\dfrac{3x}{10}$\n**B)** $\\dfrac{2x}{15}$\n**C)** $\\dfrac{x}{15}$\n**D)** $\\dfrac{3x}{5}$\n\n**Solution:** $\\dfrac{2x+x}{10}=\\dfrac{3x}{10}$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Advanced Math Pack 08: Absolute Value Equations',
        "content": '# SAT Math · Advanced Math Pack 08: Absolute Value Equations\n**Domain:** Advanced Math\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nSolve $|x|=6$.\n\n**A)** $x=6$ or $x=-6$\n**B)** $x=6$ only\n**C)** $x=-6$ only\n**D)** No solution\n\n**Solution:** Definition of absolute value.\n**Answer:** A\n\n## Problem 2\n$|3x-1|=8$ has solutions\n\n**A)** $x=3$ and $x=-\\dfrac{7}{3}$\n**B)** $x=3$ only\n**C)** $x=\\dfrac{7}{3}$ and $-3$\n**D)** $x=9$ and $-7$\n\n**Solution:** $3x-1=8$ → $x=3$; $3x-1=-8$ → $x=-7/3$.\n**Answer:** A\n\n## Problem 3\n$|x|+4=1$ has\n\n**A)** No real solution\n**B)** $x=-3$\n**C)** $x=3$\n**D)** $x=-5$\n\n**Solution:** $|x|=-3$ impossible.\n**Answer:** A\n\n## Problem 4\nWhich is true for all real $x$?\n\n**A)** $|x|\\ge 0$\n**B)** $|x|>0$\n**C)** $|x|=x$\n**D)** $|x|=-x$\n\n**Solution:** Absolute value is nonnegative.\n**Answer:** A\n\n## Problem 5\nDistance between $-2$ and $7$ on the number line is\n\n**A)** $9$\n**B)** $5$\n**C)** $-9$\n**D)** $14$\n\n**Solution:** $|7-(-2)|=9$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: If $|x-4|=0$, then $x=$\n\n*Student-produced response — enter a number.*\n\n**Solution:** Only when inside is $0$.\n**Answer (SPR):** 4\n\n## Problem 7\nSolve $|2x|=10$. Positive solution is\n\n**A)** $5$\n**B)** $10$\n**C)** $-5$\n**D)** $20$\n\n**Solution:** $2x=\\pm 10$; positive $x=5$.\n**Answer:** A\n\n## Problem 8\nThe graph of $y=|x-2|$ has vertex at\n\n**A)** $(2,0)$\n**B)** $(0,2)$\n**C)** $(-2,0)$\n**D)** $(2,2)$\n\n**Solution:** V-shape centered at $x=2$, $y=0$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Advanced Math Pack 09: Nonlinear Functions',
        "content": '# SAT Math · Advanced Math Pack 09: Nonlinear Functions\n**Domain:** Advanced Math\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nIf $f(x)=x^2-3x$, then $f(-2)=$\n\n**A)** $10$\n**B)** $-10$\n**C)** $2$\n**D)** $-2$\n\n**Solution:** $4-3(-2)=4+6=10$.\n**Answer:** A\n\n## Problem 2\nAs $x\\to\\infty$, $g(x)=(0.5)^x$ approaches\n\n**A)** $0$\n**B)** $\\infty$\n**C)** $0.5$\n**D)** $1$\n\n**Solution:** Exponential decay → $0$.\n**Answer:** A\n\n## Problem 3\nDomain of $h(x)=\\sqrt{x-4}$ is\n\n**A)** $x\\ge 4$\n**B)** $x>4$\n**C)** $x\\le 4$\n**D)** all real $x$\n\n**Solution:** Radicand nonnegative.\n**Answer:** A\n\n## Problem 4\nIf $f(x)=2x+1$ and $g(x)=x^2$, then $(g\\circ f)(2)=$\n\n**A)** $25$\n**B)** $9$\n**C)** $10$\n**D)** $5$\n\n**Solution:** $f(2)=5$; $g(5)=25$.\n**Answer:** A\n\n## Problem 5\nZeros of $p(x)=(x-1)(x+5)$ are\n\n**A)** $1$ and $-5$\n**B)** $-1$ and $5$\n**C)** $1$ and $5$\n**D)** $0$ and $-5$\n\n**Solution:** Set each factor to $0$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: For $f(x)=x^2$, find $f(6)-f(4)$.\n\n*Student-produced response — enter a number.*\n\n**Solution:** $36-16=20$.\n**Answer (SPR):** 20\n\n## Problem 7\nWhich function is even?\n\n**A)** $f(x)=x^2+1$\n**B)** $f(x)=x^3$\n**C)** $f(x)=x+1$\n**D)** $f(x)=2^x$\n\n**Solution:** $f(-x)=f(x)$ for even functions.\n**Answer:** A\n\n## Problem 8\nVertical shift of $y=x^2$ up by $3$ yields\n\n**A)** $y=x^2+3$\n**B)** $y=(x+3)^2$\n**C)** $y=3x^2$\n**D)** $y=x^2-3$\n\n**Solution:** Add constant outside.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Advanced Math Pack 10: Mixed Advanced Math',
        "content": '# SAT Math · Advanced Math Pack 10: Mixed Advanced Math\n**Domain:** Advanced Math\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nSolve $x^2+x-12=0$. Positive root is\n\n**A)** $3$\n**B)** $4$\n**C)** $2$\n**D)** $6$\n\n**Solution:** $(x+4)(x-3)=0$ → $x=3$.\n**Answer:** A\n\n## Problem 2\nIf $y=3^{x}$, then $y$ when $x=0$ is\n\n**A)** $1$\n**B)** $0$\n**C)** $3$\n**D)** undefined\n\n**Solution:** Any nonzero number to power $0$ is $1$.\n**Answer:** A\n\n## Problem 3\n$\\dfrac{x^2-1}{x-1}$ for $x\\ne 1$ equals\n\n**A)** $x+1$\n**B)** $x-1$\n**C)** $x$\n**D)** $1$\n\n**Solution:** $(x-1)(x+1)/(x-1)$.\n**Answer:** A\n\n## Problem 4\nProduct of roots of $x^2-5x+6=0$ is\n\n**A)** $6$\n**B)** $5$\n**C)** $-6$\n**D)** $1$\n\n**Solution:** $c/a=6$.\n**Answer:** A\n\n## Problem 5\n$|2x+1|=5$ and $x>0$ gives $x=$\n\n**A)** $2$\n**B)** $-3$\n**C)** $3$\n**D)** $\\dfrac{5}{2}$\n\n**Solution:** $2x+1=5$ → $x=2$ (the positive case).\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Evaluate $(3^2)(2^3)$.\n\n*Student-produced response — enter a number.*\n\n**Solution:** $9\\cdot 8=72$.\n**Answer (SPR):** 72\n\n## Problem 7\nVertex of $y=-2(x+1)^2+7$ is\n\n**A)** $(-1,7)$\n**B)** $(1,7)$\n**C)** $(-1,-7)$\n**D)** $(1,-7)$\n\n**Solution:** $(h,k)=(-1,7)$.\n**Answer:** A\n\n## Problem 8\nSolve $\\sqrt{3x}=6$.\n\n**A)** $x=12$\n**B)** $x=2$\n**C)** $x=36$\n**D)** $x=4$\n\n**Solution:** $3x=36$ → $x=12$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Problem-Solving and Data Analysis Pack 01: Ratios and Proportions',
        "content": '# SAT Math · Problem-Solving and Data Analysis Pack 01: Ratios and Proportions\n**Domain:** Problem-Solving and Data Analysis\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nThe ratio of girls to boys in a club is $3:2$. If there are $30$ students, how many are girls?\n\n**A)** $18$\n**B)** $12$\n**C)** $15$\n**D)** $20$\n\n**Solution:** $3/5$ of $30=18$.\n**Answer:** A\n\n## Problem 2\nIf $\\dfrac{a}{b}=\\dfrac{4}{5}$ and $b=20$, then $a=$\n\n**A)** $16$\n**B)** $25$\n**C)** $15$\n**D)** $10$\n\n**Solution:** $a=\\dfrac{4}{5}\\cdot 20=16$.\n**Answer:** A\n\n## Problem 3\nA map scale is $1$ inch : $40$ miles. $2.5$ inches represent\n\n**A)** $100$ miles\n**B)** $80$ miles\n**C)** $60$ miles\n**D)** $120$ miles\n\n**Solution:** $2.5\\times 40=100$.\n**Answer:** A\n\n## Problem 4\nSolve $\\dfrac{x}{12}=\\dfrac{5}{8}$.\n\n**A)** $x=7.5$\n**B)** $x=8$\n**C)** $x=6$\n**D)** $x=15$\n\n**Solution:** $8x=60$ → $x=7.5$.\n**Answer:** A\n\n## Problem 5\nRecipe uses $2$ cups flour for $3$ cups sugar. For $9$ cups sugar, flour needed is\n\n**A)** $6$ cups\n**B)** $4$ cups\n**C)** $5$ cups\n**D)** $8$ cups\n\n**Solution:** $\\dfrac{2}{3}=\\dfrac{f}{9}$ → $f=6$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: If $5$ workers finish a job in $12$ days at constant rate, days for $10$ workers (same job) is\n\n*Student-produced response — enter a number.*\n\n**Solution:** Work proportional to workers times days; double workers → half days.\n**Answer (SPR):** 6\n\n## Problem 7\nIn a bag, red:blue marbles $=5:7$. Total $48$ marbles. Blue count is\n\n**A)** $28$\n**B)** $20$\n**C)** $24$\n**D)** $30$\n\n**Solution:** $7/12$ of $48=28$.\n**Answer:** A\n\n## Problem 8\nWhich pair is proportional to $6:9$?\n\n**A)** $8:12$\n**B)** $4:8$\n**C)** $6:8$\n**D)** $2:9$\n\n**Solution:** $6/9=2/3$ and $8/12=2/3$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Problem-Solving and Data Analysis Pack 02: Percentages',
        "content": '# SAT Math · Problem-Solving and Data Analysis Pack 02: Percentages\n**Domain:** Problem-Solving and Data Analysis\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\n$30\\%$ of $80$ is\n\n**A)** $24$\n**B)** $30$\n**C)** $56$\n**D)** $18$\n\n**Solution:** $0.3\\times 80=24$.\n**Answer:** A\n\n## Problem 2\nA 50-dollar shirt is discounted $20\\%$. Sale price is\n\n**A)** 40 dollars\n**B)** 30 dollars\n**C)** 45 dollars\n**D)** 10 dollars\n\n**Solution:** $50\\times 0.8=40$.\n**Answer:** A\n\n## Problem 3\nIncrease from $40$ to $50$ is what percent increase?\n\n**A)** $25\\%$\n**B)** $20\\%$\n**C)** $10\\%$\n**D)** $125\\%$\n\n**Solution:** $\\dfrac{10}{40}=0.25$.\n**Answer:** A\n\n## Problem 4\nIf a value increases by $10\\%$ then decreases by $10\\%$, final relative to original is\n\n**A)** $99\\%$\n**B)** $100\\%$\n**C)** $90\\%$\n**D)** $110\\%$\n\n**Solution:** $1.1\\times 0.9=0.99$.\n**Answer:** A\n\n## Problem 5\nWhat percent of $200$ is $50$?\n\n**A)** $25\\%$\n**B)** $50\\%$\n**C)** $4\\%$\n**D)** $40\\%$\n\n**Solution:** $50/200=0.25$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: $15\\%$ of a number is $45$. The number is\n\n*Student-produced response — enter a number.*\n\n**Solution:** $0.15n=45$ → $n=300$.\n**Answer (SPR):** 300\n\n## Problem 7\nTax of $8\\%$ on a 25-dollar purchase adds\n\n**A)** 2 dollars\n**B)** 8 dollars\n**C)** 1.50 dollars\n**D)** 2.50 dollars\n\n**Solution:** $0.08\\times 25=2$.\n**Answer:** A\n\n## Problem 8\nA population grows from $800$ to $960$. Percent growth is\n\n**A)** $20\\%$\n**B)** $16\\%$\n**C)** $160\\%$\n**D)** $12\\%$\n\n**Solution:** $160/800=0.20$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Problem-Solving and Data Analysis Pack 03: Rates and Units',
        "content": '# SAT Math · Problem-Solving and Data Analysis Pack 03: Rates and Units\n**Domain:** Problem-Solving and Data Analysis\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nA car travels $150$ miles in $3$ hours. Average speed is\n\n**A)** $50$ mph\n**B)** $45$ mph\n**C)** $150$ mph\n**D)** $30$ mph\n\n**Solution:** $150/3=50$.\n**Answer:** A\n\n## Problem 2\nConvert $2.5$ hours to minutes.\n\n**A)** $150$\n**B)** $120$\n**C)** $90$\n**D)** $250$\n\n**Solution:** $2.5\\times 60=150$.\n**Answer:** A\n\n## Problem 3\nA machine makes $40$ parts/hour. In $2.5$ hours it makes\n\n**A)** $100$\n**B)** $80$\n**C)** $90$\n**D)** $120$\n\n**Solution:** $40\\times 2.5=100$.\n**Answer:** A\n\n## Problem 4\nUnit price: 12 dollars for $3$ pounds. Cost per pound is\n\n**A)** 4 dollars\n**B)** 3 dollars\n**C)** 9 dollars\n**D)** 36 dollars\n\n**Solution:** $12/3=4$.\n**Answer:** A\n\n## Problem 5\n$60$ km/h equals how many km in $20$ minutes?\n\n**A)** $20$\n**B)** $30$\n**C)** $15$\n**D)** $12$\n\n**Solution:** $20$ min $=1/3$ h; $60/3=20$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: At $8$ pages per minute, minutes to print $96$ pages:\n\n*Student-produced response — enter a number.*\n\n**Solution:** $96/8=12$.\n**Answer (SPR):** 12\n\n## Problem 7\nDensity is $5$ g/cm$^3$. Mass of $12$ cm$^3$ is\n\n**A)** $60$ g\n**B)** $2.4$ g\n**C)** $17$ g\n**D)** $0.4$ g\n\n**Solution:** $5\\times 12=60$.\n**Answer:** A\n\n## Problem 8\nWhich rate is greatest?\n\n**A)** $30$ miles in $20$ minutes\n**B)** $60$ mph\n**C)** $2$ miles per minute\n**D)** $90$ miles in $2$ hours\n\n**Solution:** $2$ mi/min $=120$ mph; first option is $90$ mph; $60$ mph; last is $45$ mph.\n**Answer:** C\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Problem-Solving and Data Analysis Pack 04: One-Variable Data',
        "content": '# SAT Math · Problem-Solving and Data Analysis Pack 04: One-Variable Data\n**Domain:** Problem-Solving and Data Analysis\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nData set: $2,4,4,6,9$. The median is\n\n**A)** $4$\n**B)** $5$\n**C)** $6$\n**D)** $2$\n\n**Solution:** Middle value of ordered list is $4$.\n**Answer:** A\n\n## Problem 2\nMean of $3,5,7,9$ is\n\n**A)** $6$\n**B)** $5$\n**C)** $7$\n**D)** $8$\n\n**Solution:** $24/4=6$.\n**Answer:** A\n\n## Problem 3\nRange of $11,3,8,20,5$ is\n\n**A)** $17$\n**B)** $15$\n**C)** $8$\n**D)** $20$\n\n**Solution:** $20-3=17$.\n**Answer:** A\n\n## Problem 4\nMode of $1,2,2,2,3,4$ is\n\n**A)** $2$\n**B)** $1$\n**C)** $3$\n**D)** $4$\n\n**Solution:** Most frequent value.\n**Answer:** A\n\n## Problem 5\nIf every value in a data set increases by $5$, the mean\n\n**A)** Increases by $5$\n**B)** Stays the same\n**C)** Increases by $5\\%$\n**D)** Is multiplied by $5$\n\n**Solution:** Adding constant shifts mean by that constant.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Mean of $10,10,10,14$ is\n\n*Student-produced response — enter a number.*\n\n**Solution:** $44/4=11$.\n**Answer (SPR):** 11\n\n## Problem 7\nWhich measure is most affected by a single extreme outlier?\n\n**A)** Mean\n**B)** Median\n**C)** Mode\n**D)** Middle value of sorted list\n\n**Solution:** Mean uses all values including extremes.\n**Answer:** A\n\n## Problem 8\nFive test scores average $80$. Four scores are $70,85,90,75$. The fifth score is\n\n**A)** $80$\n**B)** $85$\n**C)** $75$\n**D)** $90$\n\n**Solution:** Total $400$; known sum $320$; fifth $=80$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Problem-Solving and Data Analysis Pack 05: Scatterplots and Models',
        "content": '# SAT Math · Problem-Solving and Data Analysis Pack 05: Scatterplots and Models\n**Domain:** Problem-Solving and Data Analysis\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nA scatterplot shows a strong negative linear association. Slope of the best-fit line is\n\n**A)** Negative\n**B)** Positive\n**C)** Zero\n**D)** Undefined\n\n**Solution:** Negative association → negative slope.\n**Answer:** A\n\n## Problem 2\nIf the line of best fit is $y=2.5x+10$, predicted $y$ when $x=4$ is\n\n**A)** $20$\n**B)** $12.5$\n**C)** $40$\n**D)** $14$\n\n**Solution:** $2.5(4)+10=20$.\n**Answer:** A\n\n## Problem 3\nResidual $=$ observed $y$ minus predicted $y$. If observed $=18$ and predicted $=15$, residual is\n\n**A)** $3$\n**B)** $-3$\n**C)** $15$\n**D)** $18$\n\n**Solution:** $18-15=3$.\n**Answer:** A\n\n## Problem 4\nWhich model fits exponential growth better than linear?\n\n**A)** Population doubling each period\n**B)** Constant increase of $5$ each period\n**C)** Random scatter\n**D)** Decreasing by $2$ each time\n\n**Solution:** Multiplicative growth is exponential.\n**Answer:** A\n\n## Problem 5\nCorrelation close to $0$ suggests\n\n**A)** Little linear association\n**B)** Strong positive linear association\n**C)** Strong negative linear association\n**D)** Perfect fit\n\n**Solution:** $r\\approx 0$ means weak linear relationship.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Best-fit line $y=-3x+21$. When $x=5$, predicted $y=$\n\n*Student-produced response — enter a number.*\n\n**Solution:** $-15+21=6$.\n**Answer (SPR):** 6\n\n## Problem 7\nExtrapolation means\n\n**A)** Predicting outside the data range\n**B)** Predicting within the data range\n**C)** Computing the mean only\n**D)** Ignoring outliers always\n\n**Solution:** Extrapolation is outside observed $x$.\n**Answer:** A\n\n## Problem 8\nIf points closely follow $y=mx+b$ with $m>0$, association is\n\n**A)** Positive linear\n**B)** Negative linear\n**C)** Nonlinear only\n**D)** None\n\n**Solution:** Positive slope → positive association.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Problem-Solving and Data Analysis Pack 06: Probability',
        "content": '# SAT Math · Problem-Solving and Data Analysis Pack 06: Probability\n**Domain:** Problem-Solving and Data Analysis\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nA fair die is rolled. $P(\\text{even})=$\n\n**A)** $\\dfrac{1}{2}$\n**B)** $\\dfrac{1}{3}$\n**C)** $\\dfrac{1}{6}$\n**D)** $\\dfrac{2}{3}$\n\n**Solution:** Even faces $2,4,6$ → $3/6$.\n**Answer:** A\n\n## Problem 2\nBag has $3$ red and $7$ blue marbles. $P(\\text{red})=$\n\n**A)** $\\dfrac{3}{10}$\n**B)** $\\dfrac{3}{7}$\n**C)** $\\dfrac{7}{10}$\n**D)** $\\dfrac{1}{3}$\n\n**Solution:** $3$ of $10$.\n**Answer:** A\n\n## Problem 3\nTwo fair coins flipped. $P(\\text{two heads})=$\n\n**A)** $\\dfrac{1}{4}$\n**B)** $\\dfrac{1}{2}$\n**C)** $\\dfrac{1}{3}$\n**D)** $\\dfrac{3}{4}$\n\n**Solution:** HH among HH,HT,TH,TT.\n**Answer:** A\n\n## Problem 4\nA spinner has $4$ equal sectors labeled A–D. $P(\\text{not A})=$\n\n**A)** $\\dfrac{3}{4}$\n**B)** $\\dfrac{1}{4}$\n**C)** $1$\n**D)** $\\dfrac{1}{2}$\n\n**Solution:** $1-1/4=3/4$.\n**Answer:** A\n\n## Problem 5\nIndependent events $A,B$ with $P(A)=0.2$, $P(B)=0.5$. $P(A\\text{ and }B)=$\n\n**A)** $0.1$\n**B)** $0.7$\n**C)** $0.3$\n**D)** $0.4$\n\n**Solution:** $0.2\\times 0.5=0.1$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: A card is drawn from $52$. Number of aces is $4$. Probability of ace as a percent (nearest whole) is about\n\n*Student-produced response — enter a number.*\n\n**Solution:** $4/52\\approx 0.0769\\approx 8\\%$.\n**Answer (SPR):** 8\n\n## Problem 7\nIf $P(E)=0.35$, then $P(\\text{not }E)=$\n\n**A)** $0.65$\n**B)** $0.35$\n**C)** $1.35$\n**D)** $0$\n\n**Solution:** $1-0.35=0.65$.\n**Answer:** A\n\n## Problem 8\nFrom numbers $\\{1,2,3,4,5\\}$, $P(\\text{prime})=$\n\n**A)** $\\dfrac{3}{5}$\n**B)** $\\dfrac{2}{5}$\n**C)** $\\dfrac{4}{5}$\n**D)** $\\dfrac{1}{5}$\n\n**Solution:** Primes $2,3,5$ → $3/5$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Problem-Solving and Data Analysis Pack 07: Conditional Probability',
        "content": '# SAT Math · Problem-Solving and Data Analysis Pack 07: Conditional Probability\n**Domain:** Problem-Solving and Data Analysis\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nIn a class of $40$, $22$ play soccer and $10$ of those also play basketball. Given soccer, $P(\\text{basketball})=$\n\n**A)** $\\dfrac{10}{22}$\n**B)** $\\dfrac{10}{40}$\n**C)** $\\dfrac{22}{40}$\n**D)** $\\dfrac{10}{12}$\n\n**Solution:** Condition on soccer players only.\n**Answer:** A\n\n## Problem 2\nTable: Pass $30$, Fail $10$. Of those who studied ($25$), $20$ passed. $P(\\text{pass}|\\text{studied})=$\n\n**A)** $\\dfrac{20}{25}$\n**B)** $\\dfrac{20}{30}$\n**C)** $\\dfrac{25}{40}$\n**D)** $\\dfrac{20}{40}$\n\n**Solution:** $20$ of $25$ who studied.\n**Answer:** A\n\n## Problem 3\nIf $P(A)=0.4$, $P(A\\text{ and }B)=0.1$, then $P(B|A)=$\n\n**A)** $0.25$\n**B)** $0.1$\n**C)** $0.4$\n**D)** $0.5$\n\n**Solution:** $P(B|A)=0.1/0.4=0.25$.\n**Answer:** A\n\n## Problem 4\nA jar has $4$ green and $6$ yellow. One green is removed. $P(\\text{second is green})=$\n\n**A)** $\\dfrac{3}{9}$\n**B)** $\\dfrac{4}{10}$\n**C)** $\\dfrac{4}{9}$\n**D)** $\\dfrac{3}{10}$\n\n**Solution:** $3$ green left of $9$.\n**Answer:** A\n\n## Problem 5\nAmong $100$ people, $60$ like tea, $40$ like coffee, $25$ like both. $P(\\text{coffee}|\\text{tea})=$\n\n**A)** $\\dfrac{25}{60}$\n**B)** $\\dfrac{25}{40}$\n**C)** $\\dfrac{25}{100}$\n**D)** $\\dfrac{40}{60}$\n\n**Solution:** $25$ of $60$ tea drinkers also like coffee.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: $P(A)=0.5$, $P(A\\text{ and }B)=0.2$. Enter $P(B|A)$ as a decimal.\n\n*Student-produced response — enter a number.*\n\n**Solution:** $0.2/0.5=0.4$.\n**Answer (SPR):** 0.4\n\n## Problem 7\nSelecting without replacement, two cards from $5$ red and $5$ black. $P(\\text{both red})=$\n\n**A)** $\\dfrac{5}{10}\\cdot\\dfrac{4}{9}$\n**B)** $\\dfrac{5}{10}\\cdot\\dfrac{5}{10}$\n**C)** $\\dfrac{5}{10}\\cdot\\dfrac{4}{10}$\n**D)** $\\dfrac{1}{2}$\n\n**Solution:** Without replacement reduces count.\n**Answer:** A\n\n## Problem 8\nIf events are independent, $P(A|B)$ equals\n\n**A)** $P(A)$\n**B)** $P(B)$\n**C)** $P(A\\text{ and }B)$\n**D)** $1$\n\n**Solution:** Independence: conditioning on $B$ does not change $P(A)$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Problem-Solving and Data Analysis Pack 08: Samples and Margin of Error',
        "content": "# SAT Math · Problem-Solving and Data Analysis Pack 08: Samples and Margin of Error\n**Domain:** Problem-Solving and Data Analysis\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nA random sample of $200$ voters finds $110$ support a measure. Estimated support is\n\n**A)** $55\\%$\n**B)** $110\\%$\n**C)** $45\\%$\n**D)** $200\\%$\n\n**Solution:** $110/200=0.55$.\n**Answer:** A\n\n## Problem 2\nLarger random samples generally produce\n\n**A)** Smaller margin of error\n**B)** Larger margin of error\n**C)** Biased results always\n**D)** No change in precision\n\n**Solution:** More data → typically tighter estimates.\n**Answer:** A\n\n## Problem 3\nMargin of error $\\pm 3\\%$ around $52\\%$ means a plausible interval is\n\n**A)** $49\\%$ to $55\\%$\n**B)** $52\\%$ to $55\\%$\n**C)** $3\\%$ to $52\\%$\n**D)** $49\\%$ to $52\\%$\n\n**Solution:** $52\\pm 3$.\n**Answer:** A\n\n## Problem 4\nA survey of only online gamers about all teens' screen time is likely\n\n**A)** Biased\n**B)** Unbiased\n**C)** A census\n**D)** Without sampling error\n\n**Solution:** Sample not representative of all teens.\n**Answer:** A\n\n## Problem 5\nPopulation mean is unknown; sample mean estimates it. This is\n\n**A)** Inference from a sample\n**B)** A controlled experiment\n**C)** Proof of causation\n**D)** A parameter by definition\n\n**Solution:** Sample statistics estimate population parameters.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Sample proportion $0.40$ with margin of error $0.05$. Upper end of interval as a percent:\n\n*Student-produced response — enter a number.*\n\n**Solution:** $0.40+0.05=0.45$ → $45\\%$.\n**Answer (SPR):** 45\n\n## Problem 7\nDoubling sample size, all else equal, tends to make the estimate\n\n**A)** More precise\n**B)** Exactly twice as large\n**C)** Biased upward\n**D)** A parameter\n\n**Solution:** Precision improves with sample size.\n**Answer:** A\n\n## Problem 8\nWhich improves generalizability to a city population?\n\n**A)** Simple random sample of city residents\n**B)** Volunteers at one mall\n**C)** Friends of the researcher\n**D)** Only people who email back\n\n**Solution:** Random sampling reduces selection bias.\n**Answer:** A\n",
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Problem-Solving and Data Analysis Pack 09: Statistical Claims',
        "content": '# SAT Math · Problem-Solving and Data Analysis Pack 09: Statistical Claims\n**Domain:** Problem-Solving and Data Analysis\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nAn observational study can best establish\n\n**A)** Association\n**B)** Causation with certainty\n**C)** That lurking variables never exist\n**D)** A treatment effect by assignment\n\n**Solution:** Observational studies show association, not definitive causation.\n**Answer:** A\n\n## Problem 2\nRandom assignment of treatments is a feature of\n\n**A)** Experiments\n**B)** Surveys only\n**C)** Censuses only\n**D)** Observational studies only\n\n**Solution:** Experiments assign treatments randomly.\n**Answer:** A\n\n## Problem 3\nA headline claims a vitamin causes better grades based on students who choose to take it. Weakness:\n\n**A)** Confounding / self-selection\n**B)** Sample size must be $1$\n**C)** Means cannot be computed\n**D)** Percents are illegal\n\n**Solution:** Choosing the vitamin may correlate with other study habits.\n**Answer:** A\n\n## Problem 4\nA control group is used to\n\n**A)** Provide a baseline comparison\n**B)** Guarantee no variability\n**C)** Replace randomization\n**D)** Eliminate all ethics review\n\n**Solution:** Compare treatment vs no treatment (or placebo).\n**Answer:** A\n\n## Problem 5\nIf two variables are correlated, it follows that\n\n**A)** They may be associated without one causing the other\n**B)** One must cause the other\n**C)** The correlation equals $1$\n**D)** A third variable cannot exist\n\n**Solution:** Correlation does not imply causation.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: In a study of $50$ people, $20$ received treatment. How many were in the untreated comparison group if everyone is in exactly one group?\n\n*Student-produced response — enter a number.*\n\n**Solution:** $50-20=30$.\n**Answer (SPR):** 30\n\n## Problem 7\nBlinding helps reduce\n\n**A)** Bias from expectations\n**B)** Sample size\n**C)** Random variation to zero\n**D)** The need for a research question\n\n**Solution:** Participants/researchers less influenced by knowing assignments.\n**Answer:** A\n\n## Problem 8\nA claim based on a tiny convenience sample should be viewed as\n\n**A)** Weakly supported for broad populations\n**B)** Definitive for all humans\n**C)** More valid than a large random sample\n**D)** Automatically causal\n\n**Solution:** Limited, biased samples poorly support broad claims.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Problem-Solving and Data Analysis Pack 10: Mixed Data Analysis',
        "content": '# SAT Math · Problem-Solving and Data Analysis Pack 10: Mixed Data Analysis\n**Domain:** Problem-Solving and Data Analysis\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\n$25\\%$ of $64$ equals\n\n**A)** $16$\n**B)** $25$\n**C)** $39$\n**D)** $4$\n\n**Solution:** $0.25\\times 64=16$.\n**Answer:** A\n\n## Problem 2\nRatio $8:6$ simplified is\n\n**A)** $4:3$\n**B)** $8:6$\n**C)** $3:4$\n**D)** $2:3$\n\n**Solution:** Divide by $2$.\n**Answer:** A\n\n## Problem 3\nMean of $4,8,12$ and median of the same set — which is larger?\n\n**A)** They are equal\n**B)** Mean larger\n**C)** Median larger\n**D)** Cannot tell\n\n**Solution:** Both equal $8$.\n**Answer:** A\n\n## Problem 4\nBest-fit $y=1.2x+3$. Residual if observed $y=10$ at $x=5$ is\n\n**A)** $1$\n**B)** $-1$\n**C)** $9$\n**D)** $6$\n\n**Solution:** Predicted $1.2(5)+3=9$; residual $10-9=1$.\n**Answer:** A\n\n## Problem 5\n$P(\\text{success})=0.2$ for each independent trial. $P(\\text{two successes in a row})=$\n\n**A)** $0.04$\n**B)** $0.4$\n**C)** $0.2$\n**D)** $0.8$\n\n**Solution:** $0.2\\times 0.2=0.04$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: A $15\\%$ tip on a 40-dollar bill is how many dollars?\n\n*Student-produced response — enter a number.*\n\n**Solution:** $0.15\\times 40=6$.\n**Answer (SPR):** 6\n\n## Problem 7\nSample of $400$ with $p=0.5$ and MoE $\\pm 5\\%$. Interval for true proportion:\n\n**A)** $45\\%$ to $55\\%$\n**B)** $5\\%$ to $50\\%$\n**C)** $50\\%$ to $55\\%$\n**D)** $0\\%$ to $5\\%$\n\n**Solution:** $50\\pm 5$.\n**Answer:** A\n\n## Problem 8\nSpeed $90$ km in $1.5$ h averages\n\n**A)** $60$ km/h\n**B)** $90$ km/h\n**C)** $45$ km/h\n**D)** $135$ km/h\n\n**Solution:** $90/1.5=60$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Geometry and Trigonometry Pack 01: Area and Perimeter',
        "content": '# SAT Math · Geometry and Trigonometry Pack 01: Area and Perimeter\n**Domain:** Geometry and Trigonometry\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nArea of a rectangle $8$ by $5$ is\n\n**A)** $40$\n**B)** $26$\n**C)** $13$\n**D)** $80$\n\n**Solution:** $8\\times 5=40$.\n**Answer:** A\n\n## Problem 2\nPerimeter of a square with side $9$ is\n\n**A)** $36$\n**B)** $81$\n**C)** $18$\n**D)** $27$\n\n**Solution:** $4\\times 9=36$.\n**Answer:** A\n\n## Problem 3\nArea of a triangle with base $10$ and height $6$ is\n\n**A)** $30$\n**B)** $60$\n**C)** $16$\n**D)** $20$\n\n**Solution:** $\\dfrac{1}{2}\\cdot 10\\cdot 6=30$.\n**Answer:** A\n\n## Problem 4\nCircumference of a circle with radius $4$ is\n\n**A)** $8\\pi$\n**B)** $16\\pi$\n**C)** $4\\pi$\n**D)** $2\\pi$\n\n**Solution:** $C=2\\pi r=8\\pi$.\n**Answer:** A\n\n## Problem 5\nArea of a circle with diameter $10$ is\n\n**A)** $25\\pi$\n**B)** $100\\pi$\n**C)** $10\\pi$\n**D)** $50\\pi$\n\n**Solution:** $r=5$; $A=\\pi r^2=25\\pi$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: A rectangle has perimeter $28$ and width $5$. Length is\n\n*Student-produced response — enter a number.*\n\n**Solution:** $2(L+5)=28$ → $L+5=14$ → $L=9$.\n**Answer (SPR):** 9\n\n## Problem 7\nArea of a parallelogram with base $12$ and height $3$ is\n\n**A)** $36$\n**B)** $15$\n**C)** $30$\n**D)** $72$\n\n**Solution:** $bh=36$.\n**Answer:** A\n\n## Problem 8\nA trapezoid has bases $6$ and $10$ and height $4$. Area is\n\n**A)** $32$\n**B)** $40$\n**C)** $24$\n**D)** $64$\n\n**Solution:** $\\dfrac{6+10}{2}\\cdot 4=32$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Geometry and Trigonometry Pack 02: Volume and Surface Area',
        "content": '# SAT Math · Geometry and Trigonometry Pack 02: Volume and Surface Area\n**Domain:** Geometry and Trigonometry\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nVolume of a rectangular prism $3\\times 4\\times 5$ is\n\n**A)** $60$\n**B)** $12$\n**C)** $47$\n**D)** $30$\n\n**Solution:** $3\\cdot4\\cdot5=60$.\n**Answer:** A\n\n## Problem 2\nVolume of a cube with edge $6$ is\n\n**A)** $216$\n**B)** $36$\n**C)** $72$\n**D)** $18$\n\n**Solution:** $6^3=216$.\n**Answer:** A\n\n## Problem 3\nVolume of a cylinder with $r=3$, $h=10$ is\n\n**A)** $90\\pi$\n**B)** $30\\pi$\n**C)** $60\\pi$\n**D)** $9\\pi$\n\n**Solution:** $\\pi r^2 h=9\\pi\\cdot 10=90\\pi$.\n**Answer:** A\n\n## Problem 4\nSurface area of a cube with edge $4$ is\n\n**A)** $96$\n**B)** $64$\n**C)** $16$\n**D)** $48$\n\n**Solution:** $6\\cdot 16=96$.\n**Answer:** A\n\n## Problem 5\nA sphere has radius $3$. Volume is\n\n**A)** $36\\pi$\n**B)** $9\\pi$\n**C)** $12\\pi$\n**D)** $27\\pi$\n\n**Solution:** $\\dfrac{4}{3}\\pi r^3=\\dfrac{4}{3}\\pi 27=36\\pi$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Cone volume $\\dfrac{1}{3}\\pi r^2 h$. If $r=3$, $h=4$, the coefficient of $\\pi$ in the volume is\n\n*Student-produced response — enter a number.*\n\n**Solution:** $\\dfrac{1}{3}\\pi(9)(4)=12\\pi$.\n**Answer (SPR):** 12\n\n## Problem 7\nDoubling all edges of a cube multiplies volume by\n\n**A)** $8$\n**B)** $2$\n**C)** $4$\n**D)** $6$\n\n**Solution:** Linear scale $2$ → volume scale $2^3=8$.\n**Answer:** A\n\n## Problem 8\nA rectangular tank $2$ m by $3$ m by $4$ m holds how many cubic meters?\n\n**A)** $24$\n**B)** $9$\n**C)** $12$\n**D)** $18$\n\n**Solution:** $2\\cdot3\\cdot4=24$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Geometry and Trigonometry Pack 03: Lines and Angles',
        "content": '# SAT Math · Geometry and Trigonometry Pack 03: Lines and Angles\n**Domain:** Geometry and Trigonometry\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nTwo vertical angles each measure\n\n**A)** Equal measures\n**B)** Complementary measures\n**C)** Supplementary only if acute\n**D)** Always $90^\\circ$\n\n**Solution:** Vertical angles are congruent.\n**Answer:** A\n\n## Problem 2\nIf two lines are cut by a transversal and corresponding angles are equal, the lines are\n\n**A)** Parallel\n**B)** Perpendicular\n**C)** Skew\n**D)** Intersecting at $45^\\circ$\n\n**Solution:** Equal corresponding angles imply parallel lines.\n**Answer:** A\n\n## Problem 3\nAn angle of $55^\\circ$ has supplement\n\n**A)** $125^\\circ$\n**B)** $35^\\circ$\n**C)** $55^\\circ$\n**D)** $90^\\circ$\n\n**Solution:** $180-55=125$.\n**Answer:** A\n\n## Problem 4\nComplement of $40^\\circ$ is\n\n**A)** $50^\\circ$\n**B)** $140^\\circ$\n**C)** $40^\\circ$\n**D)** $90^\\circ$\n\n**Solution:** $90-40=50$.\n**Answer:** A\n\n## Problem 5\nAdjacent angles on a straight line sum to\n\n**A)** $180^\\circ$\n**B)** $90^\\circ$\n**C)** $360^\\circ$\n**D)** $45^\\circ$\n\n**Solution:** Linear pair is supplementary.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: If a transversal crosses parallel lines and one interior angle is $110^\\circ$, the consecutive interior angle is\n\n*Student-produced response — enter a number.*\n\n**Solution:** Consecutive interior angles supplementary: $180-110=70$.\n**Answer (SPR):** 70\n\n## Problem 7\nPerpendicular lines form angles of\n\n**A)** $90^\\circ$\n**B)** $45^\\circ$\n**C)** $180^\\circ$\n**D)** $60^\\circ$\n\n**Solution:** Definition of perpendicular.\n**Answer:** A\n\n## Problem 8\nIf $\\angle A$ and $\\angle B$ are vertical and $\\angle A=3x$, $\\angle B=x+40$, then $x=$\n\n**A)** $20$\n**B)** $10$\n**C)** $40$\n**D)** $15$\n\n**Solution:** $3x=x+40$ → $2x=40$ → $x=20$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Geometry and Trigonometry Pack 04: Triangles',
        "content": '# SAT Math · Geometry and Trigonometry Pack 04: Triangles\n**Domain:** Geometry and Trigonometry\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nSum of interior angles in any triangle is\n\n**A)** $180^\\circ$\n**B)** $90^\\circ$\n**C)** $360^\\circ$\n**D)** $270^\\circ$\n\n**Solution:** Triangle angle sum theorem.\n**Answer:** A\n\n## Problem 2\nIn $\\triangle ABC$, $\\angle A=50^\\circ$, $\\angle B=60^\\circ$. Then $\\angle C=$\n\n**A)** $70^\\circ$\n**B)** $80^\\circ$\n**C)** $60^\\circ$\n**D)** $120^\\circ$\n\n**Solution:** $180-110=70$.\n**Answer:** A\n\n## Problem 3\nAn equilateral triangle has all angles equal to\n\n**A)** $60^\\circ$\n**B)** $45^\\circ$\n**C)** $90^\\circ$\n**D)** $120^\\circ$\n\n**Solution:** $180/3=60$.\n**Answer:** A\n\n## Problem 4\nIf a triangle has sides $3,4,5$, it is\n\n**A)** Right\n**B)** Obtuse\n**C)** Equilateral\n**D)** Impossible\n\n**Solution:** $3^2+4^2=5^2$.\n**Answer:** A\n\n## Problem 5\nIsosceles triangle with vertex angle $40^\\circ$ has base angles\n\n**A)** $70^\\circ$ each\n**B)** $40^\\circ$ each\n**C)** $80^\\circ$ each\n**D)** $50^\\circ$ each\n\n**Solution:** $(180-40)/2=70$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Exterior angle of a triangle equals sum of two remote interiors. If remotes are $45^\\circ$ and $60^\\circ$, exterior is\n\n*Student-produced response — enter a number.*\n\n**Solution:** $45+60=105$.\n**Answer (SPR):** 105\n\n## Problem 7\nSSS, SAS, ASA are criteria for\n\n**A)** Congruence\n**B)** Similarity only\n**C)** Area formulas\n**D)** Circle theorems\n\n**Solution:** Triangle congruence postulates.\n**Answer:** A\n\n## Problem 8\nIn a triangle, side opposite the largest angle is\n\n**A)** The longest side\n**B)** The shortest side\n**C)** Always a median\n**D)** Always equal to another side\n\n**Solution:** Larger angle opposite longer side.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Geometry and Trigonometry Pack 05: Similarity and Scale',
        "content": '# SAT Math · Geometry and Trigonometry Pack 05: Similarity and Scale\n**Domain:** Geometry and Trigonometry\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nSimilar triangles have corresponding angles\n\n**A)** Equal\n**B)** Supplementary\n**C)** Complementary\n**D)** Always $60^\\circ$\n\n**Solution:** Definition of similarity.\n**Answer:** A\n\n## Problem 2\nTriangles with scale factor $2$ (small to large): side $5$ on small corresponds to\n\n**A)** $10$\n**B)** $7$\n**C)** $2.5$\n**D)** $25$\n\n**Solution:** $5\\times 2=10$.\n**Answer:** A\n\n## Problem 3\nIf similar figures have scale factor $3$, area scale factor is\n\n**A)** $9$\n**B)** $3$\n**C)** $6$\n**D)** $27$\n\n**Solution:** Areas scale by square of linear factor.\n**Answer:** A\n\n## Problem 4\nCorresponding sides of similar triangles are $6$ and $9$. Ratio (small:large) is\n\n**A)** $2:3$\n**B)** $3:2$\n**C)** $1:1$\n**D)** $6:1$\n\n**Solution:** $6:9=2:3$.\n**Answer:** A\n\n## Problem 5\nA $4$ ft model represents a $60$ ft building. Scale factor model:actual is\n\n**A)** $1:15$\n**B)** $1:12$\n**C)** $15:1$\n**D)** $4:1$\n\n**Solution:** $4/60=1/15$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Similar triangles; sides $x/8=6/12$. Find $x$.\n\n*Student-produced response — enter a number.*\n\n**Solution:** $12x=48$ → $x=4$.\n**Answer (SPR):** 4\n\n## Problem 7\nVolumes of similar solids with scale factor $2$ relate by factor\n\n**A)** $8$\n**B)** $2$\n**C)** $4$\n**D)** $16$\n\n**Solution:** $2^3=8$.\n**Answer:** A\n\n## Problem 8\nAA similarity requires\n\n**A)** Two pairs of congruent corresponding angles\n**B)** All three sides equal\n**C)** A right angle only\n**D)** Equal perimeters\n\n**Solution:** Two angles determine the third; triangles similar.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Geometry and Trigonometry Pack 06: Right Triangles and Pythagorean Theorem',
        "content": '# SAT Math · Geometry and Trigonometry Pack 06: Right Triangles and Pythagorean Theorem\n**Domain:** Geometry and Trigonometry\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nLegs $6$ and $8$. Hypotenuse is\n\n**A)** $10$\n**B)** $14$\n**C)** $48$\n**D)** $7$\n\n**Solution:** $\\sqrt{36+64}=10$.\n**Answer:** A\n\n## Problem 2\nIs $5,12,13$ a right triangle?\n\n**A)** Yes\n**B)** No\n**C)** Only isosceles\n**D)** Only obtuse\n\n**Solution:** $25+144=169$.\n**Answer:** A\n\n## Problem 3\nLeg $5$, hypotenuse $13$. Other leg is\n\n**A)** $12$\n**B)** $8$\n**C)** $18$\n**D)** $10$\n\n**Solution:** $\\sqrt{169-25}=12$.\n**Answer:** A\n\n## Problem 4\nDiagonal of a $3$ by $4$ rectangle is\n\n**A)** $5$\n**B)** $7$\n**C)** $12$\n**D)** $6$\n\n**Solution:** Pythagorean theorem.\n**Answer:** A\n\n## Problem 5\nIf legs are equal and hypotenuse is $10\\sqrt{2}$, each leg is\n\n**A)** $10$\n**B)** $5$\n**C)** $10\\sqrt{2}$\n**D)** $5\\sqrt{2}$\n\n**Solution:** $45$-$45$-$90$: legs $=$ hyp$/\\sqrt{2}=10$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Right triangle legs $9$ and $12$. Hypotenuse:\n\n*Student-produced response — enter a number.*\n\n**Solution:** $\\sqrt{81+144}=15$.\n**Answer (SPR):** 15\n\n## Problem 7\nA $20$-ft ladder reaches $16$ ft up a wall. Distance from wall to base is\n\n**A)** $12$\n**B)** $4$\n**C)** $18$\n**D)** $8$\n\n**Solution:** $\\sqrt{400-256}=12$.\n**Answer:** A\n\n## Problem 8\nWhich set cannot be side lengths of a right triangle?\n\n**A)** $2,3,4$\n**B)** $6,8,10$\n**C)** $5,12,13$\n**D)** $7,24,25$\n\n**Solution:** $4+9=13\\ne 16$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Geometry and Trigonometry Pack 07: Trigonometric Ratios',
        "content": '# SAT Math · Geometry and Trigonometry Pack 07: Trigonometric Ratios\n**Domain:** Geometry and Trigonometry\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nIn a right triangle, $\\sin\\theta=\\dfrac{\\text{opposite}}{\\text{hypotenuse}}$. If opp $=3$, hyp $=5$, $\\sin\\theta=$\n\n**A)** $\\dfrac{3}{5}$\n**B)** $\\dfrac{4}{5}$\n**C)** $\\dfrac{3}{4}$\n**D)** $\\dfrac{5}{3}$\n\n**Solution:** Direct ratio.\n**Answer:** A\n\n## Problem 2\n$\\cos\\theta=\\dfrac{4}{5}$. Adjacent over hypotenuse suggests $\\tan\\theta=$\n\n**A)** $\\dfrac{3}{4}$\n**B)** $\\dfrac{4}{3}$\n**C)** $\\dfrac{4}{5}$\n**D)** $\\dfrac{5}{4}$\n\n**Solution:** Third side $3$; $\\tan=\\text{opp}/\\text{adj}=3/4$.\n**Answer:** A\n\n## Problem 3\n$\\sin 30^\\circ=$\n\n**A)** $\\dfrac{1}{2}$\n**B)** $\\dfrac{\\sqrt{3}}{2}$\n**C)** $1$\n**D)** $\\dfrac{\\sqrt{2}}{2}$\n\n**Solution:** Standard value.\n**Answer:** A\n\n## Problem 4\n$\\cos 60^\\circ=$\n\n**A)** $\\dfrac{1}{2}$\n**B)** $\\dfrac{\\sqrt{3}}{2}$\n**C)** $0$\n**D)** $1$\n\n**Solution:** Standard value.\n**Answer:** A\n\n## Problem 5\nIf $\\tan\\theta=1$ and $\\theta$ acute, $\\theta=$\n\n**A)** $45^\\circ$\n**B)** $30^\\circ$\n**C)** $60^\\circ$\n**D)** $90^\\circ$\n\n**Solution:** $\\tan 45^\\circ=1$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Right triangle: opposite $8$, adjacent $6$. Enter $\\tan\\theta$ as a reduced improper fraction $a/b$.\n\n*Student-produced response — enter a number.*\n\n**Solution:** $\\tan\\theta=8/6=4/3$.\n**Answer (SPR):** 4/3\n\n## Problem 7\n$\\sin^2\\theta+\\cos^2\\theta=$\n\n**A)** $1$\n**B)** $0$\n**C)** $\\tan\\theta$\n**D)** $2$\n\n**Solution:** Pythagorean identity.\n**Answer:** A\n\n## Problem 8\nAngle of elevation $30^\\circ$ to the top of a tree; horizontal distance $50$ ft. Tree height is\n\n**A)** $\\dfrac{50}{\\sqrt{3}}$\n**B)** $50\\sqrt{3}$\n**C)** $25$\n**D)** $100$\n\n**Solution:** $\\tan 30^\\circ=\\dfrac{1}{\\sqrt{3}}=\\dfrac{h}{50}$ → $h=\\dfrac{50}{\\sqrt{3}}$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Geometry and Trigonometry Pack 08: Special Right Triangles',
        "content": '# SAT Math · Geometry and Trigonometry Pack 08: Special Right Triangles\n**Domain:** Geometry and Trigonometry\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nIn a $45$-$45$-$90$ triangle, legs are equal. If a leg is $7$, hypotenuse is\n\n**A)** $7\\sqrt{2}$\n**B)** $7$\n**C)** $14$\n**D)** $\\dfrac{7}{\\sqrt{2}}$\n\n**Solution:** Hypotenuse $=$ leg $\\cdot\\sqrt{2}$.\n**Answer:** A\n\n## Problem 2\nIn a $30$-$60$-$90$ triangle, shorter leg is $5$. Hypotenuse is\n\n**A)** $10$\n**B)** $5\\sqrt{3}$\n**C)** $5$\n**D)** $15$\n\n**Solution:** Hypotenuse $=2\\times$ shorter leg.\n**Answer:** A\n\n## Problem 3\nIn $30$-$60$-$90$, shorter leg $4$. Longer leg is\n\n**A)** $4\\sqrt{3}$\n**B)** $8$\n**C)** $4$\n**D)** $2\\sqrt{3}$\n\n**Solution:** Longer $=$ shorter $\\cdot\\sqrt{3}$.\n**Answer:** A\n\n## Problem 4\nHypotenuse of $45$-$45$-$90$ is $10$. Each leg is\n\n**A)** $5\\sqrt{2}$\n**B)** $10\\sqrt{2}$\n**C)** $5$\n**D)** $10$\n\n**Solution:** Leg $=$ hyp$/\\sqrt{2}=5\\sqrt{2}$.\n**Answer:** A\n\n## Problem 5\nA square has diagonal $6\\sqrt{2}$. Side length is\n\n**A)** $6$\n**B)** $3$\n**C)** $6\\sqrt{2}$\n**D)** $12$\n\n**Solution:** Diagonal $=$ side$\\sqrt{2}$ → side $=6$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: $30$-$60$-$90$ with hypotenuse $18$. Shorter leg equals\n\n*Student-produced response — enter a number.*\n\n**Solution:** Shorter $=$ half hypotenuse.\n**Answer (SPR):** 9\n\n## Problem 7\nAltitude to the hypotenuse in an equilateral triangle of side $8$ is\n\n**A)** $4\\sqrt{3}$\n**B)** $8\\sqrt{3}$\n**C)** $4$\n**D)** $8$\n\n**Solution:** Creates $30$-$60$-$90$; altitude $=4\\sqrt{3}$.\n**Answer:** A\n\n## Problem 8\nWhich side ratios match $30$-$60$-$90$?\n\n**A)** $1:\\sqrt{3}:2$\n**B)** $1:1:\\sqrt{2}$\n**C)** $3:4:5$\n**D)** $1:2:3$\n\n**Solution:** Standard ratio shorter : longer : hyp.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Geometry and Trigonometry Pack 09: Circles',
        "content": '# SAT Math · Geometry and Trigonometry Pack 09: Circles\n**Domain:** Geometry and Trigonometry\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nCentral angle $90^\\circ$ in a circle of radius $6$. Arc length is\n\n**A)** $3\\pi$\n**B)** $6\\pi$\n**C)** $\\dfrac{3}{2}\\pi$\n**D)** $9\\pi$\n\n**Solution:** Fraction $90/360=1/4$ of $2\\pi r=12\\pi$ → $3\\pi$.\n**Answer:** A\n\n## Problem 2\nArea of a sector with central angle $60^\\circ$ and $r=6$ is\n\n**A)** $6\\pi$\n**B)** $36\\pi$\n**C)** $12\\pi$\n**D)** $3\\pi$\n\n**Solution:** $\\dfrac{60}{360}\\pi r^2=\\dfrac{1}{6}\\cdot 36\\pi=6\\pi$.\n**Answer:** A\n\n## Problem 3\nEquation of a circle center $(0,0)$ radius $5$ is\n\n**A)** $x^2+y^2=25$\n**B)** $x^2+y^2=5$\n**C)** $(x-5)^2+y^2=0$\n**D)** $x+y=25$\n\n**Solution:** $x^2+y^2=r^2$.\n**Answer:** A\n\n## Problem 4\nInscribed angle intercepting a $80^\\circ$ arc measures\n\n**A)** $40^\\circ$\n**B)** $80^\\circ$\n**C)** $160^\\circ$\n**D)** $20^\\circ$\n\n**Solution:** Inscribed angle is half the arc.\n**Answer:** A\n\n## Problem 5\nDiameter of a circle with circumference $14\\pi$ is\n\n**A)** $14$\n**B)** $7$\n**C)** $28$\n**D)** $14\\pi$\n\n**Solution:** $C=\\pi d$ → $d=14$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Circle area $49\\pi$. Radius is\n\n*Student-produced response — enter a number.*\n\n**Solution:** $r^2=49$ → $r=7$.\n**Answer (SPR):** 7\n\n## Problem 7\nA chord of length $8$ is $3$ from the center. Radius is\n\n**A)** $5$\n**B)** $4$\n**C)** $3$\n**D)** $11$\n\n**Solution:** Half chord $4$; $r=\\sqrt{3^2+4^2}=5$.\n**Answer:** A\n\n## Problem 8\nCenter $(2,-1)$, radius $4$. Equation:\n\n**A)** $(x-2)^2+(y+1)^2=16$\n**B)** $(x+2)^2+(y-1)^2=16$\n**C)** $(x-2)^2+(y+1)^2=4$\n**D)** $x^2+y^2=16$\n\n**Solution:** $(x-h)^2+(y-k)^2=r^2$.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Geometry and Trigonometry Pack 10: Mixed Geometry and Trigonometry',
        "content": '# SAT Math · Geometry and Trigonometry Pack 10: Mixed Geometry and Trigonometry\n**Domain:** Geometry and Trigonometry\n**Aligned to:** Digital SAT Math (College Board content domains)\n\nOriginal AI practice problems for Digital SAT Math fluency. Not College Board exam items.\n\n## Problem 1\nArea of a circle with radius $2$ is\n\n**A)** $4\\pi$\n**B)** $2\\pi$\n**C)** $8\\pi$\n**D)** $\\pi$\n\n**Solution:** $\\pi\\cdot 4=4\\pi$.\n**Answer:** A\n\n## Problem 2\nVolume of a cube side $5$ is\n\n**A)** $125$\n**B)** $25$\n**C)** $15$\n**D)** $100$\n\n**Solution:** $5^3=125$.\n**Answer:** A\n\n## Problem 3\nPythagorean triple completing legs $9,12$ has hypotenuse\n\n**A)** $15$\n**B)** $21$\n**C)** $13$\n**D)** $10$\n\n**Solution:** $15$.\n**Answer:** A\n\n## Problem 4\n$\\sin 60^\\circ=$\n\n**A)** $\\dfrac{\\sqrt{3}}{2}$\n**B)** $\\dfrac{1}{2}$\n**C)** $1$\n**D)** $\\dfrac{\\sqrt{2}}{2}$\n\n**Solution:** Standard value.\n**Answer:** A\n\n## Problem 5\nSimilar triangles scale factor $1/2$ (large to small). Large side $20$ corresponds to\n\n**A)** $10$\n**B)** $40$\n**C)** $15$\n**D)** $5$\n\n**Solution:** $20\\times 1/2=10$.\n**Answer:** A\n\n## Problem 6 (SPR)\nSPR: Interior angles of a triangle are $x$, $2x$, and $3x$. Find $x$.\n\n*Student-produced response — enter a number.*\n\n**Solution:** $6x=180$ → $x=30$.\n**Answer (SPR):** 30\n\n## Problem 7\nA cylinder $r=2$, $h=5$ has volume\n\n**A)** $20\\pi$\n**B)** $10\\pi$\n**C)** $4\\pi$\n**D)** $40\\pi$\n\n**Solution:** $\\pi\\cdot 4\\cdot 5=20\\pi$.\n**Answer:** A\n\n## Problem 8\nIn right triangle with acute $\\theta$, adjacent $=12$, hyp $=13$. $\\cos\\theta=$\n\n**A)** $\\dfrac{12}{13}$\n**B)** $\\dfrac{5}{13}$\n**C)** $\\dfrac{12}{5}$\n**D)** $\\dfrac{5}{12}$\n\n**Solution:** Adjacent/hypotenuse.\n**Answer:** A\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Domain Guide: Algebra',
        "content": '# SAT Math · Domain Guide: Algebra\n**Domain:** Algebra\n**Aligned to:** Digital SAT Math (College Board content domains)\n\n## What this domain measures\nAnalyze, fluently solve, and create linear equations and inequalities; analyze and fluently solve equations and systems using multiple techniques.\n\n## Official skill list (College Board)\n- **Linear equations in one variable** — isolate the variable; clear parentheses and fractions; check solutions.\n- **Linear functions** — interpret slope and intercept; evaluate and build $f(x)=mx+b$; connect tables, graphs, and equations.\n- **Linear equations in two variables** — graph and rewrite forms; find intercepts; identify solutions as ordered pairs.\n- **Systems of two linear equations in two variables** — substitution, elimination, and graphical intersection; recognize one, none, or infinitely many solutions.\n- **Linear inequalities in one or two variables** — solve and graph; flip the inequality when multiplying/dividing by a negative; interpret feasible regions in context.\n\n## Study moves\n1. Always rewrite to a clear form ($x=\\ldots$, $y=mx+b$, or $Ax+By=C$) before interpreting.\n2. For word problems, define variables, write equations, then solve — do not jump to arithmetic.\n3. For systems, decide quickly: substitution if a variable is already isolated; elimination if coefficients align.\n4. Practice SPR (student-produced response) by boxing a single numeric answer and checking units.\n\n## Mini self-check\n- Solve $3(x-2)=2x+5$ and state each algebra step.\n- Find the intersection of $y=2x-1$ and $x+y=8$.\n- Graph $y>-x+3$ with the correct boundary style.\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Domain Guide: Advanced Math',
        "content": '# SAT Math · Domain Guide: Advanced Math\n**Domain:** Advanced Math\n**Aligned to:** Digital SAT Math (College Board content domains)\n\n## What this domain measures\nSkills central to progressing in advanced math courses: absolute value, quadratic, exponential, polynomial, rational, radical, and other nonlinear equations, plus equivalent expressions.\n\n## Official skill list (College Board)\n- **Nonlinear functions** — quadratics, exponentials, and other curves; interpret key features (vertex, intercepts, growth/decay).\n- **Nonlinear equations in one variable** — solve quadratics by factoring, square roots, or quadratic formula; solve absolute value, radical, and rational equations with domain checks.\n- **Systems of equations in two variables** — linear–nonlinear intersections (e.g., line and parabola).\n- **Equivalent expressions** — expand, factor, rewrite radicals/exponents, and simplify rational expressions strategically.\n\n## Study moves\n1. For quadratics, connect factored, standard, and vertex forms.\n2. For exponentials, distinguish growth (base $>1$) from decay ($0<$ base $<1$).\n3. Always check for extraneous solutions after squaring or clearing denominators.\n4. Use structure: spot $(a+b)^2$, difference of squares, and common factors before expanding everything.\n\n## Mini self-check\n- Solve $x^2-5x+6=0$ and state the product of roots.\n- Rewrite $4^{x+1}$ as $4\\cdot 4^x$.\n- Simplify $\\dfrac{x^2-9}{x-3}$ for $x\\ne 3$.\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Domain Guide: Problem-Solving and Data Analysis',
        "content": '# SAT Math · Domain Guide: Problem-Solving and Data Analysis\n**Domain:** Problem-Solving and Data Analysis\n**Aligned to:** Digital SAT Math (College Board content domains)\n\n## What this domain measures\nQuantitative reasoning with ratios, rates, and proportional relationships; unit rate; analysis and interpretation of one- and two-variable data.\n\n## Official skill list (College Board)\n- **Ratios, rates, proportional relationships, and units** — unit conversions; constant rates; proportional reasoning.\n- **Percentages** — percent of, percent change, successive percents.\n- **One-variable data** — distributions; mean, median, mode, range, and spread comparisons.\n- **Two-variable data** — scatterplots; linear models; residuals; comparing linear vs exponential trends.\n- **Probability and conditional probability** — basic and “given that” probabilities from tables and descriptions.\n- **Inference from sample statistics and margin of error** — sample proportions; interpreting intervals.\n- **Evaluating statistical claims** — observational studies vs experiments; association vs causation; bias and sampling issues.\n\n## Study moves\n1. Write percents as decimals before computing; for percent change use $\\dfrac{\\text{new}-\\text{old}}{\\text{old}}$.\n2. On scatterplots, focus on slope meaning and whether predictions are interpolation or extrapolation.\n3. For conditional probability, restrict the denominator to the conditioning group.\n4. Critique headlines: Was there random sampling? Random assignment? A control group?\n\n## Mini self-check\n- $20\\%$ off 80 dollars, then $10\\%$ tax on the sale price — final cost?\n- Mean vs median sensitivity to an outlier.\n- From a two-way table, compute $P(A|B)$.\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
    {
        "title": 'SAT Math · Domain Guide: Geometry and Trigonometry',
        "content": '# SAT Math · Domain Guide: Geometry and Trigonometry\n**Domain:** Geometry and Trigonometry\n**Aligned to:** Digital SAT Math (College Board content domains)\n\n## What this domain measures\nProblems focused on area and volume; lines, angles, and triangles; right triangles and trigonometry; and circles.\n\n## Official skill list (College Board)\n- **Area and volume** — polygons, circles, prisms, cylinders, cones, spheres; effects of scaling.\n- **Lines, angles, and triangles** — parallel lines and transversals; triangle congruence/similarity ideas; angle relationships.\n- **Right triangles and trigonometry** — Pythagorean theorem; special right triangles ($30$-$60$-$90$, $45$-$45$-$90$); sine, cosine, tangent.\n- **Circles** — circumference and area; arc length and sector area; circle equations; inscribed vs central angles.\n\n## Study moves\n1. Sketch and label every geometry item — missing diagrams cause most errors.\n2. Memorize special-triangle ratios and $\\sin/\\cos/\\tan$ of $30^\\circ,45^\\circ,60^\\circ$.\n3. For similar figures: lengths scale by $k$, areas by $k^2$, volumes by $k^3$.\n4. Circle sectors use the fraction $\\dfrac{\\theta}{360}$ of full circumference or area.\n\n## Mini self-check\n- Legs $5$ and $12$ → hypotenuse?\n- Sector area for $r=6$, central angle $60^\\circ$.\n- $\\tan\\theta$ if opposite $=5$ and adjacent $=12$.\n',
        "category": 'SAT Mathematics',
        "space": 'sat-mathematics',
    },
]
