"""Wave 6 formula-practice quiz specifications (companion to generate-ap-formula-practice-wave6.py)."""

# Each entry: title suffix after "Wave 6X — ", subject, description, topic_tags, items
# Item: ("mcq"|"frq", prompt, ...mcq: choices, answer_idx, steps, concept_id, tier)
#       ("frq", prompt, steps, answers, concept_id, tier)

WAVE6_QUIZ_SPECS = [
    # ── AP Physics 1 ──
    {
        "label": "6A",
        "subject": "AP Physics 1",
        "topic": "Fluids",
        "description": "Original CED-aligned practice with hydrostatic pressure, buoyancy, and continuity.",
        "topic_tags": ["ap-physics-1", "fluids", "unit-8"],
        "items": [
            (
                "mcq",
                r"A sealed tank holds water (\(\rho=1000\,\mathrm{kg/m^3}\)). The gauge pressure \(2.0\,\mathrm m\) below the surface is closest to which value? Use \(g=10\,\mathrm{m/s^2}\).",
                [r"A) \(2.0\times10^3\,\mathrm{Pa}\)", r"B) \(2.0\times10^4\,\mathrm{Pa}\)", r"C) \(2.0\times10^5\,\mathrm{Pa}\)", r"D) \(2.0\times10^6\,\mathrm{Pa}\)"],
                1,
                [r"Gauge pressure in a static fluid: \(P=\rho gh\).", r"Substitute: \(P=(1000)(10)(2.0)=2.0\times10^4\,\mathrm{Pa}\)."],
                "p1-hydrostatic-gauge-w6",
                2,
            ),
            (
                "frq",
                r"A \(0.30\,\mathrm{m^3}\) block of wood (\(\rho_{\mathrm{wood}}=600\,\mathrm{kg/m^3}\)) floats in fresh water. Find the fraction of the block submerged and the buoyant force. Use \(g=10\,\mathrm{m/s^2}\).",
                [r"Floating equilibrium: \(F_B=mg\) and \(F_B=\rho_{\mathrm{fluid}}V_{\mathrm{disp}}g\).", r"Solve for submerged fraction \(V_{\mathrm{disp}}/V_{\mathrm{obj}}=\rho_{\mathrm{obj}}/\rho_{\mathrm{fluid}}\).", "Compute buoyant force from displaced water weight."],
                [r"Submerged fraction \(=600/1000=0.60\) (60%).", r"Block mass \(m=\rho V=(600)(0.30)=180\,\mathrm{kg}\); \(F_B=mg=1800\,\mathrm N\)."],
                "p1-buoyancy-fraction-w6",
                2,
            ),
            (
                "mcq",
                r"Water flows through a horizontal pipe that narrows from \(A_1=0.040\,\mathrm{m^2}\) to \(A_2=0.010\,\mathrm{m^2}\). If \(v_1=2.0\,\mathrm{m/s}\), what is \(v_2\)?",
                [r"A) \(0.50\,\mathrm{m/s}\)", r"B) \(2.0\,\mathrm{m/s}\)", r"C) \(4.0\,\mathrm{m/s}\)", r"D) \(8.0\,\mathrm{m/s}\)"],
                3,
                [r"Continuity for incompressible flow: \(A_1v_1=A_2v_2\).", r"\(v_2=(A_1/A_2)v_1=(0.040/0.010)(2.0)=8.0\,\mathrm{m/s}\)."],
                "p1-continuity-w6",
                2,
            ),
            (
                "frq",
                r"A horizontal pipe carries water at \(3.0\,\mathrm{m/s}\) where the diameter is \(6.0\,\mathrm{cm}\). The pipe rises \(1.5\,\mathrm m\) and the diameter shrinks to \(3.0\,\mathrm{cm}\). With \(\rho=1000\,\mathrm{kg/m^3}\) and \(g=10\,\mathrm{m/s^2}\), estimate the gauge pressure change from the wide section to the narrow section (Bernoulli, same streamline).",
                [r"Find \(v_2\) from continuity.", r"Apply Bernoulli between two points on one streamline: \(P+\tfrac12\rho v^2+\rho gy=\text{const}\).", r"Subtract to get \(\Delta P\) including the height term."],
                [r"Areas scale as \(d^2\), so \(v_2=4(3.0)=12\,\mathrm{m/s}\).", r"\(\Delta P=\tfrac12\rho(v_1^2-v_2^2)-\rho g\Delta y=\tfrac12(1000)(9-144)-15000\approx-82500\,\mathrm{Pa}\) (pressure drops in the narrow, higher section)."],
                "p1-bernoulli-w6",
                3,
            ),
        ],
    },
    {
        "label": "6B",
        "subject": "AP Physics 1",
        "topic": "Torque and Angular Momentum",
        "description": "Original practice with torque, rotational inertia, and angular momentum conservation.",
        "topic_tags": ["ap-physics-1", "rotation", "unit-7"],
        "items": [
            (
                "mcq",
                r"A \(40\,\mathrm N\) force is applied tangentially at \(r=0.25\,\mathrm m\) on a wheel. The torque magnitude is",
                [r"A) \(10\,\mathrm{N\,m}\)", r"B) \(16\,\mathrm{N\,m}\)", r"C) \(40\,\mathrm{N\,m}\)", r"D) \(160\,\mathrm{N\,m}\)"],
                0,
                [r"Tangential force: \(\tau=rF\sin90^\circ=rF\).", r"\(\tau=(0.25)(40)=10\,\mathrm{N\,m}\)."],
                "p1-torque-tangential-w6",
                1,
            ),
            (
                "frq",
                r"A uniform rod of mass \(2.0\,\mathrm{kg}\) and length \(1.2\,\mathrm m\) is pivoted at one end and released from horizontal. Find its angular acceleration immediately after release. Model the rod as \(I=\tfrac13ML^2\).",
                [r"Torque about pivot for a horizontal uniform rod: \(\tau=Mg(L/2)\).", r"Use \(\tau=I\alpha\) with \(I=\tfrac13ML^2\).", r"Solve for \(\alpha\)."],
                [r"\(\alpha=\dfrac{Mg(L/2)}{\tfrac13ML^2}=\dfrac{3g}{2L}=\dfrac{3(10)}{2(1.2)}=12.5\,\mathrm{rad/s^2}\)."],
                "p1-rod-pivot-w6",
                3,
            ),
            (
                "mcq",
                r"A disk (\(I=0.20\,\mathrm{kg\,m^2}\)) spins at \(6.0\,\mathrm{rad/s}\). A \(0.20\,\mathrm{kg}\) lump of clay sticks at \(r=1.0\,\mathrm m\) from the axis. The new angular speed is",
                [r"A) \(2.0\,\mathrm{rad/s}\)", r"B) \(3.0\,\mathrm{rad/s}\)", r"C) \(4.5\,\mathrm{rad/s}\)", r"D) \(6.0\,\mathrm{rad/s}\)"],
                1,
                [r"Conserve angular momentum: \(I_1\omega_1=I_2\omega_2\).", r"\(I_2=0.20+0.20(1.0)^2=0.40\); \(\omega_2=0.20(6.0)/0.40=3.0\,\mathrm{rad/s}\)."],
                "p1-L-conservation-w6",
                2,
            ),
            (
                "frq",
                r"A \(0.80\,\mathrm{kg}\) point mass moves in a horizontal circle of radius \(0.60\,\mathrm m\) at \(2.5\,\mathrm{rad/s}\). Find its angular momentum about the center and the centripetal force.",
                [r"Use \(L=I\omega=m r^2\omega\) for a point mass.", r"Centripetal force \(F=mv^2/r=m r\omega^2\)."],
                [r"\(L=(0.80)(0.60)^2(2.5)=0.72\,\mathrm{kg\,m^2/s}\).", r"\(F=(0.80)(0.60)(2.5)^2=3.0\,\mathrm N\)."],
                "p1-angular-momentum-w6",
                2,
            ),
        ],
    },
    # ── AP Physics 2 ──
    {
        "label": "6A",
        "subject": "AP Physics 2",
        "topic": "Thermodynamics",
        "description": "Original practice with ideal-gas processes, work, and engine efficiency.",
        "topic_tags": ["ap-physics-2", "thermodynamics", "unit-9"],
        "items": [
            (
                "mcq",
                r"An ideal monatomic gas (\(\gamma=5/3\)) undergoes an adiabatic expansion. Which statement is correct?",
                [r"A) \(Q>0\) because the gas expands.", r"B) \(\Delta U=0\) because no heat enters.", r"C) The gas does work and \(Q=0\).", "D) Temperature must increase."],
                2,
                [r"Adiabatic: \(Q=0\).", r"First law: \(\Delta U=Q-W\); expansion implies \(W>0\), so internal energy decreases."],
                "p2-adiabatic-w6",
                2,
            ),
            (
                "frq",
                r"\(2.0\,\mathrm{mol}\) of an ideal gas at \(300\,\mathrm K\) and \(1.0\times10^5\,\mathrm{Pa}\) is heated at constant pressure to \(450\,\mathrm K\). With \(R=8.31\,\mathrm{J/(mol\,K)}\), find the work done by the gas and \(\Delta U\) for a diatomic ideal gas (\(c_V=\tfrac{7}{2}R\)).",
                [r"At constant pressure, \(W=nR\Delta T\).", r"\(\Delta U=n c_V\Delta T\).", "Carry units in joules."],
                [r"\(W=(2.0)(8.31)(150)\approx2.49\times10^3\,\mathrm J\).", r"\(\Delta U=(2.0)(3.5)(8.31)(150)\approx8.73\times10^3\,\mathrm J\)."],
                "p2-isobaric-w6",
                3,
            ),
            (
                "mcq",
                r"A heat engine absorbs \(800\,\mathrm J\) from a hot reservoir and rejects \(500\,\mathrm J\) to a cold reservoir each cycle. Its thermal efficiency is",
                ["A) 0.375", "B) 0.500", "C) 0.625", "D) 1.60"],
                0,
                [r"\(\eta=W/Q_h=1-Q_c/Q_h\).", r"\(\eta=1-500/800=0.375\)."],
                "p2-engine-efficiency-w6",
                2,
            ),
            (
                "frq",
                r"A Carnot engine operates between \(500\,\mathrm K\) and \(300\,\mathrm K\). If it absorbs \(1200\,\mathrm J\) per cycle, find the maximum possible work output and heat rejected.",
                [r"\(\eta_{\mathrm{Carnot}}=1-T_c/T_h\).", r"\(W=\eta Q_h\); \(Q_c=Q_h-W\)."],
                [r"\(\eta=1-300/500=0.40\); \(W=480\,\mathrm J\).", r"\(Q_c=720\,\mathrm J\)."],
                "p2-carnot-w6",
                2,
            ),
        ],
    },
    {
        "label": "6B",
        "subject": "AP Physics 2",
        "topic": "Geometric Optics",
        "description": "Original practice with mirrors, lenses, and magnification.",
        "topic_tags": ["ap-physics-2", "optics", "unit-13"],
        "items": [
            (
                "mcq",
                r"An object is placed \(30\,\mathrm{cm}\) in front of a converging lens with \(f=10\,\mathrm{cm}\). The image distance is",
                [r"A) \(-15\,\mathrm{cm}\)", r"B) \(+15\,\mathrm{cm}\)", r"C) \(+20\,\mathrm{cm}\)", r"D) \(+30\,\mathrm{cm}\)"],
                1,
                [r"Thin-lens: \(1/f=1/d_o+1/d_i\).", r"\(1/10=1/30+1/d_i\Rightarrow d_i=15\,\mathrm{cm}\) (real, on opposite side)."],
                "p2-thin-lens-w6",
                2,
            ),
            (
                "frq",
                r"A concave mirror has radius \(40\,\mathrm{cm}\). An object \(60\,\mathrm{cm}\) from the vertex produces an image. Find \(d_i\), magnification, and state whether the image is real or virtual.",
                [r"\(f=R/2=20\,\mathrm{cm}\); mirror equation \(1/f=1/d_o+1/d_i\).", r"\(m=-d_i/d_o\).", r"Sign of \(d_i\) indicates real vs virtual."],
                [r"\(1/20=1/60+1/d_i\Rightarrow d_i=30\,\mathrm{cm}\) (positive → real).", r"\(m=-30/60=-0.50\) (inverted, half size)."],
                "p2-mirror-w6",
                2,
            ),
            (
                "mcq",
                r"Light enters glass (\(n=1.50\)) from air at \(30^\circ\) to the normal. The refracted angle is closest to",
                [r"A) \(19^\circ\)", r"B) \(30^\circ\)", r"C) \(48^\circ\)", r"D) \(90^\circ\) (total internal reflection)"],
                0,
                [r"Snell: \(n_1\sin\theta_1=n_2\sin\theta_2\).", r"\(\sin\theta_2=\sin30^\circ/1.50=0.333\Rightarrow\theta_2\approx19^\circ\)."],
                "p2-snell-w6",
                2,
            ),
            (
                "frq",
                r"Two slits separated by \(0.20\,\mathrm{mm}\) are illuminated with \(\lambda=600\,\mathrm{nm}\). On a screen \(2.0\,\mathrm m\) away, find the distance between the central maximum and the first-order bright fringe.",
                [r"Small-angle fringe spacing \(y=m\lambda L/d\).", r"Use consistent SI units for \(d\) and \(\lambda\)."],
                [r"\(y_1=(600\times10^{-9})(2.0)/(0.20\times10^{-3})=6.0\times10^{-3}\,\mathrm m=6.0\,\mathrm{mm}\)."],
                "p2-double-slit-w6",
                2,
            ),
        ],
    },
    # ── AP Physics C: Mechanics ──
    {
        "label": "6A",
        "subject": "AP Physics C: Mechanics",
        "topic": "Rotation with Calculus",
        "description": "Original calculus-based practice with torque, rotational kinematics, and energy.",
        "topic_tags": ["ap-physics-c-mechanics", "rotation", "unit-6"],
        "items": [
            (
                "mcq",
                r"A wheel's angular velocity is \(\omega(t)=4.0-0.50t\,\mathrm{rad/s}\). Its angular acceleration at \(t=2.0\,\mathrm s\) is",
                [r"A) \(-1.0\,\mathrm{rad/s^2}\)", r"B) \(-0.50\,\mathrm{rad/s^2}\)", r"C) \(+0.50\,\mathrm{rad/s^2}\)", r"D) \(+3.0\,\mathrm{rad/s^2}\)"],
                1,
                [r"\(\alpha=d\omega/dt\).", r"\(\alpha=-0.50\,\mathrm{rad/s^2}\) (constant)."],
                "pc-rot-alpha-w6",
                2,
            ),
            (
                "frq",
                r"A solid cylinder (\(M=3.0\,\mathrm{kg}, R=0.20\,\mathrm m\)) rolls without slipping down a \(30^\circ\) incline. Find its linear acceleration. Use \(I=\tfrac12MR^2\).",
                [r"Energy or Newton: rolling constraint \(a=\alpha R\).", r"Net force down incline minus friction relation for rolling.", r"Standard result \(a=\dfrac{g\sin\theta}{1+I/(MR^2)}\)."],
                [r"\(I/(MR^2)=0.5\); \(a=\dfrac{10\sin30^\circ}{1+0.5}=\dfrac{5}{1.5}\approx3.33\,\mathrm{m/s^2}\)."],
                "pc-rolling-incline-w6",
                3,
            ),
            (
                "mcq",
                r"The rotational kinetic energy of a hoop (\(I=MR^2\)) of mass \(2.0\,\mathrm{kg}\) and radius \(0.40\,\mathrm m\) spinning at \(5.0\,\mathrm{rad/s}\) is",
                [r"A) \(4.0\,\mathrm J\)", r"B) \(8.0\,\mathrm J\)", r"C) \(16\,\mathrm J\)", r"D) \(20\,\mathrm J\)"],
                0,
                [r"\(K_{\mathrm{rot}}=\tfrac12I\omega^2=\tfrac12MR^2\omega^2\).", r"\(K=\tfrac12(2.0)(0.40)^2(5.0)^2=4.0\,\mathrm J\)."],
                "pc-rotational-ke-w6",
                2,
            ),
            (
                "frq",
                r"A torque \(\tau=6.0-2.0t\,\mathrm{N\,m}\) acts on a disk with \(I=0.80\,\mathrm{kg\,m^2}\), initially at rest. Find \(\omega(3.0\,\mathrm s)\) by integrating \(\alpha=\tau/I\).",
                [r"\(\alpha=(6.0-2.0t)/0.80\).", r"\(\omega=\int_0^3\alpha\,dt\).", "Evaluate the definite integral."],
                [r"\(\omega=\int_0^3(7.5-2.5t)\,dt=[7.5t-1.25t^2]_0^3=22.5-11.25=11.25\,\mathrm{rad/s}\)."],
                "pc-torque-integral-w6",
                3,
            ),
        ],
    },
    {
        "label": "6B",
        "subject": "AP Physics C: Mechanics",
        "topic": "Gravitation and Orbits",
        "description": "Original practice with universal gravitation, orbital speed, and energy.",
        "topic_tags": ["ap-physics-c-mechanics", "gravitation", "unit-7"],
        "items": [
            (
                "mcq",
                r"Two \(1000\,\mathrm{kg}\) spheres are \(1.0\,\mathrm m\) apart (center to center). The gravitational force between them is closest to (\(G=6.67\times10^{-11}\,\mathrm{N\,m^2/kg^2}\))",
                [r"A) \(6.7\times10^{-5}\,\mathrm N\)", r"B) \(6.7\times10^{-4}\,\mathrm N\)", r"C) \(6.7\times10^{-3}\,\mathrm N\)", r"D) \(6.7\times10^{-2}\,\mathrm N\)"],
                0,
                [r"\(F=Gm_1m_2/r^2\).", r"\(F=(6.67\times10^{-11})(10^6)/1=6.67\times10^{-5}\,\mathrm N\)."],
                "pc-grav-force-w6",
                2,
            ),
            (
                "frq",
                r"A satellite orbits Earth (\(M_E=5.97\times10^{24}\,\mathrm{kg}\)) at altitude \(400\,\mathrm{km}\). Find its orbital speed and period. Earth radius \(R_E=6.37\times10^6\,\mathrm m\), \(G=6.67\times10^{-11}\).",
                [r"For circular orbit: \(v=\sqrt{GM/r}\) with \(r=R_E+h\).", r"Period \(T=2\pi r/v\)."],
                [r"\(r=6.77\times10^6\,\mathrm m\); \(v\approx7.67\times10^3\,\mathrm{m/s}\).", r"\(T=2\pi(6.77\times10^6)/(7.67\times10^3)\approx5.55\times10^3\,\mathrm s\approx92\,\mathrm{min}\)."],
                "pc-orbit-speed-w6",
                3,
            ),
            (
                "mcq",
                r"Gravitational potential energy \(U=-Gm_1m_2/r\). If \(r\) is halved, \(|U|\)",
                ["A) doubles", "B) halves", "C) stays the same", "D) becomes four times smaller"],
                0,
                [r"\(U=-Gm_1m_2/r\).", r"Halving \(r\) doubles \(|U|\) (the binding energy magnitude increases)."],
                "pc-grav-potential-w6",
                2,
            ),
            (
                "frq",
                r"A \(500\,\mathrm{kg}\) satellite transfers from a circular orbit at \(r_1=7.0\times10^6\,\mathrm m\) to \(r_2=1.4\times10^7\,\mathrm m\) (Earth \(GM=3.98\times10^{14}\,\mathrm{m^3/s^2}\)). Find the change in total mechanical energy.",
                [r"Circular orbit energy \(E=-GMm/(2r)\).", r"\(\Delta E=GMm(1/(2r_1)-1/(2r_2))\)."],
                [r"\(\Delta E=(3.98\times10^{14})(500)\left(\dfrac1{2(7.0\times10^6)}-\dfrac1{2(1.4\times10^7)}\right)\approx7.1\times10^9\,\mathrm J\) (energy must be added)."],
                "pc-orbit-energy-w6",
                3,
            ),
        ],
    },
    # ── AP Physics C: E&M ──
    {
        "label": "6A",
        "subject": "AP Physics C: E&M",
        "topic": "Electric Fields and Gauss's Law",
        "description": "Original practice with Coulomb's law, field superposition, and Gaussian surfaces.",
        "topic_tags": ["ap-physics-c-em", "electrostatics", "unit-8"],
        "items": [
            (
                "mcq",
                r"A \(+4.0\,\mu\mathrm C\) point charge is at the origin. The electric field magnitude at \(x=0.30\,\mathrm m\) is closest to (\(k=8.99\times10^9\,\mathrm{N\,m^2/C^2}\))",
                [r"A) \(4.0\times10^5\,\mathrm{N/C}\)", r"B) \(4.0\times10^6\,\mathrm{N/C}\)", r"C) \(4.0\times10^7\,\mathrm{N/C}\)", r"D) \(4.0\times10^8\,\mathrm{N/C}\)"],
                0,
                [r"\(E=k|q|/r^2\).", r"\(E=(8.99\times10^9)(4.0\times10^{-6})/(0.30)^2\approx4.0\times10^5\,\mathrm{N/C}\)."],
                "pem-coulomb-field-w6",
                2,
            ),
            (
                "frq",
                r"An infinite line of charge has linear density \(\lambda=2.0\times10^{-6}\,\mathrm{C/m}\). Find the electric field magnitude \(2.0\,\mathrm{cm}\) from the line using Gauss's law.",
                [r"Cylindrical Gaussian surface: flux \(E(2\pi rL)=\lambda L/\varepsilon_0\).", r"Solve for \(E\)."],
                [r"\(E=\lambda/(2\pi\varepsilon_0 r)\approx(2.0\times10^{-6})/(2\pi(8.85\times10^{-12})(0.020))\approx1.8\times10^7\,\mathrm{N/C}\)."],
                "pem-line-charge-w6",
                3,
            ),
            (
                "mcq",
                r"A solid nonconducting sphere of radius \(R\) has uniform volume charge density. Inside (\(r<R\)), the field magnitude varies as",
                [r"A) \(1/r^2\)", r"B) \(r\)", "C) constant", r"D) \(1/r\)"],
                1,
                [r"Enclosed charge \(Q_{\mathrm{enc}}\propto r^3\).", r"Gauss gives \(E\propto Q_{\mathrm{enc}}/r^2\propto r\)."],
                "pem-sphere-field-w6",
                2,
            ),
            (
                "frq",
                r"Two large parallel plates separated by \(1.5\,\mathrm{cm}\) have uniform fields \(E=4.0\times10^4\,\mathrm{N/C}\) pointing from the positive plate to the negative plate. Find the potential difference and the work done moving \(+3.0\,\mu\mathrm C\) from the negative plate to the positive plate (against the field).",
                [r"\(\Delta V=Ed\) for uniform field.", r"\(W=q\Delta V\) with sign for direction against field."],
                [r"\(\Delta V=(4.0\times10^4)(0.015)=600\,\mathrm V\).", r"Moving + charge against field to higher potential: \(W=q\Delta V=(3.0\times10^{-6})(600)=1.8\times10^{-3}\,\mathrm J\)."],
                "pem-plate-potential-w6",
                2,
            ),
        ],
    },
    {
        "label": "6B",
        "subject": "AP Physics C: E&M",
        "topic": "RC Circuits and Inductance",
        "description": "Original practice with RC time constants, LR transients, and stored energy.",
        "topic_tags": ["ap-physics-c-em", "circuits", "unit-10"],
        "items": [
            (
                "mcq",
                r"A \(10\,\mu\mathrm F\) capacitor charges through a \(2.0\,\mathrm{k\Omega}\) resistor from a \(12\,\mathrm V\) battery. The time constant is",
                [r"A) \(2.0\times10^{-5}\,\mathrm s\)", r"B) \(2.0\times10^{-2}\,\mathrm s\)", r"C) \(0.20\,\mathrm s\)", r"D) \(20\,\mathrm s\)"],
                1,
                [r"\(\tau=RC\).", r"\(\tau=(2.0\times10^3)(10\times10^{-6})=2.0\times10^{-2}\,\mathrm s\)."],
                "pem-rc-tau-w6",
                2,
            ),
            (
                "frq",
                r"In the same RC circuit, how long until the capacitor voltage reaches \(75\%\) of \(12\,\mathrm V\)? Use \(V=V_s(1-e^{-t/\tau})\).",
                [r"Set \(V/V_s=0.75\).", r"\(t=-\tau\ln(1-0.75)\)."],
                [r"\(t=-(2.0\times10^{-2})\ln(0.25)\approx2.77\times10^{-2}\,\mathrm s\)."],
                "pem-rc-charge-w6",
                2,
            ),
            (
                "mcq",
                r"An ideal inductor \(L=0.40\,\mathrm H\) carries current increasing at \(2.5\,\mathrm{A/s}\). The magnitude of the induced emf is",
                [r"A) \(0.16\,\mathrm V\)", r"B) \(1.0\,\mathrm V\)", r"C) \(1.6\,\mathrm V\)", r"D) \(16\,\mathrm V\)"],
                1,
                [r"\(|\mathcal E|=L|dI/dt|\).", r"\(|\mathcal E|=(0.40)(2.5)=1.0\,\mathrm V\)."],
                "pem-inductor-emf-w6",
                2,
            ),
            (
                "frq",
                r"A \(5.0\,\mathrm{mH}\) inductor and \(20\,\Omega\) resistor are in series with a \(9.0\,\mathrm V\) battery (\(t=0\) current zero). Find \(\tau=L/R\) and the current after one time constant.",
                [r"LR growth: \(I=(\mathcal E/R)(1-e^{-t/\tau})\).", r"At \(t=\tau\), current is \(1-e^{-1}\) of maximum."],
                [r"\(\tau=0.005/20=2.5\times10^{-4}\,\mathrm s\).", r"\(I_{\max}=9/20=0.45\,\mathrm A\); \(I(\tau)=0.45(1-e^{-1})\approx0.28\,\mathrm A\)."],
                "pem-lr-circuit-w6",
                3,
            ),
        ],
    },
    # ── AP Calculus AB/BC ──
    {
        "label": "6A",
        "subject": "AP Calculus AB/BC",
        "topic": "Integration Applications",
        "description": "Original practice with area, volume, and average value.",
        "topic_tags": ["ap-calculus", "integration", "unit-8"],
        "items": [
            (
                "mcq",
                r"The region bounded by \(y=x^2\) and \(y=4\) is revolved about the \(x\)-axis. The volume is",
                [r"A) \(\dfrac{128\pi}{5}\)", r"B) \(\dfrac{256\pi}{5}\)", r"C) \(32\pi\)", r"D) \(64\pi\)"],
                1,
                [r"Washers: outer \(R=2\), inner \(r=x\).", r"\(V=\pi\int_{-2}^{2}(4-x^2)\,dx=\pi[4x-x^3/3]_{-2}^{2}=256\pi/5\)."],
                "calc-washer-volume-w6",
                3,
            ),
            (
                "frq",
                r"Find the area of the region enclosed by \(y=\sin x\) and \(y=\cos x\) on \([0,\pi/2]\).",
                [r"Find intersection: \(\cos x=\sin x\Rightarrow x=\pi/4\).", r"Split integral where \(\cos x\ge\sin x\) vs opposite.", r"\(\int|\cos x-\sin x|\,dx\)."],
                [r"Area \(=\int_0^{\pi/4}(\cos x-\sin x)\,dx+\int_{\pi/4}^{\pi/2}(\sin x-\cos x)\,dx\).", r"\(=2\sqrt2-2\approx0.828\)."],
                "calc-trig-area-w6",
                3,
            ),
            (
                "mcq",
                r"The average value of \(f(x)=x^2+1\) on \([0,3]\) is",
                [r"A) \(4\)", r"B) \(5\)", r"C) \(6\)", r"D) \(10\)"],
                0,
                [r"\(f_{\mathrm{avg}}=\dfrac1{b-a}\int_a^b f(x)\,dx\).", r"\(\dfrac1{3}\int_0^3(x^2+1)\,dx=\dfrac1{3}[9+3]=4\)."],
                "calc-average-value-w6",
                2,
            ),
            (
                "frq",
                r"Set up (and evaluate) the integral for the arc length of \(y=\tfrac23x^{3/2}\) from \(x=0\) to \(x=4\).",
                [r"\(L=\int\sqrt{1+(dy/dx)^2}\,dx\).", r"\(dy/dx=\sqrt x\).", "Evaluate the definite integral."],
                [r"\(L=\int_0^4\sqrt{1+x}\,dx=\left[\tfrac{2}{3}(1+x)^{3/2}\right]_0^4=\tfrac{2}{3}(125-1)=\tfrac{248}{3}\)."],
                "calc-arc-length-w6",
                3,
            ),
        ],
    },
    {
        "label": "6B",
        "subject": "AP Calculus AB/BC",
        "topic": "Series and Parametric Motion",
        "description": "Original BC-level practice with Taylor polynomials and parametric derivatives.",
        "topic_tags": ["ap-calculus", "series", "unit-10"],
        "items": [
            (
                "mcq",
                r"The Maclaurin polynomial of degree 2 for \(f(x)=e^x\) is",
                [r"A) \(1+x\)", r"B) \(1+x+\tfrac{x^2}{2}\)", r"C) \(1+x+x^2\)", r"D) \(x+\tfrac{x^2}{2}\)"],
                1,
                [r"\(f(0)=1, f'(0)=1, f''(0)=1\).", r"\(P_2(x)=1+x+\tfrac12x^2\)."],
                "calc-maclaurin-w6",
                2,
            ),
            (
                "frq",
                r"Find the radius of convergence of \(\displaystyle\sum_{n=1}^{\infty}\frac{(x-2)^n}{n\cdot3^n}\) using the ratio test.",
                [r"Apply ratio test to \(|a_{n+1}/a_n|\).", r"Set limit \(<1\) and solve for \(|x-2|\)."],
                [r"\(\left|\dfrac{x-2}{3}\right|<1\Rightarrow |x-2|<3\); radius \(R=3\)."],
                "calc-ratio-test-w6",
                3,
            ),
            (
                "mcq",
                r"A particle moves with \(x(t)=t^2\) and \(y(t)=t^3\). At \(t=1\), the speed is",
                [r"A) \(\sqrt5\)", r"B) \(\sqrt{13}\)", r"C) \(5\)", r"D) \(13\)"],
                1,
                [r"\(v=\sqrt{(dx/dt)^2+(dy/dt)^2}\).", r"At \(t=1\): \(dx/dt=2, dy/dt=3\Rightarrow v=\sqrt{13}\)."],
                "calc-parametric-speed-w6",
                2,
            ),
            (
                "frq",
                r"Determine whether \(\displaystyle\sum_{n=1}^{\infty}\frac{(-1)^{n+1}}{\sqrt n}\) converges absolutely, conditionally, or diverges.",
                [r"Alternating series test for convergence.", r"Compare \(\sum 1/\sqrt n\) for absolute convergence (p-test)."],
                [r"Alternating series converges (terms decrease to 0).", r"\(\sum 1/\sqrt n\) diverges (\(p=1/2\)); series converges conditionally."],
                "calc-alternating-series-w6",
                3,
            ),
        ],
    },
    # ── AP Statistics ──
    {
        "label": "6A",
        "subject": "AP Statistics",
        "topic": "Inference for Means",
        "description": "Original practice with one- and two-sample t procedures.",
        "topic_tags": ["ap-statistics", "inference", "unit-7"],
        "items": [
            (
                "mcq",
                r"An SRS of \(n=25\) yields \(\bar x=118\) and \(s=15\). A 95% one-sample \(t\) interval for \(\mu\) uses",
                [r"A) \(118\pm1.96(15/\sqrt{25})\)", r"B) \(118\pm2.064(15/\sqrt{25})\)", r"C) \(118\pm2.064(15)\)", r"D) \(118\pm1.96(15)\)"],
                1,
                [r"Use \(t^*\) with \(df=24\) for 95% confidence.", r"Standard error is \(s/\sqrt n\), not \(s\)."],
                "stats-one-mean-ci-w6",
                2,
            ),
            (
                "frq",
                r"Two independent groups: \(n_1=20,\ \bar x_1=72,\ s_1=8\); \(n_2=22,\ \bar x_2=65,\ s_2=7\). Construct a 90% confidence interval for \(\mu_1-\mu_2\) (technology gives \(t^*=1.684\), \(df\approx39\)).",
                [r"Check independence and approximate normality.", r"Point estimate \(\bar x_1-\bar x_2\).", r"SE \(=\sqrt{s_1^2/n_1+s_2^2/n_2}\)."],
                [r"Estimate \(=7\).", r"SE \(\approx\sqrt{64/20+49/22}\approx2.47\); interval \(7\pm1.684(2.47)\approx(2.8,11.2)\)."],
                "stats-two-mean-ci-w6",
                3,
            ),
            (
                "mcq",
                r"A paired \(t\) test is appropriate when",
                ["A) two independent SRSs measure the same variable.", "B) the same subjects are measured before and after treatment.", "C) sample sizes must be equal.", r"D) population \(\sigma\) is known."],
                1,
                ["Paired design analyzes differences within matched pairs.", "Independence is within-pair; the parameter is a mean difference."],
                "stats-paired-design-w6",
                1,
            ),
            (
                "frq",
                r"Test \(H_0:\mu_d=0\) vs \(H_a:\mu_d>0\) for paired differences with \(n=12\), \(\bar d=1.8\), \(s_d=2.4\). Report the test statistic and state whether \(p<0.05\) using \(t^*=1.796\) at \(\alpha=0.05\).",
                [r"\(t=\bar d/(s_d/\sqrt n)\).", r"Compare to one-sided critical value \(df=11\)."],
                [r"\(t=1.8/(2.4/\sqrt{12})\approx2.60\).", r"\(2.60>1.796\Rightarrow\) reject \(H_0\) at 5% (evidence mean improvement exceeds 0)."],
                "stats-paired-test-w6",
                3,
            ),
        ],
    },
    {
        "label": "6B",
        "subject": "AP Statistics",
        "topic": "Chi-Square and Regression",
        "description": "Original practice with chi-square tests and regression inference.",
        "topic_tags": ["ap-statistics", "chi-square", "unit-8"],
        "items": [
            (
                "mcq",
                r"A chi-square test of independence on a \(3\times4\) table has \(df=\)",
                ["A) 5", "B) 6", "C) 11", "D) 12"],
                1,
                [r"\(df=(r-1)(c-1)\).", r"\((3-1)(4-1)=6\)."],
                "stats-chi-df-w6",
                2,
            ),
            (
                "frq",
                r"Observed counts for a die: 12, 18, 22, 16, 14, 18 (\(n=100\)). Compute \(\chi^2\) for goodness of fit to a fair die and state \(df\).",
                [r"Expected count \(E=100/6\) for each face.", r"\(\chi^2=\sum(O-E)^2/E\)."],
                [r"\(E\approx16.67\).", r"\(\chi^2\approx4.0\) (approx); \(df=5\). Compare to table as follow-up in context."],
                "stats-gof-die-w6",
                2,
            ),
            (
                "mcq",
                r"In regression, a residual plot showing a clear U-shape suggests",
                ["A) linear model is adequate.", "B) correlation equals causation.", "C) a nonlinear model may fit better.", r"D) \(r^2=0\)."],
                2,
                ["Systematic curvature in residuals violates linearity.", "Consider a transformed or higher-order model."],
                "stats-residual-plot-w6",
                2,
            ),
            (
                "frq",
                r"For LSRL \(\hat y=40+3.5x\) with \(n=30\), \(s=6\), and \(\sum(x_i-\bar x)^2=200\), find the standard error of the slope and a 95% CI for \(\beta\) (\(t^*=2.048\)).",
                [r"\(SE_b=s/\sqrt{\sum(x_i-\bar x)^2}\).", r"CI \(b\pm t^*SE_b\)."],
                [r"\(SE_b=6/\sqrt{200}\approx0.424\).", r"CI \(3.5\pm2.048(0.424)\approx(2.63,4.37)\)."],
                "stats-slope-ci-w6",
                3,
            ),
        ],
    },
    # ── AP Chemistry ──
    {
        "label": "6A",
        "subject": "AP Chemistry",
        "topic": "Kinetics and Equilibrium",
        "description": r"Original practice with rate laws, ICE tables, and \(K_c\).",
        "topic_tags": ["ap-chemistry", "kinetics", "unit-5"],
        "items": [
            (
                "mcq",
                r"For \(2\,\mathrm{NOCl}(g)\rightleftharpoons2\,\mathrm{NO}(g)+\mathrm{Cl}_2(g)\), the rate of disappearance of NOCl is \(0.040\,\mathrm{M/s}\). The rate of formation of \(\mathrm{Cl}_2\) is",
                [r"A) \(0.010\,\mathrm{M/s}\)", r"B) \(0.020\,\mathrm{M/s}\)", r"C) \(0.040\,\mathrm{M/s}\)", r"D) \(0.080\,\mathrm{M/s}\)"],
                1,
                [r"Stoichiometry: \(\Delta[\mathrm{Cl}_2]/\Delta t=\tfrac12|\Delta[\mathrm{NOCl}]/\Delta t|\).", r"\(0.040/2=0.020\,\mathrm{M/s}\)."],
                "chem-rate-stoich-w6",
                2,
            ),
            (
                "frq",
                r"\(\mathrm{N}_2(g)+3\,\mathrm{H}_2(g)\rightleftharpoons2\,\mathrm{NH}_3(g)\). At equilibrium, \([\mathrm{N}_2]=0.50\,\mathrm M\), \([\mathrm{H}_2]=1.50\,\mathrm M\), \([\mathrm{NH}_3]=0.40\,\mathrm M\). Find \(K_c\).",
                [r"Write \(K_c=[\mathrm{NH}_3]^2/([\mathrm{N}_2][\mathrm{H}_2]^3)\).", "Substitute equilibrium concentrations."],
                [r"\(K_c=(0.40)^2/((0.50)(1.50)^3)\approx0.047\)."],
                "chem-kc-ammonia-w6",
                2,
            ),
            (
                "mcq",
                r"A reaction is first order in A with \(k=0.693\,\mathrm{s^{-1}}\). The half-life is closest to",
                [r"A) \(0.693\,\mathrm s\)", r"B) \(1.0\,\mathrm s\)", r"C) \(1.44\,\mathrm s\)", r"D) \(10\,\mathrm s\)"],
                1,
                [r"First-order: \(t_{1/2}=\ln2/k\).", r"\(t_{1/2}=0.693/0.693=1.0\,\mathrm s\)."],
                "chem-half-life-w6",
                2,
            ),
            (
                "frq",
                r"For \(\mathrm{PCl}_5(g)\rightleftharpoons\mathrm{PCl}_3(g)+\mathrm{Cl}_2(g)\), \(K_c=0.040\) at a certain \(T\). If \([\mathrm{PCl}_5]=0.20\,\mathrm M\) and \([\mathrm{PCl}_3]=[\mathrm{Cl}_2]=0.10\,\mathrm M\), predict the direction of shift to reach equilibrium.",
                [r"Compute reaction quotient \(Q\).", r"Compare \(Q\) to \(K_c\)."],
                [r"\(Q=(0.10)(0.10)/0.20=0.050\).", r"\(Q>K_c\Rightarrow\) reaction shifts left (toward \(\mathrm{PCl}_5\))."],
                "chem-reaction-quotient-w6",
                2,
            ),
        ],
    },
    {
        "label": "6B",
        "subject": "AP Chemistry",
        "topic": "Electrochemistry and Thermochemistry",
        "description": r"Original practice with cell potential, Nernst equation, and \(\Delta G\).",
        "topic_tags": ["ap-chemistry", "electrochemistry", "unit-9"],
        "items": [
            (
                "mcq",
                r"Given \(E^\circ_{\mathrm{cell}}=+1.10\,\mathrm V\) for a galvanic cell, which statement is correct at standard conditions?",
                [r"A) \(\Delta G^\circ>0\)", r"B) \(K<1\)", "C) The reaction is spontaneous under standard conditions.", "D) Electrons flow from cathode to anode in the wire."],
                2,
                [r"\(\Delta G^\circ=-nFE^\circ\); positive \(E^\circ\) means spontaneous.", "Electrons flow from anode to cathode externally."],
                "chem-cell-spontaneous-w6",
                2,
            ),
            (
                "frq",
                r"For \( \mathrm{Zn^{2+}+2e^-\rightarrow Zn}\) (\(E^\circ=-0.76\,\mathrm V\)) and \(\mathrm{Cu^{2+}+2e^-\rightarrow Cu}\) (\(E^\circ=+0.34\,\mathrm V\)), find \(E^\circ_{\mathrm{cell}}\) for the galvanic \(\mathrm{Zn|Zn^{2+}||Cu^{2+}|Cu}\) cell and \(\Delta G^\circ\) (\(n=2\), \(F=96500\,\mathrm{C/mol}\)).",
                [r"\(E^\circ_{\mathrm{cell}}=E^\circ_{\mathrm{cathode}}-E^\circ_{\mathrm{anode}}\).", r"\(\Delta G^\circ=-nFE^\circ\)."],
                [r"\(E^\circ=0.34-(-0.76)=1.10\,\mathrm V\).", r"\(\Delta G^\circ=-2(96500)(1.10)\approx-2.12\times10^5\,\mathrm{J/mol}\)."],
                "chem-delta-g-cell-w6",
                2,
            ),
            (
                "mcq",
                r"At nonstandard conditions, as \([\mathrm{Cu^{2+}}]\) increases relative to \([\mathrm{Zn^{2+}}]\), \(E_{\mathrm{cell}}\) will",
                ["A) increase", "B) decrease", r"C) stay exactly at \(E^\circ\)", "D) become zero always"],
                0,
                [r"Nernst: increasing product of reduction quotient for cathode reactant raises potential.", r"Higher \([\mathrm{Cu^{2+}}]\) favors the forward cell reaction."],
                "chem-nernst-trend-w6",
                2,
            ),
            (
                "frq",
                r"A student mixes \(50.0\,\mathrm{mL}\) of \(0.200\,\mathrm M\ \mathrm{HCl}\) with \(50.0\,\mathrm{mL}\) of \(0.200\,\mathrm M\ \mathrm{NaOH}\) in a coffee-cup calorimeter. Total \(\Delta T=6.20\,\mathrm K\), solution mass \(100\,\mathrm g\), \(c=4.18\,\mathrm{J/(g\,K)}\). Find \(q\) and approximate \(\Delta H\) per mole of water formed.",
                [r"\(q=mc\Delta T\).", r"Moles of water formed from limiting neutralization.", r"\(\Delta H\approx q/n\)."],
                [r"\(q=(100)(4.18)(6.20)\approx2.59\times10^3\,\mathrm J\).", r"\(n=0.0100\,\mathrm{mol}\Rightarrow\Delta H\approx-2.59\times10^5\,\mathrm{J/mol}\) (exothermic)."],
                "chem-calorimetry-w6",
                3,
            ),
        ],
    },
    # ── AP Biology ──
    {
        "label": "6A",
        "subject": "AP Biology",
        "topic": "Enzyme Kinetics and Energetics",
        "description": "Original practice with enzyme rates, ATP, and cellular respiration yields.",
        "topic_tags": ["ap-biology", "energetics", "unit-3"],
        "items": [
            (
                "mcq",
                r"An enzyme's reaction rate levels off at high substrate concentration primarily because",
                ["A) the active sites are saturated.", "B) the enzyme is denatured.", r"C) \(\Delta G\) becomes positive.", "D) product inhibition is impossible."],
                0,
                [r"At high \([S]\), essentially all enzyme is ES complex.", "Further increases in substrate cannot increase rate until more enzyme is added."],
                "bio-enzyme-saturation-w6",
                1,
            ),
            (
                "frq",
                r"A yeast culture produces \(0.48\,\mathrm{mol}\) \(\mathrm{CO}_2\) from glucose fermentation. How many moles of glucose were consumed, and how many moles of ATP (net) are expected under ideal fermentation?",
                [r"Fermentation: 1 glucose \(\rightarrow\) 2 pyruvate \(\rightarrow\) 2 ethanol + 2 CO\(_2\) (net).", r"Relate moles CO\(_2\) to glucose.", r"Net ATP from glycolysis only."],
                [r"\(0.48\,\mathrm{mol}\ \mathrm{CO}_2\Rightarrow0.24\,\mathrm{mol}\) glucose.", r"Net \(2\) ATP per glucose \(\Rightarrow0.48\,\mathrm{mol}\) ATP (ideal)."],
                "bio-fermentation-yield-w6",
                2,
            ),
            (
                "mcq",
                r"Competitive inhibition differs from noncompetitive inhibition because competitive inhibitors",
                ["A) bind the active site and can be outcompeted by substrate.", "B) always denature the enzyme.", r"C) lower \(V_{\max}\) without affecting \(K_m\).", "D) bind only at allosteric sites."],
                0,
                ["Competitive inhibitors resemble substrate and compete for active site.", r"Noncompetitive often lowers \(V_{\max}\)."],
                "bio-inhibition-w6",
                2,
            ),
            (
                "frq",
                r"In an experiment, chloroplasts evolve \(O_2\) at \(12\,\mu\mathrm{mol/h}\) under saturating light. Estimate \(\mu\mathrm{mol}\) glucose equivalent fixed per hour (assume linear electron flow and 6 CO\(_2\) per glucose).",
                [r"Photosynthesis: 6 CO\(_2\) + 6 H\(_2\)O \(\rightarrow\) glucose + 6 O\(_2\).", r"Scale O\(_2\) production to glucose."],
                [r"\(12\,\mu\mathrm{mol}\ O_2/h\Rightarrow2\,\mu\mathrm{mol}\) glucose equivalent/h."],
                "bio-photosynthesis-stoich-w6",
                2,
            ),
        ],
    },
    {
        "label": "6B",
        "subject": "AP Biology",
        "topic": "Population Genetics and Ecology",
        "description": "Original practice with Hardy-Weinberg, selection, and population growth.",
        "topic_tags": ["ap-biology", "genetics", "unit-7"],
        "items": [
            (
                "mcq",
                r"In a large randomly mating population, \(16\%\) show a recessive phenotype. The frequency of carriers (\(Aa\)) is closest to",
                ["A) 0.16", "B) 0.32", "C) 0.48", "D) 0.68"],
                2,
                [r"\(q^2=0.16\Rightarrow q=0.4, p=0.6\).", r"\(2pq=2(0.6)(0.4)=0.48\)."],
                "bio-hw-carriers-w6",
                2,
            ),
            (
                "frq",
                r"A lake fish population has carrying capacity \(K=5000\) and intrinsic rate \(r=0.40\,\mathrm{yr^{-1}}\). Using logistic growth, find the population growth rate \(dN/dt\) when \(N=2500\).",
                [r"\(dN/dt=rN(1-N/K)\).", r"Substitute \(N=K/2\)."],
                [r"\(dN/dt=0.40(2500)(1-0.5)=500\) fish/year."],
                "bio-logistic-w6",
                2,
            ),
            (
                "mcq",
                r"Which condition is required for Hardy-Weinberg equilibrium?",
                ["A) Natural selection favoring heterozygotes", "B) No gene flow", "C) Nonrandom mating", "D) Small population size"],
                1,
                ["Hardy-Weinberg assumes no selection, no gene flow, random mating, large population, no mutation.", "Gene flow violation breaks equilibrium."],
                "bio-hw-conditions-w6",
                1,
            ),
            (
                "frq",
                r"In a chi-square test of genotype counts (AA, Aa, aa) expected under HW with \(p=0.7\), observed counts in \(n=200\) are 98, 84, 18. Compute expected counts and \(\chi^2\) (show setup).",
                [r"\(E_{AA}=np^2,\ E_{Aa}=2npq,\ E_{aa}=nq^2\).", r"\(\chi^2=\sum(O-E)^2/E\)."],
                [r"\(q=0.3\Rightarrow E:98,84,18\) (matches observed here by construction—compute \(\chi^2\approx0\).)", r"If observed differed, plug into formula; small \(\chi^2\) supports HW."],
                "bio-chi-square-hw-w6",
                3,
            ),
        ],
    },
    # ── AP Macroeconomics ──
    {
        "label": "6A",
        "subject": "AP Macroeconomics",
        "topic": "GDP and Fiscal Multipliers",
        "description": "Original practice with expenditure approach, MPC, and multiplier effects.",
        "topic_tags": ["ap-macroeconomics", "gdp", "unit-2"],
        "items": [
            (
                "mcq",
                r"If \(C=200+0.75Y_d\), \(I=100\), \(G=225\), and \(T=100\) (lump-sum), equilibrium real GDP in a closed economy with no \(NX\) is",
                [r"A) \(1400\)", r"B) \(1600\)", r"C) \(1800\)", r"D) \(2000\)"],
                2,
                [r"\(Y=C+I+G\) with \(Y_d=Y-T\).", r"\(Y=200+0.75(Y-100)+100+225\Rightarrow0.25Y=450\Rightarrow Y=1800\)."],
                "macro-equilibrium-y-w6",
                2,
            ),
            (
                "frq",
                r"An economy has \(MPC=0.80\). Government spending increases by \(\$25\) billion with no tax change. Find the spending multiplier and the total change in equilibrium GDP.",
                [r"Spending multiplier \(=1/(1-MPC)\).", r"\(\Delta Y=\text{multiplier}\times\Delta G\)."],
                [r"Multiplier \(=1/0.20=5\).", r"\(\Delta Y=5(25)=\$125\) billion."],
                "macro-spending-multiplier-w6",
                2,
            ),
            (
                "mcq",
                r"In the expenditure approach, which is included in GDP?",
                ["A) Transfer payments", "B) Intermediate goods sold to a bakery", "C) A newly produced tractor sold to a farm", "D) Used car sale to a consumer"],
                2,
                ["GDP counts final goods and services produced domestically in the period.", "Tractor is a new capital good investment."],
                "macro-gdp-inclusion-w6",
                1,
            ),
            (
                "frq",
                r"Nominal GDP rises \(6\%\) and the GDP deflator rises \(4\%\). Approximate the real GDP growth rate and interpret.",
                [r"Approximate: \(\%\Delta\) real \(\approx\%\Delta\) nominal \(-\%\Delta\) deflator.", "Interpret in terms of output vs price level."],
                [r"Real growth \(\approx2\%\).", "Output grew modestly after removing average price increases."],
                "macro-real-nominal-w6",
                2,
            ),
        ],
    },
    {
        "label": "6B",
        "subject": "AP Macroeconomics",
        "topic": "Money, Phillips Curve, and Trade",
        "description": "Original practice with money multiplier, inflation-unemployment, and net exports.",
        "topic_tags": ["ap-macroeconomics", "money", "unit-4"],
        "items": [
            (
                "mcq",
                r"If the required reserve ratio is \(10\%\) and banks hold no excess reserves, the simple money multiplier is",
                [r"A) \(0.10\)", r"B) \(1.0\)", r"C) \(5.0\)", r"D) \(10\)"],
                3,
                [r"Simple multiplier \(=1/rr\).", r"\(1/0.10=10\)."],
                "macro-money-multiplier-w6",
                1,
            ),
            (
                "frq",
                r"The quantity equation is \(MV=PY\). If \(M\) grows \(8\%\), \(V\) is stable, and real output \(Y\) grows \(3\%\), predict the inflation rate.",
                [r"With stable \(V\), \(\%\Delta P\approx\%\Delta M-\%\Delta Y\).", "State assumption explicitly."],
                [r"Inflation \(\approx8\%-3\%=5\%\)."],
                "macro-quantity-equation-w6",
                2,
            ),
            (
                "mcq",
                r"A short-run Phillips curve shows",
                ["A) a positive relationship between unemployment and inflation.", "B) a negative relationship between unemployment and inflation.", "C) no relationship between unemployment and inflation.", "D) long-run vertical trade-offs always."],
                1,
                ["Short-run Phillips: lower unemployment associated with higher inflation.", "Long-run curve is vertical at natural rate."],
                "macro-phillips-w6",
                1,
            ),
            (
                "frq",
                r"A country has \(NX=-\$40\) billion, \(C=\$900\)B, \(I=\$250\)B, and \(G=\$210\)B. Find GDP in the expenditure approach and state one implication of negative net exports.",
                [r"\(Y=C+I+G+NX\).", r"Interpret \(NX<0\) as imports exceeding exports."],
                [r"\(Y=900+250+210-40=1320\) billion.", "Domestic spending exceeds production value from trade; foreign borrowing or asset sales may finance the gap."],
                "macro-nx-gdp-w6",
                2,
            ),
        ],
    },
    # ── AP Microeconomics ──
    {
        "label": "6A",
        "subject": "AP Microeconomics",
        "topic": "Elasticity and Surplus",
        "description": "Original practice with price elasticity, consumer/producer surplus, and tax incidence.",
        "topic_tags": ["ap-microeconomics", "elasticity", "unit-2"],
        "items": [
            (
                "mcq",
                r"Along a linear demand curve, price elasticity of demand is unit elastic at",
                ["A) the vertical intercept", "B) the midpoint", "C) the horizontal intercept", "D) every point"],
                1,
                [r"At the midpoint of a linear demand curve, \(|\epsilon|=1\).", "Elastic above midpoint, inelastic below."],
                "micro-unit-elastic-w6",
                2,
            ),
            (
                "frq",
                r"Demand is \(Q_d=120-2P\) and supply is \(Q_s=3P-30\). Find equilibrium price and quantity, then compute consumer surplus (triangle above price, below demand).",
                [r"Set \(Q_d=Q_s\).", r"CS \(=\tfrac12(\text{vertical intercept difference})(Q^*)\)."],
                [r"\(120-2P=3P-30\Rightarrow P=30,\ Q=60\).", r"Demand choke price 60; CS \(=\tfrac12(60-30)(60)=900\)."],
                "micro-cs-w6",
                2,
            ),
            (
                "mcq",
                r"If demand is more inelastic than supply, an excise tax falls mainly on",
                ["A) consumers", "B) producers", "C) neither side", "D) the government only"],
                0,
                ["Relative inelasticity determines tax burden.", "More inelastic side pays larger share."],
                "micro-tax-incidence-w6",
                2,
            ),
            (
                "frq",
                r"Income rises from \(\$40{,}000\) to \(\$50{,}000\) and quantity demanded of a good rises from 80 to 92. Compute income elasticity and classify the good.",
                [r"\(E_I=(\%\Delta Q)/(\%\Delta I)\).", r"Normal if positive; luxury if \(E_I>1\)."],
                [r"\(\%\Delta Q=15\%,\ \%\Delta I=25\%\Rightarrow E_I=0.60\).", "Normal necessity (positive but less than 1)."],
                "micro-income-elasticity-w6",
                2,
            ),
        ],
    },
    {
        "label": "6B",
        "subject": "AP Microeconomics",
        "topic": "Market Power and Welfare",
        "description": "Original practice with monopoly pricing, deadweight loss, and externalities.",
        "topic_tags": ["ap-microeconomics", "market-structure", "unit-4"],
        "items": [
            (
                "mcq",
                r"A profit-maximizing monopolist produces where",
                [r"A) \(P=MC\)", r"B) \(MR=MC\)", r"C) \(MR=0\)", r"D) \(AVC=MC\)"],
                1,
                [r"Monopoly chooses \(Q\) where \(MR=MC\).", "Price read from demand at that quantity."],
                "micro-monopoly-rule-w6",
                1,
            ),
            (
                "frq",
                r"A monopolist faces \(P=100-2Q\) and \(TC=20Q+200\). Find \(MR\), \(MC\), profit-maximizing \(Q\) and \(P\), and economic profit.",
                [r"\(TR=PQ\Rightarrow MR=100-4Q\); \(MC=20\).", r"Set \(MR=MC\); profit \(=TR-TC\)."],
                [r"\(100-4Q=20\Rightarrow Q=20,\ P=60\).", r"Profit \(=60(20)-[20(20)+200]=400\)."],
                "micro-monopoly-profit-w6",
                3,
            ),
            (
                "mcq",
                r"A negative production externality causes the market quantity to be",
                ["A) less than the socially optimal quantity.", "B) equal to the socially optimal quantity.", "C) greater than the socially optimal quantity.", "D) zero always."],
                2,
                ["Private marginal cost < social marginal cost.", "Market overproduces relative to social optimum."],
                "micro-externality-w6",
                2,
            ),
            (
                "frq",
                r"Perfect competition: \(P=\$12\), a firm's \(MC=2+0.5Q\). If \(Q=20\), should the firm expand output in the short run? Compute \(MR\) and compare to \(MC\) at \(Q=20\).",
                [r"In perfect competition, \(MR=P\).", r"Expand if \(MR>MC\) at current \(Q\)."],
                [r"\(MR=12\); \(MC=2+0.5(20)=12\).", r"\(MR=MC\): profit-maximizing at \(Q=20\); no incentive to expand further."],
                "micro-competitive-output-w6",
                2,
            ),
        ],
    },
    # ── AP Environmental Science ──
    {
        "label": "6A",
        "subject": "AP Environmental Science",
        "topic": "Energy and Carbon",
        "description": "Original practice with power, efficiency, and carbon footprint calculations.",
        "topic_tags": ["ap-environmental-science", "energy", "unit-6"],
        "items": [
            (
                "mcq",
                r"A coal plant generates \(600\,\mathrm{MW}\) while consuming \(1500\,\mathrm{MW}\) of fuel energy. Its useful energy efficiency is",
                [r"A) \(25\%\)", r"B) \(40\%\)", r"C) \(60\%\)", r"D) \(250\%\)"],
                1,
                [r"Efficiency \(=\text{useful output}/\text{input}\).", r"\(600/1500=0.40=40\%\)."],
                "env-energy-efficiency-w6",
                1,
            ),
            (
                "frq",
                r"A home uses \(900\,\mathrm{kWh}\)/month from a grid with \(0.45\,\mathrm{kg\ CO_2/kWh}\). How many metric tons of CO\(_2\) are emitted in one year?",
                [r"Annual kWh \(=12\times900\).", r"Mass \(=\) kWh \(\times\) emission factor; convert kg to metric tons."],
                [r"Annual kWh \(=10800\).", r"Mass \(=10800(0.45)=4860\,\mathrm{kg}\approx4.9\) metric tons."],
                "env-carbon-footprint-w6",
                2,
            ),
            (
                "mcq",
                r"Which change most directly reduces tropospheric ozone formation in an urban area?",
                [r"A) Increasing NO\(_x\) without changing VOCs", "B) Reducing VOC emissions from solvents and vehicles", "C) Adding leaded gasoline", "D) Increasing stratospheric chlorine"],
                1,
                [r"Ground-level ozone forms from NO\(_x\) and VOCs in sunlight.", "Cutting VOCs lowers ozone production."],
                "env-ozone-precursors-w6",
                2,
            ),
            (
                "frq",
                r"A \(2.0\,\mathrm{kW}\) heater runs \(5.0\) hours/day for 30 days. If electricity costs \(\$0.14/\mathrm{kWh}\), find total energy (kWh) and cost.",
                [r"Energy \(=\) power \(\times\) time.", r"Cost \(=\) kWh \(\times\) rate."],
                [r"Daily kWh \(=2.0(5)=10\); monthly \(=300\,\mathrm{kWh}\).", r"Cost \(=300(0.14)=\$42\)."],
                "env-power-cost-w6",
                1,
            ),
        ],
    },
    {
        "label": "6B",
        "subject": "AP Environmental Science",
        "topic": "Water and Toxicology",
        "description": "Original practice with LD50, water treatment, and nutrient pollution.",
        "topic_tags": ["ap-environmental-science", "pollution", "unit-8"],
        "items": [
            (
                "mcq",
                r"A pesticide has \(\mathrm{LD50}=5\,\mathrm{mg/kg}\) for rats. Compared to one with \(\mathrm{LD50}=50\,\mathrm{mg/kg}\), the first pesticide is",
                ["A) less toxic", "B) more toxic", "C) equally toxic", "D) not comparable"],
                1,
                ["Lower LD50 means less dose needed to kill 50% of test population.", "Therefore more toxic."],
                "env-ld50-w6",
                1,
            ),
            (
                "frq",
                r"A lake receives phosphate runoff raising concentration from \(0.010\,\mathrm{mg/L}\) to \(0.035\,\mathrm{mg/L}\). Explain one ecological chain leading to a fish kill after an algal bloom.",
                [r"Excess P \(\rightarrow\) algal bloom.", r"Decomposition depletes dissolved oxygen.", "Link to fish mortality."],
                [r"Phosphate fuels rapid algal growth.", r"Nighttime bacterial decomposition drops DO below levels needed by fish, causing die-off."],
                "env-eutrophication-w6",
                2,
            ),
            (
                "mcq",
                r"Bioaccumulation differs from biomagnification because bioaccumulation",
                ["A) occurs only in water", "B) is storage in one organism over time", "C) always reduces toxin concentration up the food chain", "D) applies only to metals"],
                1,
                ["Bioaccumulation: buildup within an individual.", "Biomagnification: increasing concentration at higher trophic levels."],
                "env-bioaccumulation-w6",
                2,
            ),
            (
                "frq",
                r"A factory must reduce BOD discharge from \(120\,\mathrm{mg/L}\) to \(30\,\mathrm{mg/L}\) at flow \(0.50\,\mathrm{m^3/s}\). Find the mass removal rate of oxygen-demanding waste (kg/day).",
                [r"Mass rate \(=\) concentration difference \(\times\) volumetric flow.", r"Convert mg/L·m\(^3\)/s to kg/day."],
                [r"\(\Delta\mathrm{BOD}=90\,\mathrm{mg/L}=0.090\,\mathrm{g/L}=0.090\,\mathrm{kg/m^3}\).", r"Mass rate \(=0.090(0.50)(86400)\approx3888\,\mathrm{kg/day}\)."],
                "env-bod-removal-w6",
                3,
            ),
        ],
    },
    # ── AP Computer Science A ──
    {
        "label": "6A",
        "subject": "AP Computer Science A",
        "topic": "Arrays and ArrayLists",
        "description": "Original practice with traversal, shifting, and runtime reasoning.",
        "topic_tags": ["ap-computer-science-a", "arrays", "unit-6"],
        "items": [
            (
                "mcq",
                r"What is printed?\n```java\nint[] a = {3,1,4,1,5};\nint s=0;\nfor (int v : a) if (v%2==0) s+=v;\nSystem.out.print(s);\n```",
                ["A) 4", "B) 8", "C) 14", "D) 16"],
                0,
                ["Sum even entries: 4 only.", "Output is 4."],
                "csa-array-sum-w6",
                1,
            ),
            (
                "frq",
                r"Write the value returned by `countAbove(int[] scores, int target)` that returns how many scores are strictly greater than `target`. Trace on `{88,72,91,72,65}` with `target=72`.",
                [r"Initialize count \(=0\).", r"Loop: increment when `scores[i] > target`.", "Trace each comparison."],
                [r"Matches at indices 0 and 2 only.", r"Returns `2`."],
                "csa-count-above-w6",
                2,
            ),
            (
                "mcq",
                r"After `ArrayList<String> w = new ArrayList<>(); w.add(\"a\"); w.add(\"b\"); w.add(1,\"c\");`, what is `w.get(1)`?",
                ["A) a", "B) b", "C) c", "D) IndexOutOfBoundsException"],
                2,
                [r"`add(1,\"c\")` inserts at index 1, shifting `b` right.", r"List is [a,c,b]; index 1 is c."],
                "csa-arraylist-insert-w6",
                1,
            ),
            (
                "frq",
                r"Describe the result of shifting all elements one index to the right in `int[] data` of length `n`, storing the last element at index 0 (rotate right by 1). Trace `{10,20,30,40}`.",
                [r"Save last element.", r"Shift indices \(n-1\) down to 1.", r"Place saved value at index 0."],
                [r"Save 40; shift 30→3, 20→2, 10→1.", r"Result `{40,10,20,30}`."],
                "csa-rotate-right-w6",
                2,
            ),
        ],
    },
    {
        "label": "6B",
        "subject": "AP Computer Science A",
        "topic": "Recursion and Classes",
        "description": "Original practice with recursive tracing and basic OOP design.",
        "topic_tags": ["ap-computer-science-a", "recursion", "unit-5"],
        "items": [
            (
                "mcq",
                r"What does `f(4)` return?\n```java\nstatic int f(int n){\n  if (n<=1) return 1;\n  return n+f(n-2);\n}\n```",
                ["A) 4", "B) 7", "C) 8", "D) 10"],
                1,
                [r"\(f(4)=4+f(2)\); \(f(2)=2+f(0)=2+1=3\).", r"\(f(4)=7\)."],
                "csa-recursion-trace-w6",
                2,
            ),
            (
                "frq",
                r"Write the sequence of printed values for `printBinary(5)` if the method prints remainders `%2` before dividing `n/2` recursively (preorder on remainders).",
                [r"Preorder: print `n%2`, then recurse on `n/2` until 0.", "Trace divisions."],
                [r"\(5\to2\to1\to0\): remainders 1,0,1.", r"Prints `1 0 1` (binary 101)."],
                "csa-print-binary-w6",
                2,
            ),
            (
                "mcq",
                r"A class `Point` has private `x,y` and a constructor `Point(int a,int b)`. Which enables creating `new Point(3,4)` from outside the class?",
                ["A) `public Point(int a,int b){x=a;y=b;}`", "B) `private Point(int a,int b){...}`", "C) No constructor (default only)", "D) `void Point(int a,int b){...}`"],
                0,
                ["Constructor must be public for external instantiation.", "Name matches class; no return type."],
                "csa-constructor-w6",
                1,
            ),
            (
                "frq",
                r"`BankAccount` has private `balance` and methods `deposit(int amt)` and `withdraw(int amt)` that reject negative amounts and overdrafts. If balance starts at 200, after `deposit(50)` and `withdraw(400)` then `withdraw(30)`, what is the final balance?",
                [r"Apply operations in order; enforce rules.", "Failed withdraw should not change balance."],
                [r"After deposit: 250.", r"Withdraw 400 fails; withdraw 30 succeeds → final balance 220."],
                "csa-bank-account-w6",
                2,
            ),
        ],
    },
]
