/**
 * Legacy generator — prefer editing data/english-questions-curated-extended.ts by hand.
 * Run: npm run generate:curated-extended
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(fileURLToPath(import.meta.url));

const TOEFL_SKILLS = [
  "Academic Reading",
  "Listening inference",
  "Listening purpose",
  "Writing coherence",
  "Speaking clarity",
  "Reading detail",
  "Grammar in context",
  "Academic Discussion",
  "Complete the Words",
] as const;

const SAT_SKILLS = [
  "Standard English Conventions",
  "Transitions",
  "Information and Ideas",
  "Expression of Ideas",
  "Central Ideas",
  "Algebra",
  "Data interpretation",
  "Rhetoric",
  "Linear equations",
  "Words in context",
] as const;

const TOEFL_TOPICS = [
  "campus housing",
  "renewable energy",
  "public health",
  "urban farming",
  "digital archives",
  "language acquisition",
  "microplastics",
  "sleep research",
  "volunteer programs",
  "museum attendance",
];

const SAT_TOPICS = [
  "community gardens",
  "library programs",
  "transit policy",
  "student journalism",
  "water conservation",
  "local elections",
  "science fairs",
  "music education",
  "coastal erosion",
  "small business grants",
];

function toeflItem(n: number) {
  const skill = TOEFL_SKILLS[n % TOEFL_SKILLS.length];
  const topic = TOEFL_TOPICS[n % TOEFL_TOPICS.length];
  if (skill === "Complete the Words") {
    const words = ["confirm", "analysis", "structure", "evidence", "research"];
    const w = words[n % words.length];
    const stem = w.slice(0, 3);
    return {
      id: `toefl-curated-ext-${n}`,
      skill,
      prompt: `Researchers could not yet con___${w.slice(3)} the ${topic} data without a larger sample.`,
      choices: [stem, "tra", "tre", "tro"],
      answer: 0,
      explanation: `The complete word is ${w}. Context supports a research finding that needs more data.`,
    };
  }
  if (skill === "Grammar in context") {
    const verbs = ["published", "analyzed", "reviewed", "presented"];
    const v = verbs[n % verbs.length];
    return {
      id: `toefl-curated-ext-${n}`,
      skill,
      prompt: `The team ___ its ${topic} report after revising the methodology.`,
      choices: ["publish", "publishes", v, "publishing"],
      answer: 2,
      explanation: `Past tense "${v}" fits a completed reporting action.`,
    };
  }
  return {
    id: `toefl-curated-ext-${n}`,
    skill,
    prompt: `A study of ${topic} found benefits in one area but no change in another. Which conclusion is best supported?`,
    choices: [
      "The study proves every outcome improved.",
      "The study supports a limited, balanced conclusion about trade-offs.",
      "The study shows research is useless.",
      "The study lasted only one day.",
    ],
    answer: 1,
    explanation:
      "When results are mixed, a balanced conclusion that matches both findings is best supported.",
  };
}

function satItem(n: number) {
  const skill = SAT_SKILLS[n % SAT_SKILLS.length];
  const topic = SAT_TOPICS[n % SAT_TOPICS.length];
  if (skill === "Algebra") {
    const a = n + 3;
    const b = a * 2 - 5;
    return {
      id: `sat-curated-ext-${n}`,
      skill,
      prompt: `If ${a}x + 7 = ${b}, what is x?`,
      choices: [`${a - 2}`, `${a}`, `${a + 1}`, `${a + 2}`],
      answer: 0,
      explanation: `Subtract 7 and divide by ${a}: x = ${a - 2}.`,
    };
  }
  if (skill === "Linear equations") {
    const m = n % 2 === 0 ? 2 : -2;
    const b = 5;
    return {
      id: `sat-curated-ext-${n}`,
      skill,
      prompt: `Which equation represents a line with slope ${m} and y-intercept ${b}?`,
      choices: [`y = ${m}x + ${b}`, `y = ${b}x + ${m}`, `y = ${-m}x + ${b}`, `y = ${m}x - ${b}`],
      answer: 0,
      explanation: "Slope-intercept form is y = mx + b.",
    };
  }
  return {
    id: `sat-curated-ext-${n}`,
    skill,
    prompt: `Which sentence best supports a paragraph about ${topic}?`,
    choices: [
      "Many things exist in the world.",
      `A pilot program on ${topic} reported measurable gains for participants in the study described.`,
      "People sometimes disagree.",
      "History is long.",
    ],
    answer: 1,
    explanation: "A specific, relevant result directly supports the paragraph's claim.",
  };
}

const toefl = Array.from({ length: 31 }, (_, i) => toeflItem(i + 1));
const sat = Array.from({ length: 31 }, (_, i) => satItem(i + 1));

const source = `import type { EnglishPracticeQuestion } from "./english-content";

/** Curated extended bank — replaces batch3 templates. Generated by scripts/generate-curated-extended.ts */
export const curatedExtendedToeflQuestions: EnglishPracticeQuestion[] = ${JSON.stringify(toefl, null, 2)};

export const curatedExtendedSatQuestions: EnglishPracticeQuestion[] = ${JSON.stringify(sat, null, 2)};
`;

writeFileSync(path.join(root, "../data/english-questions-curated-extended.ts"), source, "utf8");
console.log(`Wrote curated extended: ${toefl.length} TOEFL + ${sat.length} SAT`);
