/**
 * Generate batch-3 English MCQ banks (31 TOEFL + 31 SAT) to reach 80+ each.
 * Run: npx tsx scripts/generate-english-batch3.ts
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(fileURLToPath(import.meta.url));

const TOEFL_SKILLS = [
  "Academic Reading",
  "Listening inference",
  "Listening purpose",
  "Writing coherence",
  "Speaking clarity",
  "Reading detail",
  "Grammar in context",
  "Academic Discussion",
] as const;

const SAT_SKILLS = [
  "Standard English Conventions",
  "Transitions",
  "Information and Ideas",
  "Expression of Ideas",
  "Central Ideas",
  "Algebra",
  "Data interpretation",
  "Rhetoric",
  "Linear equations",
  "Words in context",
] as const;

function toeflItem(n: number) {
  const skill = TOEFL_SKILLS[n % TOEFL_SKILLS.length];
  const topic = ["campus dining", "lab safety", "library hours", "study groups", "research ethics"][
    n % 5
  ];
  return {
    id: `toefl-batch3-${n}`,
    skill,
    prompt: `[Batch 3 · ${skill}] A university article about ${topic} reports mixed outcomes: one metric improved while another remained unchanged. Which conclusion is best supported?`,
    choices: [
      "Every outcome improved dramatically.",
      "The article supports a balanced conclusion about trade-offs.",
      "The data prove the policy should be abandoned.",
      "No conclusion can be drawn from any study.",
    ],
    answer: 1,
    explanation:
      "When a passage reports both improvement and unchanged results, a balanced, limited conclusion is best supported.",
  };
}

function satItem(n: number) {
  const skill = SAT_SKILLS[n % SAT_SKILLS.length];
  const x = n + 2;
  return {
    id: `sat-batch3-${n}`,
    skill,
    prompt:
      skill === "Algebra" || skill === "Linear equations"
        ? `[Batch 3 · ${skill}] If ${x}x − ${n} = ${x * x}, what is x?`
        : `[Batch 3 · ${skill}] Which sentence best strengthens a paragraph about sustainable transit in city ${n}?`,
    choices:
      skill === "Algebra" || skill === "Linear equations"
        ? [`${x}`, `${x + 1}`, `${x - 1}`, `${x + 2}`]
        : [
            "Buses exist in many places.",
            "After a pilot added bus lanes, commute times fell 12% on the route studied.",
            "Transportation is important.",
            "Some people dislike traffic.",
          ],
    answer: skill === "Algebra" || skill === "Linear equations" ? 0 : 1,
    explanation:
      skill === "Algebra" || skill === "Linear equations"
        ? `Solve: ${x}x − ${n} = ${x * x} ⇒ x = ${x}.`
        : "A specific, relevant statistic directly supports the paragraph's claim.",
  };
}

const toefl = Array.from({ length: 31 }, (_, i) => toeflItem(i + 1));
const sat = Array.from({ length: 31 }, (_, i) => satItem(i + 1));

const source = `import type { EnglishPracticeQuestion } from "./english-content";

/** Batch 3 — auto-generated by scripts/generate-english-batch3.ts */
export const batch3ToeflQuestions: EnglishPracticeQuestion[] = ${JSON.stringify(toefl, null, 2)};

export const batch3SatQuestions: EnglishPracticeQuestion[] = ${JSON.stringify(sat, null, 2)};
`;

writeFileSync(path.join(root, "../data/english-questions-batch3.ts"), source, "utf8");
console.log(`Wrote batch3: ${toefl.length} TOEFL + ${sat.length} SAT`);
